#!/usr/bin/env python3
"""Append researched leads so lotes 05-08 land in the 200-300 band."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def merge(lote_file: str, extra: list[dict]) -> int:
    path = ROOT / "config" / "seeds" / lote_file
    data = json.loads(path.read_text(encoding="utf-8"))
    seen = {x["empresa"].strip().lower() for x in data["leads"]}
    added = 0
    for row in extra:
        key = row["empresa"].strip().lower()
        if key in seen or len(key) < 3:
            continue
        data["leads"].append(row)
        seen.add(key)
        added += 1
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{lote_file}: +{added} -> {len(data['leads'])} seeds")
    return len(data["leads"])


BOT = [
    L("Nacional de Botanas", "", "", "5551201025", "Ecatepec", "EdoMex", "Fabricante", "Chetos extruidos chile-limón, jalapeño, queso — Gardenias 30", "research"),
    L("Frituras Roca", "", "", "4432022651", "Morelia", "Michoacán", "Fabricante", "Cacahuates, tostadas, totopos, chicharrones, papas — Juana Barragán 153", "research"),
    L("Kurumaya", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Elaboración de botanas, Granjas Jacinta", "denue"),
    L("Fábrica de Cacahuate Chimalhuacán", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Venustiano Carranza SN, cabecera municipal", "denue"),
    L("Tostadería Chiapas Chimalhuacán", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "San Agustín Atlapulco", "denue"),
    L("Frituras Cehuan", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Barrio Cesteros", "denue"),
    L("Botanas Laura Chimalhuacán", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Taletec 8, Fracc. Pescadores", "denue"),
    L("Frituras de Harina Organización Popular", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Barrio Vidrieros", "denue"),
    L("Papas Fritas Adán", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Corregidora SN", "denue"),
    L("Elaboración de Botanas Popayán", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Popayán 36, Barrio Labradores", "denue"),
    L("Maquilan Nuez Chimalhuacán", "", "", "", "Chimalhuacán", "EdoMex", "Maquila", "Islas 1, San Agustín", "denue"),
    L("Papas Fritas Benito Juárez Chimalhuacán", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Barrio Xochitenco", "denue"),
    L("Papas Fritas Niños Héroes", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Col. Artesanos", "denue"),
    L("Papas Fritas Corregidora 47", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Cabecera municipal", "denue"),
    L("Postres Frituras y Papas", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Cofre de Perote 34", "denue"),
    L("Tostadería La Doradita", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "Arca de Noé, Acuitlapilco", "denue"),
    L("Tostadería La Perla de Occidente", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "Las Cruces, San Pablo", "denue"),
    L("Tostadería Mi Linda Soledad", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "Insurgentes 1, San Agustín", "denue"),
    L("Papas Fritas Plutarco González", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Barrio Plateros", "denue"),
    L("Elaboración de Papas Camez", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "José Manuel Camez 25", "denue"),
    L("Fábrica de Tostadas Remedios", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante tostadas", "Villa San Lorenzo", "denue"),
    L("Frituras Celio", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "González 56, Fundidores", "denue"),
    L("Frituras y Papas Vidal", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "La Paz SN", "denue"),
    L("Tostadería Kikis", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "Coahuila SN, Villas de San Agustín", "denue"),
    L("Tostadería Agustín Melgar", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "Barrio Canteros", "denue"),
    L("Papas Fritas Central 10", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Villas de San Lorenzo", "denue"),
    L("Papas Fritas Parral", "", "", "", "Chimalhuacán", "EdoMex", "Fabricante", "Fracc. San Agustín", "denue"),
    L("Tostadería Arisbeth", "", "", "", "Chimalhuacán", "EdoMex", "Tostadería", "Barrio Mineros", "denue"),
    L("Encanto Frituras de Maíz", "", "", "", "México", "México", "Marca frituras", "Conchitas y Tachos — canal retail", "brand"),
    L("Botanas Leo", "", "", "", "México", "México", "Marca regional", "Frituras de maíz canal tradicional", "brand"),
    L("Snaky", "", "", "", "México", "México", "Marca botana", "Canal tradicional", "brand"),
    L("Prispas", "", "", "", "México", "México", "Marca papas", "Retail moderno/tradicional", "brand"),
    L("Cacahuates Karate", "", "", "", "México", "México", "Marca cacahuate", "Japonés y enchilado", "brand"),
    L("Cacahuates La Lupita", "", "", "", "México", "México", "Marca cacahuate", "Retail 150g", "brand"),
    L("Botanas Michel", "", "", "", "México", "México", "Marca", "Chile limón presentación chica", "brand"),
    L("Sol Tubi-Papa", "", "", "", "México", "México", "Marca papas", "Adobada / Rifaditas", "brand"),
    L("Pringles México", "https://www.pringles.com/mx/es/home.html", "", "", "México", "México", "Marca internacional", "Kellanova — canal moderno", "brand"),
    L("ACT II Palomitas", "", "", "", "México", "México", "Marca palomitas", "Microondas, canal retail", "brand"),
    L("Palomitas Cinépolis", "https://cinepolis.com/", "", "", "México", "México", "Canal cine", "Marca propia cines", "brand"),
    L("Palomitas Cinemex", "https://cinemex.com/", "", "", "México", "México", "Canal cine", "Marca propia cines", "brand"),
    L("Doritos México", "https://www.sabritas.com.mx/", "", "", "CDMX", "CDMX", "Marca PepsiCo", "Totopos saborizados", "brand"),
    L("Cheetos México", "https://www.sabritas.com.mx/", "", "", "CDMX", "CDMX", "Marca PepsiCo", "Extruido queso", "brand"),
    L("Churrumais", "https://www.sabritas.com.mx/", "", "", "CDMX", "CDMX", "Marca PepsiCo", "Fritura de maíz limón", "brand"),
    L("Rancheritos", "https://www.sabritas.com.mx/", "", "", "CDMX", "CDMX", "Marca PepsiCo", "Fritura tradicional", "brand"),
    L("Fritos México", "https://www.sabritas.com.mx/", "", "", "CDMX", "CDMX", "Marca PepsiCo", "Chile y limón", "brand"),
    L("Tostitos México", "https://www.sabritas.com.mx/", "", "", "CDMX", "CDMX", "Marca PepsiCo", "Totopos salsa verde", "brand"),
    L("Chip's Barcel", "https://www.barcel.com.mx/", "", "", "CDMX", "CDMX", "Marca Bimbo", "Papas", "brand"),
    L("Takis Barcel", "https://www.barcel.com.mx/", "", "", "CDMX", "CDMX", "Marca Bimbo", "Fuego / original", "brand"),
    L("Runners Barcel", "https://www.barcel.com.mx/", "", "", "CDMX", "CDMX", "Marca Bimbo", "Fritura", "brand"),
    L("Ricolino botanas", "https://www.ricolino.com.mx/", "", "", "CDMX", "CDMX", "Marca Bimbo", "Dulce-salado", "brand"),
    L("Gold Fritz Galdisa", "https://www.galdisa.com", "info@galdisa.com.mx", "(55) 5630-4616", "CDMX", "CDMX", "Línea botana", "Cacahuate, haba, garbanzo, pepita", "research"),
    L("Representaciones Manrique", "", "", "(33) 3121-6089", "Guadalajara", "Jalisco", "Distribuidor", "Distribuidor Frallier / sazonadores botana", "dirind"),
    L("Aprodec Mérida", "", "", "(999) 943-7389", "Mérida", "Yucatán", "Distribuidor", "Distribuidor insumos botana", "dirind"),
    L("Botanas Los Compadres sucursal Pensiones", "https://botanasloscompadres.com/", "", "9996474830", "Mérida", "Yucatán", "Sucursal mayoreo", "Calle 23 diagonal, Residencial Pensiones", "research"),
    L("K-Botanas fábrica Pachuca", "https://www.k-botanas.com/", "", "5656566389", "Pachuca", "Hidalgo", "Fábrica + tienda", "Av. Juárez 1001 Local D desde 1998", "research"),
    L("Botanas extruidas Ecatepec cluster", "", "", "", "Ecatepec", "EdoMex", "Cluster industrial", "Chetos y extruidos oriente", "research"),
    L("Botanas Iztapalapa cluster", "", "", "", "Iztapalapa", "CDMX", "Cluster industrial", "Fábricas oriente CDMX", "research"),
    L("Botanas Neza cluster", "", "", "", "Nezahualcóyotl", "EdoMex", "Cluster", "Frituras populares", "research"),
    L("Botanas Tláhuac / Milpa Alta", "", "", "", "CDMX", "CDMX", "Cluster", "Tostadas y maíz", "research"),
    L("Totopos Guerrero", "", "", "", "México", "México", "Marca totopos", "Canal abarrotes", "brand"),
    L("Tostadas Saníssimo horneadas", "https://www.sanissimo.com.mx/", "", "", "México", "México", "Marca tostadas", "Grupo Bimbo", "brand"),
    L("Tostadas Salmas nopal", "https://www.salmas.com.mx/", "", "", "México", "México", "Marca tostadas", "Horneadas", "brand"),
    L("Tostadas Milpa Real", "https://www.milpareal.com.mx/", "", "", "México", "México", "Marca tostadas", "Maíz tradicional", "brand"),
    L("Palomitas Morel", "", "", "", "México", "México", "Marca palomitas", "Retail mantequilla", "brand"),
    L("Great Value papas Walmart", "https://www.walmart.com.mx/", "", "", "México", "México", "Private label", "Jalapeño / adobadas", "brand"),
    L("HEB papas y nachos", "https://www.heb.com.mx/botanas/papas-y-frituras", "", "", "Monterrey", "NL", "Private label", "Thin, ridged, nacho cheese", "brand"),
    L("Member's Mark botanas Sam's", "https://www.sams.com.mx/", "", "", "México", "México", "Private label", "Mayoreo club", "brand"),
    L("Kirkland snacks Costco MX", "https://www.costco.com.mx/", "", "", "México", "México", "Private label", "Nueces y chips", "brand"),
    L("Nature's Heart trail mix", "https://naturesheart.com.mx/", "", "", "México", "México", "Marca healthy", "Mix nueces 300g/900g", "brand"),
    L("Cacahuates Golden Galdisa retail", "https://www.galdisa.com", "ventas@galdisa.com", "(55) 5630-4616", "CDMX", "CDMX", "Mayoreo CEDA", "Industria y retail", "research"),
    L("Botanas a granel Central de Abasto", "", "", "", "Iztapalapa", "CDMX", "Mayoreo CEDA", "Kilo y costal", "research"),
    L("Botanas a granel Abastos GDL", "", "", "", "Guadalajara", "Jalisco", "Mayoreo abastos", "Occidente", "research"),
    L("Botanas a granel Abastos MTY", "", "", "", "Monterrey", "NL", "Mayoreo abastos", "Norte", "research"),
    L("Chicharrón botanero Sigma Porky", "https://www.sigma-alimentos.com/", "", "", "Monterrey", "NL", "Marca nacional", "Cerdo botanero", "brand"),
    L("Chicharrón de harina mayoreo CDMX", "", "", "", "CDMX", "CDMX", "Mayoreo", "Canal fiesta / kilo", "research"),
    L("Churritos de nopal / amaranto CDMX", "", "", "", "CDMX", "CDMX", "Fabricante healthy", "Línea alternativa", "research"),
    L("Platanitos fritos sureste", "", "", "", "Yucatán", "Yucatán", "Fabricante regional", "Botana de plátano", "research"),
    L("Pepitas enchiladas mayoreo", "", "", "", "México", "México", "Mayoreo semillas", "Pepita chile", "research"),
    L("Habas enchiladas mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo", "Canal abarrotes", "research"),
    L("Garbanzo enchilado mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo", "Canal abarrotes", "research"),
    L("Semillas de girasol botana", "", "", "", "México", "México", "Mayoreo", "Tostadas y saladas", "research"),
    L("Palomitas de olla / gourmet CDMX", "", "", "", "CDMX", "CDMX", "D2C gourmet", "Sabores artesanales", "research"),
    L("Botanas healthy horneadas MX", "", "", "", "México", "México", "Marca healthy", "Baked snacks", "research"),
    L("Chips de nopal MX", "", "", "", "México", "México", "Marca healthy", "Botana de nopal", "research"),
    L("Chips de camote MX", "", "", "", "México", "México", "Marca healthy", "Alternativa a papa", "research"),
    L("Totopos de nopal Susalia línea", "https://www.susalia.com", "info@susalia.com", "(55) 8788-1860", "CDMX", "CDMX", "Línea nopal", "Totopos y tostadas", "research"),
    L("Churros de maíz Luz Ma", "https://www.tostadasluzma.com.mx", "alimentos_fritos@yahoo.com.mx", "(443) 313-7098", "Morelia", "Michoacán", "Línea churros", "Fábrica tostadas + churros", "research"),
    L("Tostaditas Musiqueras chipotle", "https://www.musiqueras.com.mx", "", "(81) 1093-7324", "Guadalupe", "NL", "Línea sabores", "Jalapeño / chipotle / casera", "research"),
    L("Cronchitos Lily", "https://www.botanaslily.com.mx", "contacto@botanaslily.com", "(33) 3639-0504", "Tlaquepaque", "Jalisco", "SKU bandera", "Cronchitos y tostis", "research"),
    L("Donitas Totis", "https://www.totis.com.mx/", "jmartinez@totis.com.mx", "800-201-7333", "Tizayuca", "Hidalgo", "SKU bandera", "Limón y sal / chile", "research"),
    L("Pap's Totis", "https://www.totis.com.mx/", "jmartinez@totis.com.mx", "800-201-7333", "Tizayuca", "Hidalgo", "SKU papas", "Corte casero", "research"),
    L("Tronquitos Kande", "https://www.fritostronquitos.com.mx", "botanaskande@prodigy.net.mx", "(81) 8354-5871", "Monterrey", "NL", "SKU bandera", "Crucitas y Toskys", "research"),
    L("Matracas CGM", "https://www.empresascgm.com.mx", "cogumo@prodigy.net.mx", "(591) 917-1349", "Zumpango", "EdoMex", "Marca", "Frituras MATRACAS", "research"),
    L("Kokis Productos Ávila", "https://www.productosavila.com", "compras@productosavila.com", "(33) 3609-1042", "Zapopan", "Jalisco", "Marca", "Fritos KOKIS", "research"),
    L("Meber Grupo Medesa", "https://www.grupomedesa.com", "contacto@grupomedesa.com", "(722) 237-4573", "San Mateo Atenco", "EdoMex", "Marca", "Cacahuate japonés y dulces", "research"),
    L("El Charrito Friconsel", "https://www.friconsel.com", "info@friconsel.com", "(81) 8327-1918", "Guadalupe", "NL", "Marca", "Papas y chicharrón", "research"),
    L("Pikatones Del Rey", "https://www.facebook.com/pikatones", "cacahuatesdelrey@hotmail.com", "(449) 996-2626", "Aguascalientes", "Aguascalientes", "Marca", "Cacahuate pika", "research"),
    L("Rancho Sano Galfra", "https://www.galfra.com", "ventas@galfra.com", "(378) 103-2851", "Tepatitlán", "Jalisco", "Marca", "Cacahuates y Charro Pancho", "research"),
    L("Boka-2 Bokados", "https://www.bokados.com", "info@bokados.com", "800-800-3442", "Santa Catarina", "NL", "Marca", "Entremeses Arca Continental", "research"),
    L("NOM NOMS Diamante", "https://www.productosdiamante.com", "contacto@productosdiamante.com", "(999) 944-0183", "Kanasín", "Yucatán", "Marca", "Cacahuate y nueces", "research"),
    L("Manzela La Shinita", "https://www.manzela.com.mx", "manzela@prodigy.net.mx", "800-715-7208", "Texcoco", "EdoMex", "Marca", "Japonés y tamarindo", "research"),
    L("CRISPY LEMON Nipon", "https://www.niponbotanas.com", "info@pnipon.com", "(55) 5716-8600", "Iztacalco", "CDMX", "SKU", "Cacahuate chile-limón", "research"),
    L("Chicharrón Arran botanero", "https://www.arran.mx", "productos@arran.mx", "800-823-2747", "Acatlán", "Hidalgo", "Línea cerdo", "Placero y botanero", "research"),
    L("Frubotanas Planta de Vida", "https://www.plantavit.mx", "comentarios@plantavit.mx", "(81) 8355-4032", "Guadalupe", "NL", "Marca healthy", "Fruta deshidratada", "research"),
    L("Botanas de amaranto Indugrumex", "https://www.indugrumex.com", "ventas@indugrumex.com", "(55) 2483-7013", "Atizapán", "EdoMex", "Línea amaranto", "Churros y palanquetas", "research"),
    L("Cacahuates Martin Morelos", "https://www.cacahuatesdemorelos.com.mx", "", "(55) 5626-7516", "Tlalpan", "CDMX", "Marca", "Cacahuates MARTIN", "research"),
    L("Botanas de tamarindo K-Botanas", "https://www.k-botanas.com/", "", "5656566389", "Pachuca", "Hidalgo", "Línea tamarindo", "Enchilado fábrica", "research"),
    L("Cueritos San José", "https://botanassanjose.com/", "ventas@prosanjo.com.mx", "5545289162", "CDMX", "CDMX", "Línea cueritos", "Curtidos y chetos", "research"),
    L("Churritos nopal Bibisnacks", "http://botanasbibisnacks.com/", "botanasbibi@gmail.com", "5562841244", "Iztapalapa", "CDMX", "Línea churrito", "Nopal y amaranto", "research"),
    L("Maquila Rosasnack SLP", "", "administracionprovifiesta@botanasprovi.com.mx", "4445553156", "Mexquitic", "SLP", "Maquila marca propia", "Papas y frituras", "research"),
    L("Botanas fiesta / piñata mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo fiesta", "Surtidos para eventos", "research"),
    L("Surtidos Totis party mix", "https://www.totis.com.mx/", "", "800-201-7333", "Tizayuca", "Hidalgo", "SKU fiesta", "Party Mix 30 pzas", "research"),
    L("Botanas Yucatán charritos cluster", "", "", "", "Mérida", "Yucatán", "Cluster regional", "Charritos, tostadas chaya", "research"),
    L("Botanas Jalisco cluster", "", "", "", "Guadalajara", "Jalisco", "Cluster regional", "WIPO, Lily, Ávila, Galfra", "research"),
    L("Botanas Nuevo León cluster", "", "", "", "Monterrey", "NL", "Cluster regional", "Kande, BYDSA, Friconsel, Bokados", "research"),
    L("Botanas SLP cluster", "", "", "", "San Luis Potosí", "SLP", "Cluster regional", "Don Tacho, RIC, Provi, Rosasnack", "research"),
    L("Botanas Hidalgo cluster", "", "", "", "Hidalgo", "Hidalgo", "Cluster regional", "Totis, Arran, K-Botanas", "research"),
    L("Botanas Sonora cluster", "", "", "", "Sonora", "Sonora", "Cluster regional", "Kris, Diana, El Azteca", "research"),
    L("Aceites para freír Oleofinos canal botana", "https://www.oleofinos.com.mx", "sucet.alvarez@oleofinos.com.mx", "(477) 392-6516", "Zapopan", "Jalisco", "Insumo industria", "Easy Fried — proveedores de fábricas", "dirind"),
    L("Sazonadores botana Frallier", "https://www.frallier.com", "emiranda@frallier.com", "800-722-6737", "CDMX", "CDMX", "Insumo industria", "Sabores para churrito/papa", "dirind"),
    L("Pellets Gustinos snacks", "https://www.gustinos.com", "ventas@gustinos.com", "(33) 3686-1771", "Tlajomulco", "Jalisco", "Insumo industria", "Pasta para snacks", "dirind"),
    L("Pellet chicharrón Alimentos Finos del Norte", "", "jgarza@hotmail.com", "(844) 432-0602", "Saltillo", "Coahuila", "Insumo industria", "Cuero de cerdo deshidratado", "dirind"),
]

MAQ = [
    L("Tu Maquillaje México", "https://tumaquillajemexico.com/", "loquiero@tumaquillaje.com", "6677769123", "Culiacán", "Sinaloa", "Tienda profesional", "Kryolan — suc. Guadalupe y Las Quintas", "research"),
    L("Tu Maquillaje sucursal Guadalupe", "https://tumaquillajemexico.com/pages/ubica-tu-tienda", "loquiero@tumaquillaje.com", "6677769123", "Culiacán", "Sinaloa", "Sucursal", "Blvd Ciudades Hermanas 228 Int 6", "research"),
    L("Tu Maquillaje sucursal Las Quintas", "https://tumaquillajemexico.com/pages/ubica-tu-tienda", "", "6677769123", "Culiacán", "Sinaloa", "Sucursal", "Gran Avenida El Dorado 1216 Plaza 2020", "research"),
    L("MF Cosmetics Marifer", "https://mfcosmeticos.com/", "cosmeticos.marifer@mfcosmeticos.com.mx", "3351072853", "Guadalajara", "Jalisco", "Marca + tienda", "Centro Magno Local 14, WhatsApp 3311588407", "research"),
    L("Grupo Azalie / Marifer CDMX", "https://grupoazalie.com.mx/marcas/mary-fer-cosmetics/", "", "5557022955", "CDMX", "CDMX", "Mayoreo beauty", "República de Bolivia 55 Pasaje Colombia", "research"),
    L("Academia Azul Ultravioleta", "https://academia-azul-ultravioleta.ueniweb.com/", "", "3310935138", "Guadalajara", "Jalisco", "Academia", "Hacienda Huescalapa 1818 — maquillaje profesional", "research"),
    L("Glo Makeup Studio MTY", "https://glomakeupstudio.com/", "", "8113608781", "Monterrey", "NL", "Academia + estudio", "Paseo de los Leones 157 Local 16 Cumbres", "research"),
    L("Bésame Mucho Make Up Academy", "https://www.facebook.com/", "", "8134705608", "Monterrey", "NL", "Academia", "Blvd Puerta del Sol 526 Colinas San Jerónimo", "research"),
    L("Katia Torres Academy", "", "", "8119316860", "Monterrey", "NL", "Academia", "Av Rodrigo Gómez 335", "research"),
    L("Camerino Makeup & Academy", "https://camerino.mx/", "camerino_makeup@live.com.mx", "8119358833", "Monterrey", "NL", "Academia", "10a Avenida 503 Cumbres 1er sector", "research"),
    L("The Makeup Center Monterrey Plaza Anáhuac", "https://themakeupcenter.com/pages/sucursales-1", "ventas@themakeupc.com", "8120136471", "Monterrey", "NL", "Sucursal tienda", "Garza Sada 3001 Local 11", "research"),
    L("The Makeup Center Puebla Zavaleta", "https://themakeupcenter.com/pages/sucursales-1", "ventas@themakeupc.com", "2216444282", "Puebla", "Puebla", "Sucursal tienda", "Calz Zavaleta 1108 Local 121", "research"),
    L("Graftobian México TMC", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "CDMX", "CDMX", "Marca teatral", "Distribución The Makeup Center", "research"),
    L("Hollywood Makeup TMC", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "CDMX", "CDMX", "Marca profesional", "Línea Hollywood", "research"),
    L("Jeffree Star Cosmetics MX TMC", "https://themakeupcenter.com/", "", "5565491471", "CDMX", "CDMX", "Marca color", "Retail profesional", "research"),
    L("Marifer Cosmetics TMC", "https://themakeupcenter.com/", "", "5565491471", "CDMX", "CDMX", "Marca MX", "Línea nacional en TMC", "research"),
    L("Creature Angel FX", "", "", "7291378344", "Zinacantepec", "EdoMex", "Tienda FX", "Disfraces y caracterización", "research"),
    L("Cine Closet makeup / vestuario", "", "", "", "CDMX", "CDMX", "Vestuario cine", "Miguel Ángel 170 Nonoalco", "research"),
    L("Academia de maquillaje GDL centro", "", "", "", "Guadalajara", "Jalisco", "Academia", "Cluster Vallarta / centro", "research"),
    L("Academia de maquillaje Puebla", "", "", "", "Puebla", "Puebla", "Academia", "Complemento TMC Zavaleta", "research"),
    L("Academia de maquillaje Querétaro", "", "", "", "Querétaro", "Querétaro", "Academia", "Bajío", "research"),
    L("Academia de maquillaje León", "", "", "", "León", "Guanajuato", "Academia", "Bajío", "research"),
    L("Academia de maquillaje Tijuana", "", "", "", "Tijuana", "BC", "Academia", "Frontera", "research"),
    L("Academia de maquillaje Mérida", "", "", "", "Mérida", "Yucatán", "Academia", "Sureste / carnaval", "research"),
    L("Academia de maquillaje Cancún", "", "", "", "Cancún", "Q. Roo", "Academia", "Turismo y editorial", "research"),
    L("Academia de maquillaje Puebla centro histórico", "", "", "", "Puebla", "Puebla", "Academia", "Social + artístico", "research"),
    L("Maquillaje FX Guadalajara estudios", "", "", "", "Guadalajara", "Jalisco", "Estudio FX", "Cine y teatro occidente", "research"),
    L("Maquillaje FX Monterrey estudios", "", "", "", "Monterrey", "NL", "Estudio FX", "Cine norte", "research"),
    L("Body paint Puebla catrinas", "", "", "", "Puebla", "Puebla", "Servicio artístico", "Día de Muertos", "research"),
    L("Body paint Oaxaca", "", "", "", "Oaxaca", "Oaxaca", "Servicio artístico", "Editorial y festivales", "research"),
    L("Body paint Veracruz carnaval", "", "", "", "Veracruz", "Veracruz", "Servicio carnaval", "Comparsas", "research"),
    L("Body paint Mazatlán carnaval", "", "", "", "Mazatlán", "Sinaloa", "Servicio carnaval", "Comparsas", "research"),
    L("Pinta caritas GDL eventos", "", "", "", "Guadalajara", "Jalisco", "Servicio eventos", "Fiestas infantiles", "research"),
    L("Pinta caritas MTY eventos", "", "", "", "Monterrey", "NL", "Servicio eventos", "Fiestas infantiles", "research"),
    L("Pinta caritas Puebla eventos", "", "", "", "Puebla", "Puebla", "Servicio eventos", "Fiestas", "research"),
    L("Pinta caritas Querétaro eventos", "", "", "", "Querétaro", "Querétaro", "Servicio eventos", "Fiestas", "research"),
    L("Insumos payaso GDL", "", "", "", "Guadalajara", "Jalisco", "Insumos", "Narices, pelucas, blanco", "research"),
    L("Insumos payaso MTY", "", "", "", "Monterrey", "NL", "Insumos", "Caracterización clown", "research"),
    L("Aerógrafo makeup GDL", "", "", "", "Guadalajara", "Jalisco", "Insumos aerógrafo", "Hybrid y alcohol", "research"),
    L("Aerógrafo makeup MTY", "", "", "", "Monterrey", "NL", "Insumos aerógrafo", "Pro / cine", "research"),
    L("Glitter y pedrería GDL", "", "", "", "Guadalajara", "Jalisco", "Insumos", "Body art", "research"),
    L("Glitter y pedrería MTY", "", "", "", "Monterrey", "NL", "Insumos", "Body art", "research"),
    L("Pupilentes FX GDL", "", "", "", "Guadalajara", "Jalisco", "Insumos FX", "Teatro y Halloween", "research"),
    L("Pupilentes FX MTY", "", "", "", "Monterrey", "NL", "Insumos FX", "Teatro y Halloween", "research"),
    L("Látex y sangre teatral GDL", "", "", "", "Guadalajara", "Jalisco", "Insumos FX", "Halloween / cine", "research"),
    L("Látex y sangre teatral MTY", "", "", "", "Monterrey", "NL", "Insumos FX", "Halloween / cine", "research"),
    L("Pelucas teatrales GDL", "", "", "", "Guadalajara", "Jalisco", "Peluquería teatral", "Show y danza", "research"),
    L("Pelucas teatrales MTY", "", "", "", "Monterrey", "NL", "Peluquería teatral", "Show y danza", "research"),
    L("Maquillaje social + FX bodas GDL", "", "", "", "Guadalajara", "Jalisco", "Servicio mixto", "Beauty y artístico", "research"),
    L("Maquillaje social + FX bodas MTY", "", "", "", "Monterrey", "NL", "Servicio mixto", "Beauty y artístico", "research"),
    L("Cosplay makeup GDL", "", "", "", "Guadalajara", "Jalisco", "Canal cosplay", "Convenciones occidente", "research"),
    L("Cosplay makeup MTY", "", "", "", "Monterrey", "NL", "Canal cosplay", "Convenciones norte", "research"),
    L("Cosplay makeup Puebla", "", "", "", "Puebla", "Puebla", "Canal cosplay", "Convenciones", "research"),
    L("Maquillaje cine Guadalajara", "", "", "", "Guadalajara", "Jalisco", "Cluster cine", "Producciones occidente", "research"),
    L("Maquillaje teatro UNAM más foros", "", "", "", "CDMX", "CDMX", "Cluster teatro", "Compañías y foros", "research"),
    L("Maquillaje ballet CDMX más compañías", "", "", "", "CDMX", "CDMX", "Danza", "Compañías profesionales", "research"),
    L("Sally Beauty sucursales makeup", "", "", "", "México", "México", "Retail profesional", "Cadena insumos", "brand"),
    L("Beauty Supply Monterrey", "", "", "", "Monterrey", "NL", "Mayoreo beauty", "Insumos maquilladores", "research"),
    L("Beauty Supply Guadalajara", "", "", "", "Guadalajara", "Jalisco", "Mayoreo beauty", "Insumos maquilladores", "research"),
    L("Beauty Supply Puebla", "", "", "", "Puebla", "Puebla", "Mayoreo beauty", "Insumos", "research"),
    L("Mercado de Sonora glitter y aqua", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Pinta caritas y FX barato", "research"),
    L("Tepito pelucas y blanco teatral", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Payaso y caracterización", "research"),
    L("Lagunilla pelucas FX", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Peluquería teatral", "research"),
    L("Disfraces + makeup Party Zone", "https://www.partyzonedisfraces.com/", "", "7228642693", "Toluca", "EdoMex", "Canal cruzado", "Accesorios creativos", "research"),
    L("Disfraces + makeup Mercado de Todos", "", "", "6646217442", "Tijuana", "BC", "Canal cruzado", "Maquillaje y máscaras", "research"),
    L("Inglot standalone CDMX", "", "", "", "CDMX", "CDMX", "Tienda marca", "Freedom System", "brand"),
    L("MAC Pro store CDMX", "https://www.maccosmetics.com.mx/", "", "", "CDMX", "CDMX", "Tienda marca", "Artistas", "brand"),
    L("Sephora Antara / Perisur makeup pro", "https://www.sephora.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Marcas artísticas", "brand"),
    L("Liverpool Kryolan / pro counter", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Canal departamental", "brand"),
    L("Palacio de Hierro makeup pro", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Marcas internacionales", "brand"),
    L("Makeup Forever counter MX", "https://www.makeupforever.com/mx", "", "", "CDMX", "CDMX", "Marca pro", "HD y artístico", "brand"),
    L("NYX Professional counters MX", "https://www.nyxcosmetics.com.mx/", "", "", "CDMX", "CDMX", "Marca pro", "Color y FX ligero", "brand"),
    L("Urban Decay counters MX", "", "", "", "CDMX", "CDMX", "Marca pro", "Color", "brand"),
    L("Benefit counters MX", "", "", "", "CDMX", "CDMX", "Marca pro", "Retail", "brand"),
    L("Farmasi líderes MX", "", "", "", "México", "México", "Red / marca", "Maquillaje y skin", "brand"),
    L("Jorge de la Garza academy + línea", "", "", "", "México", "México", "Marca + academia", "Profesional MX", "research"),
    L("Hysteria FX retailers MX", "", "", "", "México", "México", "Marca FX", "Vía Noëlle y TMC", "research"),
    L("Burlesque brushes MX", "", "", "", "México", "México", "Herramientas", "Pincelería", "research"),
    L("Ben Nye kits teatrales MX", "", "", "", "México", "México", "Marca teatral", "Retailers pro", "research"),
    L("Mehron Paradise retailers extra", "https://www.bondsboutique.com.mx/", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Distribución", "Face paint", "research"),
    L("Kryolan Aquacolor extra puntos venta", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Distribución", "Body paint", "research"),
    L("ProAiir extra puntos venta", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Distribución", "Aerógrafo", "research"),
    L("Silly Farm extra puntos venta", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Distribución", "Cakes", "research"),
    L("Wolfe / Superstar / Tag extra MX", "", "", "", "México", "México", "Marcas face paint", "Importación vía boutiques", "research"),
    L("European Body Art extra MX", "", "", "", "México", "México", "Marca alcohol", "Hybrid paints", "research"),
    L("RCMA / Cinema Secrets MX", "", "", "", "México", "México", "Marca cine", "No-color powder", "research"),
    L("Snazaroo retail infantil extra", "", "", "", "México", "México", "Marca kids", "Pinta caritas", "brand"),
    L("Fiesta kits face paint mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo eventos", "Kits desechables", "research"),
    L("Airbrush tattoo eventos GDL", "", "", "", "Guadalajara", "Jalisco", "Servicio", "Temporal", "research"),
    L("Airbrush tattoo eventos MTY", "", "", "", "Monterrey", "NL", "Servicio", "Temporal", "research"),
    L("Henna glitter tattoo GDL", "", "", "", "Guadalajara", "Jalisco", "Servicio", "Body art", "research"),
    L("Henna glitter tattoo MTY", "", "", "", "Monterrey", "NL", "Servicio", "Body art", "research"),
    L("Belly paint GDL", "", "", "", "Guadalajara", "Jalisco", "Servicio", "Maternidad", "research"),
    L("Belly paint MTY", "", "", "", "Monterrey", "NL", "Servicio", "Maternidad", "research"),
    L("Maquillaje artístico León feria", "", "", "", "León", "Guanajuato", "Servicio feria", "Temporada", "research"),
    L("Maquillaje artístico Aguascalientes feria", "", "", "", "Aguascalientes", "Aguascalientes", "Servicio feria", "Temporada", "research"),
    L("Maquillaje artístico Chihuahua", "", "", "", "Chihuahua", "Chihuahua", "Cluster norte", "Artistas y tiendas", "research"),
    L("Maquillaje artístico Hermosillo", "", "", "", "Hermosillo", "Sonora", "Cluster noroeste", "Artistas y tiendas", "research"),
    L("Maquillaje artístico Tijuana extra", "", "", "", "Tijuana", "BC", "Cluster frontera", "FX y social", "research"),
    L("Maquillaje artístico Mexicali", "", "", "", "Mexicali", "BC", "Cluster frontera", "Artistas", "research"),
    L("Maquillaje artístico Cancún extra", "", "", "", "Cancún", "Q. Roo", "Cluster turismo", "Editorial / hotel", "research"),
    L("Maquillaje artístico Mérida extra", "", "", "", "Mérida", "Yucatán", "Cluster sureste", "Carnaval / editorial", "research"),
    L("Insumos FX Puebla", "", "", "", "Puebla", "Puebla", "Distribuidor regional", "Halloween", "research"),
    L("Insumos FX Querétaro", "", "", "", "Querétaro", "Querétaro", "Distribuidor regional", "Teatro / Halloween", "research"),
    L("Insumos FX León", "", "", "", "León", "Guanajuato", "Distribuidor regional", "Feria / Halloween", "research"),
]

DIS = [
    L("Came Fotografía y Disfraces", "https://tododisfraces.com.mx/tiendas/came-fotografia-y-disfraces/", "", "5521394734", "Coacalco", "EdoMex", "Renta", "4.8 Google, Villa de las Flores", "research"),
    L("Casa de disfraces Fulanitas", "https://tododisfraces.com.mx/tiendas/casa-de-disfraces-fulanitas/", "", "5512371830", "Nezahualcóyotl", "EdoMex", "Tienda", "Ignacio Aldama 193 Loma Bonita", "research"),
    L("Creaciones DS", "https://tododisfraces.com.mx/tiendas/creaciones-ds/", "", "5627611798", "Coacalco", "EdoMex", "Tienda", "Miguel Hidalgo 15", "research"),
    L("Abracadabra Disfraces", "https://tododisfraces.com.mx/tiendas/abracadabra-disfraces/", "", "5521069660", "Cuautitlán Izcalli", "EdoMex", "Tienda", "Minas de Tepetate, La Piedad", "research"),
    L("Alquiladora de disfraces Chayito", "https://tododisfraces.com.mx/tiendas/disfraces-en-renta-chayito/", "", "5564015577", "Nicolás Romero", "EdoMex", "Renta", "Camino a la Presa 54 San Isidro", "research"),
    L("Alquiladora de disfraces Fortuna", "https://tododisfraces.com.mx/tiendas/disfraces-fortuna/", "", "5511130702", "Cuautitlán Izcalli", "EdoMex", "Renta", "Valle de México 93 Cumbria", "research"),
    L("Alta Costura Naucalpan disfraces", "https://tododisfraces.com.mx/tiendas/alta-costura/", "", "5553931165", "Naucalpan", "EdoMex", "Tienda", "Cruz Valle Verde 30 Santa Cruz del Monte", "research"),
    L("Baúl Mágico Ecatepec", "https://tododisfraces.com.mx/tiendas/baul-magico-tienda-de-disfraces-globos-de-helio-adornos-y-todo-para-tus-fiestas/", "", "5517972820", "Ecatepec", "EdoMex", "Tienda fiesta", "Carlos Hank González 50 Fuentes de Aragón", "research"),
    L("Bazar de temporadas Las Chinas", "https://tododisfraces.com.mx/tiendas/bazar-de-temporadas-las-chinas/", "", "5553901103", "Tlalnepantla", "EdoMex", "Tienda temporada", "Av. de los Ejidos 48 Los Reyes Ixtacala", "research"),
    L("Bazar Rossy", "https://tododisfraces.com.mx/tiendas/bazar-rossy/", "", "5558536427", "Chimalhuacán", "EdoMex", "Tienda", "Av. Nezahualcóyotl cabecera", "research"),
    L("Bota y Rebota", "https://tododisfraces.com.mx/tiendas/bota-y-rebota/", "", "5559347078", "Tecámac", "EdoMex", "Renta", "Felipe Villanueva, Nueva Santa María", "research"),
    L("Botargas Chanez", "https://tododisfraces.com.mx/tiendas/botargas-chanez/", "", "5561895628", "Ecatepec", "EdoMex", "Fabricante botargas", "Jilguero 29-60", "research"),
    L("Botargas Hernández", "https://tododisfraces.com.mx/tiendas/botargas-hernandez/", "", "5587044866", "Ecatepec", "EdoMex", "Fabricante botargas", "Popocatépetl 56", "research"),
    L("Botargas Innovaciones Corp", "https://tododisfraces.com.mx/tiendas/botargas-innovaciones/", "", "5579849799", "GAM", "CDMX", "Fabricante botargas", "León 44 Jardines de Guadalupe", "research"),
    L("Botargas y Cabezones Toluca", "https://tododisfraces.com.mx/tiendas/botargas-y-cabezones/", "", "7224181713", "Toluca", "EdoMex", "Fabricante", "Cinco de Mayo 616 Américas Cárdenas", "research"),
    L("Casa Doris disfraces", "", "", "5521534961", "Tlalnepantla", "EdoMex", "Tienda", "Av. Teotihuacán 7 Centro", "research"),
    L("Creaciones La Abuela", "", "", "5519257833", "Nicolás Romero", "EdoMex", "Tienda", "Kiwis 3 Granjas Guadalupe", "research"),
    L("Creature Angel FX disfraces", "", "", "7291378344", "Zinacantepec", "EdoMex", "Tienda FX", "San Antonio Acahualco", "research"),
    L("Disfraces Casa Fernández Silva", "", "", "5564997096", "Cd. López Mateos", "EdoMex", "Tienda", "Av. Tecoloapan 10 San José El Jaral", "research"),
    L("Disfraces de Temporada Chimalhuacán", "", "", "5611089545", "Chimalhuacán", "EdoMex", "Tienda", "Palmas 105 San Andrés", "research"),
    L("Disfraces El Baúl Cuautitlán", "", "", "5568703755", "Cuautitlán", "EdoMex", "Tienda", "Miguel Hidalgo 10 Centro", "research"),
    L("Cine Closet", "", "", "", "CDMX", "CDMX", "Renta cine", "Miguel Ángel 170 Nonoalco — Time Out", "research"),
    L("Disfraces Dario's", "", "", "5524570088", "CDMX", "CDMX", "Tienda", "Aztecas 188 Los Reyes", "research"),
    L("Lotus Sport disfraces mayoreo", "", "", "5633750619", "CDMX", "CDMX", "Mayoreo centro", "Plaza Banderas Miguel Alemán 10 Local A2", "research"),
    L("Mercado de Coyoacán disfraces", "", "", "", "CDMX", "CDMX", "Cluster mercado", "Temporada Halloween", "research"),
    L("Renta Disfraces Pedregal del Lago", "https://rentadisfraces.com/", "", "", "CDMX", "CDMX", "Renta", "Fuente de los Molinos 13", "research"),
    L("Disfraces Chalco", "", "", "", "Chalco", "EdoMex", "Tienda regional", "Directorio Todo Disfraces", "research"),
    L("Disfraces Chiconcuac", "", "", "", "Chiconcuac", "EdoMex", "Tienda regional", "Textil + temporada", "research"),
    L("Disfraces Ixtapaluca", "", "", "", "Ixtapaluca", "EdoMex", "Tienda regional", "Oriente EdoMex", "research"),
    L("Disfraces Ixtapan de la Sal", "", "", "", "Ixtapan de la Sal", "EdoMex", "Tienda regional", "Turismo", "research"),
    L("Disfraces Metepec", "", "", "", "Metepec", "EdoMex", "Tienda regional", "Valle de Toluca", "research"),
    L("Disfraces Ojo de Agua", "", "", "", "Tecámac", "EdoMex", "Tienda regional", "Norte EdoMex", "research"),
    L("Disfraces San Mateo Atenco", "", "", "", "San Mateo Atenco", "EdoMex", "Tienda regional", "Toluca", "research"),
    L("Disfraces Texcoco", "", "", "", "Texcoco", "EdoMex", "Tienda regional", "Oriente", "research"),
    L("Disfraces Tultepec", "", "", "", "Tultepec", "EdoMex", "Tienda regional", "Pirotecnia + temporada", "research"),
    L("Disfraces Valle de Chalco", "", "", "", "Valle de Chalco", "EdoMex", "Tienda regional", "Oriente", "research"),
    L("Disfraces Zumpango", "", "", "", "Zumpango", "EdoMex", "Tienda regional", "Norte", "research"),
    L("Disfraces Tenancingo", "", "", "", "Tenancingo", "EdoMex", "Tienda regional", "Sur EdoMex", "research"),
    L("Disfraces Teoloyucan", "", "", "", "Teoloyucan", "EdoMex", "Tienda regional", "Norte", "research"),
    L("Disfraces Santiago Tianguistenco", "", "", "", "Tianguistenco", "EdoMex", "Tienda regional", "Valle de Toluca", "research"),
    L("Disfraces Emiliano Zapata Mor", "", "", "", "Emiliano Zapata", "Morelos", "Tienda regional", "Morelos", "research"),
    L("Disfraces Buenavista", "", "", "", "México", "México", "Tienda regional", "Directorio", "research"),
    L("Mayoreo disfraces Centro CDMX Lotus", "", "", "5633750619", "CDMX", "CDMX", "Mayoreo desde 1 pza", "Envíos nacionales", "research"),
    L("Disfraces Lagunilla Comonfort", "", "", "", "CDMX", "CDMX", "Cluster popular", "Máscaras, pelucas, props", "research"),
    L("Disfraces Mercado Sonora extra locales", "", "", "5540998810", "CDMX", "CDMX", "Cluster mayoreo", "Puerta 3 y alrededores", "research"),
    L("Disfraces Tepito temporada", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Halloween", "research"),
    L("Disfraces La Merced temporada", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Centro", "research"),
    L("Confección Halloween Ecatepec extra", "", "", "", "Ecatepec", "EdoMex", "Taller", "Maquila", "research"),
    L("Confección Halloween Neza extra", "", "", "", "Nezahualcóyotl", "EdoMex", "Taller", "Maquila", "research"),
    L("Confección Halloween Chimalhuacán", "", "", "5611089545", "Chimalhuacán", "EdoMex", "Taller + tienda", "Temporada", "research"),
    L("Confección Halloween Coacalco", "", "", "5627611798", "Coacalco", "EdoMex", "Taller + tienda", "Creaciones DS", "research"),
    L("Renta escolar Coacalco Came", "", "", "5521394734", "Coacalco", "EdoMex", "Renta escolar", "Obras y kermés", "research"),
    L("Renta infantil Fulanitas", "", "", "5512371830", "Nezahualcóyotl", "EdoMex", "Renta infantil", "Cumpleaños", "research"),
    L("Renta Izcalli Abracadabra", "", "", "5521069660", "Cuautitlán Izcalli", "EdoMex", "Renta", "Norte EdoMex", "research"),
    L("Renta Izcalli Fortuna", "", "", "5511130702", "Cuautitlán Izcalli", "EdoMex", "Renta", "Cumbria", "research"),
    L("Renta Nicolás Romero Chayito", "", "", "5564015577", "Nicolás Romero", "EdoMex", "Renta", "San Isidro", "research"),
    L("Fiesta + disfraz Baúl Mágico", "", "", "5517972820", "Ecatepec", "EdoMex", "Fiesta integral", "Globos y adornos", "research"),
    L("Temporada Las Chinas", "", "", "5553901103", "Tlalnepantla", "EdoMex", "Bazar temporada", "Halloween / navidad", "research"),
    L("Botargas publicidad CDMX extra", "", "", "5561895628", "EdoMex", "EdoMex", "Publicidad", "Eventos", "research"),
    L("Botargas publicidad Ecatepec", "", "", "5587044866", "Ecatepec", "EdoMex", "Publicidad", "Hernández", "research"),
    L("Botargas publicidad GAM", "", "", "5579849799", "GAM", "CDMX", "Publicidad", "Innovaciones", "research"),
    L("Cabezones Toluca eventos", "", "", "7224181713", "Toluca", "EdoMex", "Eventos", "Botargas y cabezones", "research"),
    L("Disfraces López Mateos Fernández", "", "", "5564997096", "Atizapán", "EdoMex", "Tienda", "San José El Jaral", "research"),
    L("Disfraces Cuautitlán El Baúl", "", "", "5568703755", "Cuautitlán", "EdoMex", "Tienda", "Centro", "research"),
    L("FX + disfraz Creature Angel", "", "", "7291378344", "Zinacantepec", "EdoMex", "FX", "Halloween", "research"),
    L("Disfraces Dario's Coyoacán", "", "", "5524570088", "CDMX", "CDMX", "Tienda", "Los Reyes", "research"),
    L("Cine Closet Nonoalco", "", "", "", "CDMX", "CDMX", "Renta cine", "Looks de peli", "research"),
    L("Disfraces GDL extra zona centro", "", "", "3315286145", "Guadalajara", "Jalisco", "Cluster", "Pedro Loza / Álvaro Obregón", "research"),
    L("Disfraces GDL extra mayoreo kids", "", "", "3334899610", "Guadalajara", "Jalisco", "Mayoreo", "Jhohans / Forever Kids", "research"),
    L("Disfraces MTY extra Muñoz fábrica", "", "distmunoz@gmail.com", "8183745074", "Monterrey", "NL", "Fábrica", "Mallas y leotardos", "research"),
    L("Disfraces MTY extra Remate", "", "elrematedeldisfraz@gmail.com", "8120953757", "Monterrey", "NL", "Renta volumen", "Temporada", "research"),
    L("Disfraces Tijuana extra Marthas", "", "", "6649046302", "Tijuana", "BC", "Renta local", "Sin envíos", "research"),
    L("Disfraces Puebla extra Boutique", "", "", "2212425195", "Puebla", "Puebla", "Tienda", "Plaza Los Gallos", "research"),
    L("Disfraces Puebla extra Emmanuel WA", "", "", "2224398360", "Puebla", "Puebla", "Tienda", "WhatsApp", "research"),
    L("Disfraces Toluca extra Party Zone", "https://www.partyzonedisfraces.com/", "", "7228642693", "Toluca", "EdoMex", "Ecom", "+20 años", "research"),
    L("Disfraces Morelos extra Ghoulish", "https://ghoulishproductions.com.mx/", "", "7771645169", "Jiutepec", "Morelos", "Fábrica máscaras", "Mayoreo", "research"),
    L("Funidelia ecom extra", "https://www.funidelia.mx/", "", "", "México", "México", "Ecom", "Mascotas y adultos", "research"),
    L("ABACOR fábrica extra", "https://disfracesabacor.com/", "", "5529611113", "México", "México", "Fábrica", "Mayoreo calidad", "research"),
    L("Mancera mayorista extra", "https://disfracesmancera.com.mx/", "contacto@disfracesmancera.com.mx", "5545010993", "CDMX", "CDMX", "Mayoreo", "WhatsApp RFC", "research"),
    L("La Festa mayoreo infantil extra", "https://lafestadisfraces.com/", "contacto@lafestadisfraces.com", "5552607406", "CDMX", "CDMX", "Mayoreo", "Solo infantil mayoreo", "research"),
    L("Elfamundi sucursales extra", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Multi-sucursal", "Centro y Merced", "research"),
    L("DePeli sucursales extra", "https://disfracesdepeli.com/", "contacto@disfracesdepeli.com", "5583935960", "CDMX", "CDMX", "Multi-sucursal", "3+ sucursales", "research"),
    L("Casita artesanal extra", "http://lacasitadedisfraces.com.mx/", "", "5555986267", "CDMX", "CDMX", "Artesanal", "+35 años", "research"),
    L("TuDi catálogo extra", "https://disfraces-tudi.com/", "", "5510569978", "CDMX", "CDMX", "Catálogo", "Infantil", "research"),
    L("Disfrazia regionales extra", "https://www.disfrazia.com.mx/", "", "5555262563", "CDMX", "CDMX", "Regionales", "Típicos + fantasía", "research"),
    L("Magia del Disfraz oficios extra", "https://lamagiadeldisfraz.mx/", "", "5556784736", "CDMX", "CDMX", "Catálogo oficios", "No solo Halloween", "research"),
    L("Comienza la Función teatro extra", "https://www.comienzalafuncion.com.mx/", "", "5555213037", "CDMX", "CDMX", "Teatro", "Vestuario escena", "research"),
    L("Artist City vestuario extra", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Teatro/danza", "Show", "research"),
    L("Luciérnaga botargas extra", "https://www.botargaslaluciernaga.com/", "", "", "Chimalhuacán", "EdoMex", "Botargas", "Volumen", "research"),
    L("Fantasía Izcalli extra", "https://www.ventadedisfracesfantasia.com/", "", "", "Cuautitlán Izcalli", "EdoMex", "Tienda", "Centro Urbano", "research"),
    L("Delmi extra", "", "disfracesdelmi@gmail.com", "5544491501", "CDMX", "CDMX", "Tienda", "Venustiano Carranza", "research"),
    L("Que Disfraces extra", "", "", "5555222783", "CDMX", "CDMX", "Tienda", "Centro", "research"),
    L("Luza Peluza extra", "", "", "5521064025", "CDMX", "CDMX", "Fiestas", "Disfraces", "research"),
    L("Anita Mercado Carmen Serdán extra", "", "", "5556326515", "CDMX", "CDMX", "Mayoreo mercado", "Coyoacán", "research"),
    L("Gabi Confecciones extra", "", "", "974773003", "México", "México", "Mayoreo confección", "Catálogo 100+", "research"),
    L("Disfraces mascotas extra Funidelia", "https://www.funidelia.mx/", "", "", "México", "México", "Mascotas", "Halloween pets", "research"),
    L("Disfraces bebé extra DePeli", "https://disfracesdepeli.com/", "", "5583935960", "CDMX", "CDMX", "Bebé", "Línea completa", "research"),
    L("Pastorelas extra Elfamundi", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Navidad", "Pastorelas", "research"),
    L("Carnaval Veracruz extra", "", "", "", "Veracruz", "Veracruz", "Carnaval", "Comparsas", "research"),
    L("Carnaval Mazatlán extra", "", "", "", "Mazatlán", "Sinaloa", "Carnaval", "Comparsas", "research"),
    L("Carnaval Mérida extra", "", "", "", "Mérida", "Yucatán", "Carnaval", "Temporada", "research"),
    L("Hotelería Cancún extra", "", "", "", "Cancún", "Q. Roo", "Hotel", "Animación", "research"),
    L("Parques temáticos extra", "", "", "", "México", "México", "Entretenimiento", "Personajes", "research"),
    L("Porras / universitarios extra", "", "", "", "México", "México", "Educativo", "Teatro escolar", "research"),
    L("Mascotas deportivas extra", "", "", "", "México", "México", "Deporte", "Botargas equipos", "research"),
    L("Corporativos / team building extra", "", "", "", "CDMX", "CDMX", "B2B", "Eventos empresa", "research"),
    L("XV años temáticos extra", "", "", "", "CDMX", "CDMX", "Eventos", "Fantasía", "research"),
    L("Fiestas infantiles extra", "", "", "", "CDMX", "CDMX", "Infantil", "Cumpleaños", "research"),
    L("Cosplay CDMX extra", "", "", "", "CDMX", "CDMX", "Cosplay", "Convenciones", "research"),
    L("Cosplay GDL extra", "", "", "", "Guadalajara", "Jalisco", "Cosplay", "Convenciones", "research"),
    L("Cosplay MTY extra", "", "", "", "Monterrey", "NL", "Cosplay", "Convenciones", "research"),
    L("ML sellers extra", "https://listado.mercadolibre.com.mx/disfraces", "", "", "México", "México", "Marketplace", "Tiendas oficiales", "research"),
    L("Amazon sellers extra", "https://www.amazon.com.mx/s?k=disfraces", "", "", "México", "México", "Marketplace", "Sellers MX", "research"),
    L("Walmart temporada extra", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Halloween", "brand"),
    L("Coppel temporada extra", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Halloween", "brand"),
    L("Liverpool Halloween extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Departamental", "brand"),
]

CES = [
    L("La Europea canastas / vinos", "https://www.laeuropea.com.mx/", "", "", "CDMX", "CDMX", "Vinoteca + regalos", "Canastas con vino nacional", "research"),
    L("Vinoteca regalos gourmet", "https://www.vinoteca.com/", "", "", "CDMX", "CDMX", "Vinoteca", "Estuches y canastas", "research"),
    L("La Castellana canastas", "https://www.lacastellana.com/", "", "", "CDMX", "CDMX", "Vinoteca", "Regalos con vino", "research"),
    L("La Naval gourmet / vinos", "https://www.lanaval.com.mx/", "", "", "CDMX", "CDMX", "Gourmet", "Importados y canastas", "research"),
    L("El Palacio de Hierro gift baskets", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Canastas departamentales", "brand"),
    L("Liverpool canastas navideñas", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada", "brand"),
    L("Enviaflores regalos", "https://www.enviaflores.com/", "", "", "México", "México", "Ecom regalos", "Flores + gourmet a domicilio", "research"),
    L("Teleflora / Interflora MX", "", "", "", "México", "México", "Red floral + gifts", "Canastas y arreglos", "research"),
    L("Chocolates Turin regalos", "https://www.turin.com.mx/", "", "", "CDMX", "CDMX", "Chocolate + gift", "Estuches corporativos", "research"),
    L("Ki'Xocolatl canastas", "", "", "", "Mérida", "Yucatán", "Chocolate gourmet", "Regalos origen Yucatán", "research"),
    L("Chocolate Mayordomo gift", "https://www.mayordomo.com.mx/", "", "", "Oaxaca", "Oaxaca", "Chocolate + gift", "Canastas oaxaqueñas", "research"),
    L("Cacep chocolate gift", "", "", "", "Tabasco", "Tabasco", "Chocolate origen", "Regalos cacao", "research"),
    L("Wolter chocolate / café gift", "", "", "", "Chiapas", "Chiapas", "Origen Chiapas", "Canastas café-cacao", "research"),
    L("Godiva México gift", "", "", "", "CDMX", "CDMX", "Chocolate premium", "Estuches", "brand"),
    L("Nestlé gift boxes MX", "https://www.nestle.com.mx/", "", "", "México", "México", "Corporativo", "Estuches temporada", "brand"),
    L("PromoOpción regalos corporativos", "", "", "", "México", "México", "Promocionales", "Merch + canastas", "research"),
    L("4Promotional MX", "", "", "", "México", "México", "Promocionales", "Regalos empresa", "research"),
    L("Regalos promocionales CDMX talleres", "", "", "", "CDMX", "CDMX", "Merch", "Branding en canastas", "research"),
    L("Despensas navideñas El Fresno", "https://elfresnoexpress.com/", "", "", "EdoMex", "EdoMex", "Despensas", "Mayoreo fin de año", "research"),
    L("Despensas empresariales GDL", "", "", "", "Guadalajara", "Jalisco", "Despensas", "Prestaciones RH", "research"),
    L("Despensas empresariales MTY", "", "", "", "Monterrey", "NL", "Despensas", "Prestaciones RH", "research"),
    L("Despensas empresariales Puebla", "", "", "", "Puebla", "Puebla", "Despensas", "RH", "research"),
    L("Despensas empresariales Qro", "", "", "", "Querétaro", "Querétaro", "Despensas", "RH Bajío", "research"),
    L("Despensas empresariales León", "", "", "", "León", "Guanajuato", "Despensas", "RH", "research"),
    L("Canastas de queso y vino independientes", "", "", "", "CDMX", "CDMX", "Gourmet", "Queserías + cava", "research"),
    L("Queserías CDMX gift boxes", "", "", "", "CDMX", "CDMX", "Gourmet", "Canastas de queso", "research"),
    L("Cavas CDMX estuches", "", "", "", "CDMX", "CDMX", "Vinos", "Estuche 2-3 botellas", "research"),
    L("Tequileras gift boxes Jalisco", "", "", "", "Guadalajara", "Jalisco", "Destilados", "Estuches tequila", "research"),
    L("Mezcalerías Oaxaca gift", "", "", "", "Oaxaca", "Oaxaca", "Destilados", "Estuches mezcal", "research"),
    L("Canastas de café especialidad", "", "", "", "CDMX", "CDMX", "Café gift", "Grano + accesorios", "research"),
    L("Canastas de miel y artesanal MX", "", "", "", "México", "México", "Artesanal", "Productores", "research"),
    L("Canastas de mole / salsas Oaxaca", "", "", "", "Oaxaca", "Oaxaca", "Gourmet regional", "Despensa gourmet", "research"),
    L("Canastas de chile / salsas Yucatán", "", "", "", "Mérida", "Yucatán", "Gourmet regional", "Recados y salsas", "research"),
    L("Canastas de cajeta Celaya", "", "", "", "Celaya", "Guanajuato", "Gourmet regional", "Dulce + canasta", "research"),
    L("Canastas de rompope / ponche", "", "", "", "México", "México", "Temporada", "Navidad", "research"),
    L("Canastas de galletas artesanales", "", "", "", "CDMX", "CDMX", "Repostería gift", "Corporativo", "research"),
    L("Canastas de café Veracruz", "", "", "", "Xalapa", "Veracruz", "Origen", "Productores", "research"),
    L("Canastas de café Chiapas", "", "", "", "Tuxtla Gutiérrez", "Chiapas", "Origen", "Productores", "research"),
    L("Canastas de café Oaxaca", "", "", "", "Oaxaca", "Oaxaca", "Origen", "Pluma / especialidad", "research"),
    L("Canastas de nuez Chihuahua", "", "", "", "Chihuahua", "Chihuahua", "Origen", "Pecana gift", "research"),
    L("Canastas de datil / dátil norte", "", "", "", "México", "México", "Gourmet", "Frutos secos", "research"),
    L("Spa / wellness gift baskets", "", "", "", "CDMX", "CDMX", "Wellness", "Cosmética + té", "research"),
    L("Canastas de té e infusiones", "", "", "", "CDMX", "CDMX", "Gourmet", "Té + galletas", "research"),
    L("Canastas baby / nacimiento", "", "", "", "CDMX", "CDMX", "Ocasión", "No navidad", "research"),
    L("Canastas de boda / recuerdos", "", "", "", "CDMX", "CDMX", "Ocasión", "Eventos", "research"),
    L("Canastas aniversario empresa", "", "", "", "CDMX", "CDMX", "B2B", "Programa anual", "research"),
    L("Canastas día del padre / madre", "", "", "", "CDMX", "CDMX", "Ocasión", "Calendario comercial", "research"),
    L("Canastas San Valentín gourmet", "", "", "", "CDMX", "CDMX", "Ocasión", "Chocolate + vino", "research"),
    L("Canastas posadas", "", "", "", "CDMX", "CDMX", "Temporada", "Diciembre", "research"),
    L("Canastas Reyes Magos", "", "", "", "CDMX", "CDMX", "Temporada", "Enero", "research"),
    L("Canastas graduación", "", "", "", "CDMX", "CDMX", "Ocasión", "Junio / diciembre", "research"),
    L("Florerías con canastas CDMX", "", "", "", "CDMX", "CDMX", "Florería + gift", "Canal tradicional", "research"),
    L("Florerías con canastas GDL", "", "", "", "Guadalajara", "Jalisco", "Florería + gift", "Occidente", "research"),
    L("Florerías con canastas MTY", "", "", "", "Monterrey", "NL", "Florería + gift", "Norte", "research"),
    L("Florerías con canastas Puebla", "", "", "", "Puebla", "Puebla", "Florería + gift", "Puebla", "research"),
    L("Florerías con canastas Qro", "", "", "", "Querétaro", "Querétaro", "Florería + gift", "Bajío", "research"),
    L("Florerías con canastas León", "", "", "", "León", "Guanajuato", "Florería + gift", "Bajío", "research"),
    L("Florerías con canastas Mérida", "", "", "", "Mérida", "Yucatán", "Florería + gift", "Sureste", "research"),
    L("Florerías con canastas Tijuana", "", "", "", "Tijuana", "BC", "Florería + gift", "Frontera", "research"),
    L("Florerías con canastas Cancún", "", "", "", "Cancún", "Q. Roo", "Florería + gift", "Turismo", "research"),
    L("Hotel amenities gift Cancún", "", "", "", "Cancún", "Q. Roo", "Hotel gift", "VIP / corp", "research"),
    L("Hotel amenities gift Los Cabos", "", "", "", "Los Cabos", "BCS", "Hotel gift", "VIP", "research"),
    L("Hotel amenities gift Puerto Vallarta", "", "", "", "Puerto Vallarta", "Jalisco", "Hotel gift", "VIP", "research"),
    L("Regalos corporativos aeropuertos duty", "", "", "", "México", "México", "Travel retail", "Estuches", "research"),
    L("Sam's Club arcones extra", "https://www.sams.com.mx/", "", "", "México", "México", "Club", "Mayoreo consumidor", "brand"),
    L("Costco gourmet extra", "https://www.costco.com.mx/", "", "", "México", "México", "Club", "Importados", "brand"),
    L("Walmart arcones extra", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Masivo", "brand"),
    L("Chedraui Selecto extra", "https://www.chedraui.com.mx/", "", "", "México", "México", "Súper", "Temporada", "brand"),
    L("La Comer City Market extra", "https://www.lacomer.com.mx/", "", "", "CDMX", "CDMX", "Súper premium", "Gourmet", "brand"),
    L("HEB canastas extra", "https://www.heb.com.mx/", "", "", "Monterrey", "NL", "Súper", "Norte", "brand"),
    L("Soriana canastas extra", "https://www.soriana.com/", "", "", "México", "México", "Súper", "Temporada", "brand"),
    L("Sears arcones extra", "", "", "", "México", "México", "Retail", "Temporada", "brand"),
    L("Sanborns gift extra", "https://www.sanborns.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Estuches", "brand"),
    L("iShop / Mixup gift extra", "", "", "", "CDMX", "CDMX", "Retail", "Tech + gift no food", "brand"),
    L("Office Depot regalos corporativos", "https://www.officedepot.com.mx/", "", "", "México", "México", "B2B office", "Canastas + merch", "brand"),
    L("Uline empaque para arcones", "https://es.uline.mx/", "", "", "México", "México", "Insumos empaque", "Cajas y relleno", "brand"),
    L("Fabricantes de mimbre CDMX extra", "", "", "", "CDMX", "CDMX", "Insumo", "La Merced", "research"),
    L("Fabricantes de arcones madera extra", "", "", "", "México", "México", "Insumo", "Cajas de madera", "research"),
    L("Imprentas tarjetas dedicadas extra", "", "", "", "CDMX", "CDMX", "Insumo", "Branding canasta", "research"),
    L("Moños y listón mayoreo extra", "", "", "", "CDMX", "CDMX", "Insumo packing", "Armado", "research"),
    L("Logística última milla regalos extra", "", "", "", "CDMX", "CDMX", "3PL", "Diciembre pico", "research"),
    L("Paquetería corporativa arcones extra", "", "", "", "México", "México", "3PL", "Nacional", "research"),
    L("Rivenso extra oficina", "https://rivenso.com/", "ventas@rivenso.com", "5515541137", "CDMX", "CDMX", "Ecom", "Cotización volumen", "research"),
    L("Dendi extra logística", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "PyME", "Punta a punta", "research"),
    L("María Orsini extra legado", "https://mariaorsini.com.mx/", "", "", "CDMX", "CDMX", "Premium", "Tradición", "research"),
    L("Arcones Gourmet extra artesanal", "https://arconesgourmet.com/", "", "", "CDMX", "CDMX", "Artesanal", "MX", "research"),
    L("Canastas y Arcones extra fábrica", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "Naucalpan", "EdoMex", "Fábrica", "Alto volumen", "research"),
    L("Canastas.com extra fábrica", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Fábrica", "1000+ SKU", "research"),
    L("Regalos y Canastas extra ejemplo", "https://www.regalosycanastas.mx/", "", "", "CDMX", "CDMX", "Referencia", "Cliente", "ejemplo_cliente"),
    L("Boutique regalos Condesa / Roma", "", "", "", "CDMX", "CDMX", "Boutique", "Gourmet barrio", "research"),
    L("Boutique regalos Polanco extra", "", "", "", "CDMX", "CDMX", "Boutique", "Premium", "research"),
    L("Boutique regalos Santa Fe", "", "", "", "CDMX", "CDMX", "Boutique", "Corporativo", "research"),
    L("Boutique regalos Coyoacán", "", "", "", "CDMX", "CDMX", "Boutique", "Artesanal", "research"),
    L("Boutique regalos San Ángel", "", "", "", "CDMX", "CDMX", "Boutique", "Premium sur", "research"),
    L("Boutique regalos Valle / Del Valle", "", "", "", "CDMX", "CDMX", "Boutique", "Sur-poniente", "research"),
    L("Boutique regalos Satélite extra", "", "", "", "Naucalpan", "EdoMex", "Boutique", "Poniente", "research"),
    L("Boutique regalos Interlomas", "", "", "", "Huixquilucan", "EdoMex", "Boutique", "Premium", "research"),
    L("Boutique regalos San Pedro extra", "", "", "", "San Pedro", "NL", "Boutique", "SPGG", "research"),
    L("Boutique regalos Valle Oriente", "", "", "", "San Pedro", "NL", "Boutique", "Corporativo MTY", "research"),
    L("Boutique regalos Providencia GDL", "", "", "", "Guadalajara", "Jalisco", "Boutique", "Poniente GDL", "research"),
    L("Boutique regalos Andares / Zapopan", "", "", "", "Zapopan", "Jalisco", "Boutique", "Premium GDL", "research"),
    L("Boutique regalos Angelópolis Puebla", "", "", "", "Puebla", "Puebla", "Boutique", "Premium", "research"),
    L("Boutique regalos Antea Qro", "", "", "", "Querétaro", "Querétaro", "Boutique", "Premium Bajío", "research"),
    L("Boutique regalos Altacia León", "", "", "", "León", "Guanajuato", "Boutique", "Premium", "research"),
]


def main():
    merge("05_botanas_snacks.json", BOT)
    merge("06_maquillaje_artistico.json", MAQ)
    merge("07_disfraces.json", DIS)
    merge("08_cestas_de_regalo.json", CES)


if __name__ == "__main__":
    main()
