#!/usr/bin/env python3
"""Generate seeds for lotes 09 blancos and 10 tecnología (200-300 band)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def dump(lote, slug, desc, leads):
    path = ROOT / "config" / "seeds" / f"{lote}_{slug}.json"
    path.write_text(
        json.dumps({"lote": lote, "slug": slug, "description": desc, "leads": leads}, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"  {path.name}: {len(leads)} seeds")


BLANCOS = [
    L("Mint and Lime", "https://mintandlime.mx/", "", "", "México", "México", "Ejemplo original", "Ejemplo del cliente — almohadas y cobijas", "ejemplo_cliente"),
    L("Blancos Mexicanos", "https://www.blancosmexicanos.com/", "blancosmexico@hotmail.com", "5555221017", "CDMX", "CDMX", "Fabricante mayoreo", "+40 años, hotel/hospital — Poniente 122 #473 Vallejo", "research"),
    L("Blancolor", "https://blancolor.com.mx/", "info@blancolor.com.mx", "(33) 3827-1170", "Tlajomulco", "Jalisco", "Fabricante hotelero", "48 años blancos hoteleros, Niños Héroes 603", "research"),
    L("Blancos Casa Linda", "https://blancoscasalinda.com.mx/", "", "(55) 5395-2526", "CDMX", "CDMX", "Mayoreo hotel/Airbnb", "Presa Tepuxtepec 32-201 Lomas de Sotelo", "research"),
    L("La Nueva Perla", "https://lanuevaperla.com/", "", "3336145388", "Guadalajara", "Jalisco", "Fábrica textil", "+80 años cobijas, mantelería, blancos hospital", "research"),
    L("Vianney", "https://vianney.com.mx/", "ventas.institucionales@vianney.mx", "", "México", "México", "Marca nacional", "Edredones, sábanas, almohadas, toallas", "brand"),
    L("Luuna", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "Marca D2C", "Colchones y almohadas, Reforma 296", "research"),
    L("Sognare", "https://www.sognare.com.mx/", "", "", "México", "México", "Marca colchones/blancos", "Almohadas y blancos premium", "research"),
    L("Emma Colchón México", "https://www.emma-colchon.mx/", "", "", "México", "México", "Marca D2C", "Hybrid / Active Cooling", "brand"),
    L("Nezt Colchones", "https://nezt.mx/", "", "", "México", "México", "Marca D2C", "Colchón Original", "research"),
    L("Nooz Colchones", "https://nooz.mx/", "", "", "México", "México", "Marca D2C", "Descanso D2C", "research"),
    L("Blancos Azteca", "https://listado.mercadolibre.com.mx/almohadas_Store_blancos-azteca", "", "", "México", "México", "Marca D2C", "Almohadas muy vendidas MX", "research"),
    L("Dormimundo", "https://www.dormimundo.com.mx/", "", "", "México", "México", "Cadena colchones", "Sucursales nacionales", "brand"),
    L("Colchones Atlas", "https://www.colchonesatlas.com/", "", "", "México", "México", "Marca/fábrica", "Atlas del Descanso", "brand"),
    L("Sealy México", "https://www.sealy.com.mx/", "", "", "México", "México", "Marca colchón", "Posturepedic", "brand"),
    L("Restonic México", "https://www.restonic.com.mx/", "", "", "México", "México", "Marca colchón", "Retail y fábricas", "brand"),
    L("Spring Air México", "", "", "", "México", "México", "Marca colchón", "Canal moderno", "brand"),
    L("Simmons México", "", "", "", "México", "México", "Marca colchón", "Beautyrest", "brand"),
    L("Kaltex Home", "https://www.kaltex.com.mx/", "", "", "San Juan del Río", "Querétaro", "Textilera nacional", "Blancos hotel y retail, estampado", "research"),
    L("Munditelas / Multiblancos", "https://www.munditelas.com/", "", "", "Puebla", "Puebla", "Mayoreo telas/blancos", "+25 años hotel y confección Puebla", "research"),
    L("Colchas Concord", "https://www.concord.com.mx/", "", "", "México", "México", "Marca colchas", "Retail nacional", "brand"),
    L("Íntima Hogar", "https://www.intimahogar.com/", "", "", "México", "México", "Marca hogar", "Sábanas y edredones", "brand"),
    L("IKEA México blancos", "https://www.ikea.com/mx/es/", "", "", "CDMX", "CDMX", "Retail", "Ånneland y textiles", "brand"),
    L("Distribuidora de Blancos Galicia", "", "", "", "Guadalajara", "Jalisco", "Distribuidor hotel", "+15 años jalisciense", "research"),
    L("Gallery House telas GDL", "", "", "", "Guadalajara", "Jalisco", "Telas + blancos", "Hotelería GDL", "research"),
    L("Fábrica sábanas/almohadas Emilio Rabaza", "", "", "", "Guadalajara", "Jalisco", "Fabricante hotel", "Emilio Rabaza 1971 — sábanas, almohadas, cobertores", "research"),
    L("Colchas y Blancos Del Valle", "https://colchasdelvalle.wixsite.com/colchasdelvalle", "", "5574217685", "Nezahualcóyotl", "EdoMex", "Retail regional", "Vianney / Concord, Mexibús L3", "research"),
    L("Dyexsa textiles", "", "", "", "México", "México", "Telas mayoreo", "Blancos y toallas, zona centro", "research"),
    L("Tempur México", "", "", "", "México", "México", "Marca premium", "Memory foam", "brand"),
    L("Therapedic México", "", "", "", "México", "México", "Marca colchón", "Canal retail", "brand"),
    L("Colchones América", "", "", "", "México", "México", "Marca/fábrica", "Tradicional", "brand"),
    L("Colchones Flex", "", "", "", "México", "México", "Marca", "Retail", "brand"),
    L("Colchones Exel", "", "", "", "México", "México", "Marca regional", "Descanso", "research"),
    L("Mink colchones", "", "", "", "México", "México", "Marca D2C", "Memory foam", "research"),
    L("Protectores de colchón mayoreo CDMX", "", "", "", "CDMX", "CDMX", "Mayoreo", "Hotel y hogar", "research"),
    L("Almohadas memory foam mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo", "D2C y hotel", "research"),
    L("Almohadas de pluma / down alternative", "", "", "", "México", "México", "Mayoreo", "Hotel boutique", "research"),
    L("Cobertores polar mayoreo gobierno", "https://www.blancosmexicanos.com/cobertores", "blancosmexico@hotmail.com", "5553583528", "CDMX", "CDMX", "Mayoreo institucional", "Donación y dependencias", "research"),
    L("Toallas hotel mayoreo CDMX", "https://www.blancosmexicanos.com/", "blancosmexico@hotmail.com", "5555227902", "CDMX", "CDMX", "Línea toallas", "Hotel, spa, gym", "research"),
    L("Sábanas hotel mayoreo", "https://blancoscasalinda.com.mx/", "", "5591883332", "CDMX", "CDMX", "Línea sábanas", "Airbnb y boutique", "research"),
    L("Edredones mayoreo GDL", "https://blancolor.com.mx/", "info@blancolor.com.mx", "(33) 3827-1170", "Jalisco", "Jalisco", "Línea edredón", "Hotelería occidente", "research"),
    L("Ropa hospitalaria La Nueva Perla", "https://lanuevaperla.com/", "", "3331519445", "Guadalajara", "Jalisco", "Hospital", "Campos quirúrgicos y sábanas", "research"),
    L("Mantelería eventos La Nueva Perla", "https://lanuevaperla.com/", "", "3336138245", "Guadalajara", "Jalisco", "Eventos", "Manteles y servilletas", "research"),
    L("Bordado y estampado blancos", "https://www.blancosmexicanos.com/", "blancosmexico@hotmail.com", "5555424420", "CDMX", "CDMX", "Personalización", "Logo hotel/hospital", "research"),
    L("Liverpool blancos", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Vianney, Cannon, propios", "brand"),
    L("Palacio de Hierro blancos", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Importados + nacionales", "brand"),
    L("Coppel blancos", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Edredones y almohadas", "brand"),
    L("Sears blancos", "", "", "", "México", "México", "Retail", "Temporada", "brand"),
    L("Suburbia blancos", "https://www.suburbia.com.mx/", "", "", "México", "México", "Retail", "Precio", "brand"),
    L("Walmart blancos", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Great Value / marcas", "brand"),
    L("Sam's Club blancos", "https://www.sams.com.mx/", "", "", "México", "México", "Club", "Mayoreo hogar", "brand"),
    L("Costco blancos / colchones", "https://www.costco.com.mx/", "", "", "México", "México", "Club", "Kirkland textiles", "brand"),
    L("The Home Depot colchones", "https://www.homedepot.com.mx/", "", "", "México", "México", "Retail", "Descanso", "brand"),
    L("Elektra colchones", "https://www.elektra.mx/", "", "", "México", "México", "Retail crédito", "Dormimundo / Atlas", "brand"),
    L("Woolworth blancos", "", "", "", "México", "México", "Retail", "Hogar", "brand"),
    L("Chedraui blancos", "https://www.chedraui.com.mx/", "", "", "México", "México", "Súper", "Temporada", "brand"),
    L("Soriana blancos", "https://www.soriana.com/", "", "", "México", "México", "Súper", "Temporada", "brand"),
    L("HEB blancos norte", "https://www.heb.com.mx/", "", "", "Monterrey", "NL", "Súper", "Hogar norte", "brand"),
    L("La Comer / City Market hogar", "https://www.lacomer.com.mx/", "", "", "CDMX", "CDMX", "Súper premium", "Textiles", "brand"),
    L("Fábricas de Francia hogar", "", "", "", "México", "México", "Retail", "Histórico Liverpool", "brand"),
    L("Cannon México", "", "", "", "México", "México", "Marca toallas/sábanas", "Retail", "brand"),
    L("Santista textiles MX", "", "", "", "México", "México", "Textilera", "Blancos", "research"),
    L("Cluster textiles Puebla", "https://www.munditelas.com/", "", "", "Puebla", "Puebla", "Cluster", "Telas y blancos mayoreo", "research"),
    L("Cluster textiles Guadalajara", "", "", "", "Guadalajara", "Jalisco", "Cluster", "Blancolor, Perla, Galicia", "research"),
    L("Cluster textiles Vallejo CDMX", "https://www.blancosmexicanos.com/", "", "5555221017", "CDMX", "CDMX", "Cluster", "Fábricas oriente/norte", "research"),
    L("Cluster textiles Toluca", "", "", "", "Toluca", "EdoMex", "Cluster", "Confección EdoMex", "research"),
    L("Cluster textiles San Juan del Río", "https://www.kaltex.com.mx/", "", "", "San Juan del Río", "Querétaro", "Cluster Kaltex", "Full package", "research"),
    L("Blancos hotel Cancún proveedores", "", "", "", "Cancún", "Q. Roo", "Canal hotelero", "Riviera Maya", "research"),
    L("Blancos hotel Los Cabos", "", "", "", "Los Cabos", "BCS", "Canal hotelero", "VIP", "research"),
    L("Blancos hotel Puerto Vallarta", "", "", "", "Puerto Vallarta", "Jalisco", "Canal hotelero", "Occidente", "research"),
    L("Blancos hotel CDMX boutique", "", "", "", "CDMX", "CDMX", "Canal hotelero", "Airbnb y boutique", "research"),
    L("Blancos hospital CDMX", "", "", "", "CDMX", "CDMX", "Canal hospital", "Clínicas", "research"),
    L("Blancos spa / gym CDMX", "", "", "", "CDMX", "CDMX", "Canal wellness", "Toallas y batas", "research"),
    L("Batas de baño mayoreo", "https://www.blancosmexicanos.com/", "blancosmexico@hotmail.com", "5555221017", "CDMX", "CDMX", "Línea batas", "Hotel y spa", "research"),
    L("Tapetes de baño mayoreo", "https://blancoscasalinda.com.mx/", "", "(55) 5395-5362", "CDMX", "CDMX", "Línea baño", "Hotel", "research"),
    L("Protectores de colchón hotel", "", "", "", "México", "México", "Insumo hotel", "Impermeables", "research"),
    L("Fundas de almohada mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo", "Hotel y hogar", "research"),
    L("Cojines decorativos mayoreo", "", "", "", "México", "México", "Decoración", "Retail y ecom", "research"),
    L("Cobijas donación institucional", "https://lanuevaperla.com/venta-de-cobijas-en-chiapas/", "", "3331263789", "Guadalajara", "Jalisco", "Institucional", "Fibras regeneradas, envíos MX", "research"),
    L("Dormimundo Arboledas Ags", "", "", "4499126011", "Aguascalientes", "Aguascalientes", "Sucursal", "Convención 1914 Nte 1507", "research"),
    L("Dormimundo Convención Ags", "", "", "4499786300", "Aguascalientes", "Aguascalientes", "Sucursal", "Convención 1914 Sur 809", "research"),
    L("Atlas del Descanso Convención", "", "", "", "Aguascalientes", "Aguascalientes", "Sucursal", "Colchones Atlas", "research"),
    L("Colchones a medida Aguascalientes", "https://colchonesalamedida.mx/", "", "", "Aguascalientes", "Aguascalientes", "Fábrica regional", "A la medida", "research"),
    L("Fábricas colchón Monterrey", "", "", "", "Monterrey", "NL", "Cluster norte", "Descanso NL", "research"),
    L("Fábricas colchón Guadalajara", "", "", "", "Guadalajara", "Jalisco", "Cluster occidente", "Descanso Jal", "research"),
    L("Fábricas colchón Puebla", "", "", "", "Puebla", "Puebla", "Cluster", "Descanso", "research"),
    L("Fábricas colchón León", "", "", "", "León", "Guanajuato", "Cluster Bajío", "Descanso", "research"),
    L("Fábricas colchón Tijuana", "", "", "", "Tijuana", "BC", "Cluster frontera", "Descanso", "research"),
    L("Almohadas cervicales MX", "", "", "", "México", "México", "Línea ortopédica", "D2C y farmacia", "research"),
    L("Almohadas de látex MX", "", "", "", "México", "México", "Línea premium", "Natural / sintético", "research"),
    L("Almohadas cooling gel MX", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "Línea cooling", "Luuna / Emma", "research"),
    L("Edredones nórdicos ecom MX", "", "", "", "México", "México", "Ecom", "Invierno", "research"),
    L("Cobijas sherpa / borrega MX", "", "", "", "México", "México", "Ecom temporada", "Retail", "research"),
    L("Frazadas institucionales", "https://www.blancosmexicanos.com/", "", "5555227902", "CDMX", "CDMX", "Institucional", "Gobierno y albergues", "research"),
    L("Sábanas ajustables mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo", "Hotel", "research"),
    L("Juegos de cama 2 plazas mayoreo", "", "", "", "México", "México", "Mayoreo", "Hogar", "research"),
    L("Blancos infantiles / cunas", "", "", "", "México", "México", "Línea kids", "Retail", "research"),
    L("Blancos mascotas cama", "", "", "", "México", "México", "Adyacente", "Pet beds", "research"),
    L("Colchones individuales estudiantes", "", "", "", "México", "México", "Canal educativo", "Residencias", "research"),
    L("Colchones king / cal king import", "", "", "", "México", "México", "Premium", "Medidas US", "research"),
    L("Bases y box spring MX", "", "", "", "México", "México", "Complemento", "Dormimundo / Atlas", "research"),
    L("Cabeceras y textiles cama", "", "", "", "México", "México", "Complemento", "Hogar", "research"),
    L("Fundas de colchón zipper", "", "", "", "México", "México", "Insumo", "Hotel", "research"),
    L("Cubrecolchón quilted", "", "", "", "México", "México", "Insumo", "Hogar", "research"),
    L("Toallas de alberca hotel", "", "", "", "Cancún", "Q. Roo", "Hotel playa", "Mayoreo", "research"),
    L("Toallas de gym mayoreo", "", "", "", "CDMX", "CDMX", "Gym", "Mayoreo", "research"),
    L("Manteles restaurante mayoreo", "https://lanuevaperla.com/", "", "3336138245", "Guadalajara", "Jalisco", "Horeca", "Eventos y rest", "research"),
    L("Servilletas tela mayoreo", "", "", "", "México", "México", "Horeca", "Restaurante", "research"),
    L("Caminos de mesa / individuales", "https://vianney.com.mx/", "", "", "México", "México", "Decoración mesa", "Retail", "brand"),
    L("Cortinas de baño textiles", "", "", "", "México", "México", "Baño", "Retail — no cortinas hogar a medida", "research"),
    L("Pijamas y batas Vianney", "https://vianney.com.mx/", "ventas.institucionales@vianney.mx", "", "México", "México", "Línea pijama", "Retail", "brand"),
    L("Accesorios de baño textiles", "https://vianney.com.mx/", "", "", "México", "México", "Baño", "Retail", "brand"),
    L("Outlet blancos CDMX", "", "", "", "CDMX", "CDMX", "Outlet", "Segunda / liquidación", "research"),
    L("Outlet blancos GDL", "", "", "", "Guadalajara", "Jalisco", "Outlet", "Fábrica", "research"),
    L("Outlet blancos Puebla", "", "", "", "Puebla", "Puebla", "Outlet", "Textil", "research"),
    L("Mayoreo Mercado de la Merced textiles", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Cobijas y sábanas", "research"),
    L("Mayoreo Tepito cobijas", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Temporada frío", "research"),
    L("Mayoreo La Lagunilla textiles", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Hogar", "research"),
    L("Tiendas de blancos centro GDL", "", "", "", "Guadalajara", "Jalisco", "Retail centro", "Mayoreo/menudeo", "research"),
    L("Tiendas de blancos centro MTY", "", "", "", "Monterrey", "NL", "Retail centro", "Mayoreo/menudeo", "research"),
    L("Tiendas de blancos centro Puebla", "", "", "", "Puebla", "Puebla", "Retail centro", "Mayoreo", "research"),
    L("Tiendas de blancos León", "", "", "", "León", "Guanajuato", "Retail", "Bajío", "research"),
    L("Tiendas de blancos Querétaro", "", "", "", "Querétaro", "Querétaro", "Retail", "Bajío", "research"),
    L("Tiendas de blancos Mérida", "", "", "", "Mérida", "Yucatán", "Retail", "Sureste", "research"),
    L("Tiendas de blancos Tijuana", "", "", "", "Tijuana", "BC", "Retail", "Frontera", "research"),
    L("Tiendas de blancos Chihuahua", "", "", "", "Chihuahua", "Chihuahua", "Retail", "Norte — temporada frío", "research"),
    L("Tiendas de blancos Toluca", "", "", "", "Toluca", "EdoMex", "Retail", "Frío EdoMex", "research"),
    L("Tiendas de blancos Pachuca", "", "", "", "Pachuca", "Hidalgo", "Retail", "Frío", "research"),
    L("Tiendas de blancos Xalapa", "", "", "", "Xalapa", "Veracruz", "Retail", "Clima templado", "research"),
    L("Ecom almohadas Shopify MX", "", "", "", "México", "México", "Ecom D2C", "Marcas chicas", "research"),
    L("Ecom cobijas ML official stores", "https://listado.mercadolibre.com.mx/cobijas", "", "", "México", "México", "Marketplace", "Tiendas oficiales", "research"),
    L("Amazon MX blancos sellers", "https://www.amazon.com.mx/s?k=almohadas", "", "", "México", "México", "Marketplace", "Sellers MX", "research"),
    L("Airbnb starter kits blancos", "https://blancoscasalinda.com.mx/", "", "5524418163", "CDMX", "CDMX", "Canal Airbnb", "Paquetes host", "research"),
    L("Gobierno / protección civil cobijas", "https://www.blancosmexicanos.com/", "", "5555221017", "CDMX", "CDMX", "Licitación", "Emergencias", "research"),
    L("Lavanderías industriales blancos", "", "", "", "México", "México", "Servicio + compra", "Hotel", "research"),
    L("Renta de blancos eventos", "", "", "", "CDMX", "CDMX", "Renta", "Banquetes", "research"),
    L("Blancos para moteles mayoreo", "https://www.blancosmexicanos.com/", "", "5555227902", "CDMX", "CDMX", "Canal motel", "Alta rotación", "research"),
    L("Sábanas quirúrgicas / campos", "https://lanuevaperla.com/", "", "3331519445", "Guadalajara", "Jalisco", "Médico", "Hospital", "research"),
    L("Uniformes cocina + blancos", "", "", "", "Guadalajara", "Jalisco", "Horeca mixto", "Fábrica GDL", "research"),
    L("Telas crudas / mantas teñidas", "https://lanuevaperla.com/", "", "3336138245", "Guadalajara", "Jalisco", "Insumo textil", "Confección", "research"),
    L("Estampado rotativo Kaltex", "https://www.kaltex.com.mx/", "", "", "Querétaro", "Querétaro", "Proceso", "Hasta 20 colores", "research"),
    L("Full package confección Qro", "https://www.kaltex.com.mx/", "", "", "San Juan del Río", "Querétaro", "Maquila", "Lavado láser + costura", "research"),
    L("Vianney institucional empresas", "https://vianney.com.mx/", "ventas.institucionales@vianney.mx", "", "México", "México", "B2B", "Ventas empresas", "brand"),
    L("Luuna almohadas línea", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "Línea almohada", "Cooling", "research"),
    L("Sognare almohadas Sense", "https://www.sognare.com.mx/", "", "", "México", "México", "Línea almohada", "Sense", "research"),
    L("Emma almohadas", "https://www.emma-colchon.mx/", "", "", "México", "México", "Línea almohada", "D2C", "brand"),
    L("Mint and Lime cobijas", "https://mintandlime.mx/", "", "", "México", "México", "Línea cobija", "Ejemplo + catálogo", "research"),
    L("Sealy Posturepedic retail", "https://www.sealy.com.mx/", "", "", "México", "México", "Retail marca", "Cadena", "brand"),
    L("Restonic sucursales", "https://www.restonic.com.mx/", "", "", "México", "México", "Retail marca", "Cadena", "brand"),
    L("Spring Air sucursales", "", "", "", "México", "México", "Retail marca", "Cadena", "brand"),
    L("Simmons Beautyrest MX", "", "", "", "México", "México", "Retail marca", "Premium", "brand"),
    L("Colchones Concord / hogar", "https://www.concord.com.mx/", "", "", "México", "México", "Marca hogar", "Colchas", "brand"),
    L("Íntima sábanas egipcias", "https://www.intimahogar.com/", "", "", "México", "México", "Premium hogar", "Algodón", "brand"),
    L("IKEA textiles cama extra", "https://www.ikea.com/mx/es/", "", "", "CDMX", "CDMX", "Retail", "Fundas y edredones", "brand"),
    L("Costco colchones extra", "https://www.costco.com.mx/", "", "", "México", "México", "Club", "Sealy / propios", "brand"),
    L("Sam's colchones extra", "https://www.sams.com.mx/", "", "", "México", "México", "Club", "Member's Mark", "brand"),
    L("Walmart colchones extra", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Precio", "brand"),
    L("Coppel colchones extra", "https://www.coppel.com/", "", "", "México", "México", "Crédito", "Volumen", "brand"),
    L("Elektra descanso extra", "https://www.elektra.mx/", "", "", "México", "México", "Crédito", "Volumen", "brand"),
    L("Liverpool colchones extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Departamental", "Premium mid", "brand"),
    L("Palacio colchones extra", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Departamental", "Premium", "brand"),
    L("Home Depot descanso extra", "https://www.homedepot.com.mx/", "", "", "México", "México", "Home improvement", "Colchón", "brand"),
    L("Blancos Casa Linda WhatsApp", "https://blancoscasalinda.com.mx/", "", "5591883332", "CDMX", "CDMX", "Canal WA", "Mayoreo", "research"),
    L("Blancos Mexicanos WhatsApp", "https://www.blancosmexicanos.com/", "blancosmexico@hotmail.com", "5513583528", "CDMX", "CDMX", "Canal WA", "Cotización mismo día", "research"),
    L("La Nueva Perla WhatsApp", "https://lanuevaperla.com/", "", "3338015019", "Guadalajara", "Jalisco", "Canal WA", "Mayoreo", "research"),
    L("Blancolor fábrica Tlajomulco extra", "https://blancolor.com.mx/", "info@blancolor.com.mx", "(33) 3827-1170", "Tlajomulco", "Jalisco", "Fábrica", "6 líneas tel", "research"),
    L("Entrega inmediata blancos CDMX", "https://www.blancosmexicanos.com/", "", "5555221017", "CDMX", "CDMX", "Operación", "Pedido urgente", "research"),
    L("Envíos nacionales blancos", "https://blancoscasalinda.com.mx/", "", "(55) 6395-2276", "CDMX", "CDMX", "Logística", "Toda la República", "research"),
    L("Fabricamos a la medida blancos", "https://www.blancosmexicanos.com/", "", "5555227902", "CDMX", "CDMX", "Custom", "Hotel specs", "research"),
    L("Mejoramos precio blancos", "https://www.blancosmexicanos.com/", "", "5555221017", "CDMX", "CDMX", "Mayoreo precio", "Cotiza", "research"),
    L("Hotelería 48 años Blancolor extra", "https://blancolor.com.mx/", "info@blancolor.com.mx", "(33) 3827-1170", "Jalisco", "Jalisco", "Especialista hotel", "Alta durabilidad", "research"),
    L("Airbnb paquetes Casa Linda extra", "https://blancoscasalinda.com.mx/", "", "(55) 5395-2526", "CDMX", "CDMX", "Paquete host", "Sobre pedido", "research"),
    L("Gobierno y empresas Casa Linda", "https://blancoscasalinda.com.mx/", "", "(55) 5395-5362", "CDMX", "CDMX", "B2G/B2B", "Institucional", "research"),
    L("90 años Perla extra", "https://lanuevaperla.com/", "", "3336145388", "Guadalajara", "Jalisco", "Tradición", "Textil GDL", "research"),
    L("Fibras regeneradas cobijas", "https://lanuevaperla.com/", "", "3331263789", "Guadalajara", "Jalisco", "Sustentable", "Algodón/poliéster/lana", "research"),
    L("Tienda física Perla GDL", "https://lanuevaperla.com/", "", "3336145388", "Guadalajara", "Jalisco", "Showroom", "Mayoreo presencial", "research"),
    L("Catálogo colchas Casa Linda", "https://blancoscasalinda.com.mx/", "", "5524418163", "CDMX", "CDMX", "Catálogo", "Colchas", "research"),
    L("Lomas de Sotelo showroom", "https://blancoscasalinda.com.mx/", "", "(55) 5395-2526", "Miguel Hidalgo", "CDMX", "Showroom", "Sotelo", "research"),
    L("Vallejo fábrica Blancos MX extra", "https://www.blancosmexicanos.com/", "blancosmexico@hotmail.com", "5555221017", "CDMX", "CDMX", "Planta", "CP 02300", "research"),
    L("Santa Anita planta Blancolor extra", "https://blancolor.com.mx/", "info@blancolor.com.mx", "(33) 3827-1170", "Tlajomulco", "Jalisco", "Planta", "Col. Santa Anita", "research"),
    L("Puebla mayoreo Munditelas extra", "https://www.munditelas.com/", "", "", "Puebla", "Puebla", "Mayoreo", "Hoteles y talleres", "research"),
    L("Multiblancos Puebla extra", "https://www.munditelas.com/", "", "", "Puebla", "Puebla", "Mayoreo blancos", "Disponibilidad inmediata", "research"),
    L("Confeccionistas deportivos Dyexsa", "", "", "", "México", "México", "Telas", "Pijamas y toallas", "research"),
    L("Kaltex Home hotel chains", "https://www.kaltex.com.mx/", "", "", "Querétaro", "Querétaro", "B2B hotel", "Cadenas grandes", "research"),
    L("Ancho 3 metros estampado", "https://www.kaltex.com.mx/", "", "", "Querétaro", "Querétaro", "Capacidad", "Rotativo 20 colores", "research"),
    L("Nezt Original extra", "https://nezt.mx/", "", "", "México", "México", "D2C", "Ranking colchones", "research"),
    L("Nooz Original extra", "https://nooz.mx/", "", "", "México", "México", "D2C", "Ranking", "research"),
    L("Emma Hybrid Active Cooling extra", "https://www.emma-colchon.mx/", "", "", "México", "México", "D2C", "Cooling", "brand"),
    L("Luuna Original Cooling extra", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "D2C", "Mejor calificado MX", "research"),
    L("Sognare Sense extra", "https://www.sognare.com.mx/", "", "", "México", "México", "Marca", "Sense", "research"),
    L("Sealy Posturepedic extra", "https://www.sealy.com.mx/", "", "", "México", "México", "Marca", "Clásico", "brand"),
    L("IKEA Ånneland extra", "https://www.ikea.com/mx/es/", "", "", "CDMX", "CDMX", "Retail", "Precio", "brand"),
    L("Reforma 296 Luuna HQ", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "HQ", "Piso 31 Juárez", "research"),
    L("Ventas Luuna 8am-11pm", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "Canal ventas", "Todos los días", "research"),
    L("Sofás y puffs Luuna adyacente", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "Adyacente hogar", "Mismo D2C", "research"),
    L("Camas y bases Luuna", "https://luuna.mx/", "hola@luuna.mx", "", "CDMX", "CDMX", "Complemento", "Sistema descanso", "research"),
    L("Colchas Del Valle Neza extra", "", "", "5574217685", "Nezahualcóyotl", "EdoMex", "Retail oriente", "Entrega Mexibús", "research"),
    L("Blancos Azteca ML extra", "https://listado.mercadolibre.com.mx/almohadas_Store_blancos-azteca", "", "", "México", "México", "Ecom ML", "Volumen", "research"),
    L("Mint and Lime ecom extra", "https://mintandlime.mx/", "", "", "México", "México", "Ecom", "Ejemplo", "research"),
]

TECH = [
    L("Doto", "https://doto.com.mx/", "", "", "México", "México", "Ejemplo original", "Ejemplo del cliente — cargadores y porta laptop", "ejemplo_cliente"),
    L("ELE-GATE", "https://www.ele-gate.com/", "", "", "México", "México", "Mayoreo B2B", "ELEGATE SA DE CV desde 2012, dropshipping 32 estados", "research"),
    L("Unicell México", "https://unicell.com.mx/", "", "5563681724", "CDMX", "CDMX", "Mayoreo fundas", "+15 años, Eje Central 76 Local 3", "research"),
    L("Fundas Mayoreo MX", "https://www.fundasmayoreo.com.mx/", "", "2411104310", "Apizaco", "Tlaxcala", "Mayoreo fundas", "Josefa Ortiz 500 2do piso Centro", "research"),
    L("Coolook", "https://coolook.mx/", "", "", "México", "México", "Mayoreo accesorios", "Mínimo $2,000 — Litio, Novoline, Tauro, Kingston", "research"),
    L("MOCA Distribuidora", "https://mocadistribuidora.com/", "mocadistribuidora21@gmail.com", "813882554", "Monterrey", "NL", "Mayoreo accesorios", "Av. Juárez 745 Centro, +7 años, 5000+ SKU", "research"),
    L("MOCA sucursal GDL Piso 3", "", "mocadistribuidora21@gmail.com", "8112558769", "Guadalajara", "Jalisco", "Sucursal mayoreo", "16 de Septiembre 151 — 3328462843 Alondra", "research"),
    L("PCH Connect / Shop PCH", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "CDMX", "CDMX", "Mayoreo tech", "Iztaccíhuatl 322 — suc. CDMX/GDL/Mérida/Puebla", "research"),
    L("PCH Mayoreo", "https://www.pchmayoreo.com/", "", "", "México", "México", "Mayoreo", "Distribución tecnología", "research"),
    L("DataComponents", "https://datacomponents.com.mx/", "info@datacomponents.com.mx", "5558948888", "México", "México", "Mayoreo", "IMAGES AND ENTERTAINMENT / B-Robotix", "research"),
    L("MCA Chiapas", "https://www.mcachis.com.mx/", "clientes@mcachis.com.mx", "9616132242", "Tuxtla Gutiérrez", "Chiapas", "Mayoreo cómputo", "Belisario Domínguez 2007 Penipak desde 1997", "research"),
    L("Cyberpuerta", "https://www.cyberpuerta.mx/", "", "", "México", "México", "Ecom componentes", "PC y accesorios", "research"),
    L("DDTech", "https://www.ddtech.mx/", "ventas@ddtech.mx", "(33) 1523-2823", "Guadalajara", "Jalisco", "Ecom + tienda", "Componentes ASUS partner", "research"),
    L("Digitalife", "https://www.digitalife.com.mx/", "ventas.internet@digitalife.com.mx", "3336300660", "Guadalajara", "Jalisco", "Ecom + tienda", "API Global / ASUS", "research"),
    L("PCEL / PC en Línea", "https://pcel.com/", "", "", "Monterrey", "NL", "Ecom + tienda", "Componentes, tienda física MTY", "research"),
    L("Zegucom", "https://www.zegucom.com.mx/", "", "", "Guadalajara", "Jalisco", "Ecom GDL", "Componentes", "research"),
    L("Dimercom", "", "", "", "Puebla", "Puebla", "Tienda regional", "Componentes Puebla", "research"),
    L("MiPC Comunicaciones", "https://www.mipc.com.mx/", "ricardo.reynoso@mipc.com.mx", "(33) 4770-3209", "Guadalajara", "Jalisco", "Distribuidor", "ASUS Pacífico", "research"),
    L("Ventronic", "https://www.ventronic.mx/", "online@ventronic.com.mx", "3329620635", "Guadalajara", "Jalisco", "Ecom", "Componentes", "research"),
    L("Grupo DECME", "https://www.grupodecme.com/", "", "", "México", "México", "Ecom / ML", "Componentes", "research"),
    L("Intercompras", "https://www.intercompras.com/", "", "", "México", "México", "Ecom", "Tech", "research"),
    L("Gloma Store / Loma del Norte", "https://www.glomastore.mx/", "", "", "México", "México", "Ecom", "ASUS Golfo", "research"),
    L("Lumen", "https://www.lumen.com.mx/", "", "", "México", "México", "Cadena papelería/tech", "Sucursales", "brand"),
    L("Compumex", "https://www.compumex.mx/", "", "", "México", "México", "Cadena", "Cómputo", "research"),
    L("Ofix", "https://www.ofix.com.mx/", "", "", "México", "México", "Oficina + tech", "Sucursales", "research"),
    L("Chapur", "https://www.chapur.com.mx/", "", "", "Mérida", "Yucatán", "Departamental sureste", "Tech + hogar", "brand"),
    L("Steren", "https://www.steren.com.mx/", "", "", "CDMX", "CDMX", "Cadena electrónica", "Cables, cargadores, accesorios", "brand"),
    L("Valta mayoreo celulares", "https://www.valta.com.mx/", "", "", "CDMX", "CDMX", "Mayoreo equipos", "Envío gratis >$20k", "research"),
    L("Comunitel", "https://celularesmayoreocomunitel.com/", "", "", "Guadalajara", "Jalisco", "Mayoreo celulares", "Samsung, Moto, Xiaomi, Huawei, Apple", "research"),
    L("Gama Plus", "https://gamaplus.com.mx/", "", "", "Guadalajara", "Jalisco", "Mayoreo equipos+acc", "Mínimo accesorios $1,500", "research"),
    L("Celulandia", "https://celulandia.com.mx/mayoreo/", "", "", "México", "México", "Mayoreo / open box", "+6 equipos precio mayoreo", "research"),
    L("Celular Express / Celex", "https://www.celex.com/", "", "", "México", "México", "Mayoreo + Telcel", "+25 mil productos, fundas y accesorios", "research"),
    L("Fixoem", "", "", "", "Monterrey", "NL", "Refacciones", "Suc. MTY, Puebla, Tijuana", "research"),
    L("Todo para Smartphones", "", "", "", "Monterrey", "NL", "Mayoreo accesorios", "Inventario online", "research"),
    L("Dimovil", "", "", "", "México", "México", "Mayoreo accesorios", "Proveedor listado Tiendanube", "research"),
    L("Productos x mayoreo accesorios", "", "", "", "México", "México", "Mayoreo", "Accesorios celular", "research"),
    L("InstaCase", "https://instacase.mx/", "", "", "CDMX", "CDMX", "D2C fundas", "+200 modelos, CDMX/Puebla/Cuernavaca", "research"),
    L("La Casa de las Carcasas", "https://lacasadelascarcasas.com.mx/", "", "", "México", "México", "Retail fundas", "Personalización, envíos MX", "research"),
    L("Happy Case", "https://happycase.com.mx/", "", "", "México", "México", "D2C", "Fundas personalizadas", "research"),
    L("TARLA", "https://tarla.com.mx/", "", "", "México", "México", "D2C", "Fundas piel + joyería", "research"),
    L("FunCases", "https://funcases.mx/", "", "", "México", "México", "D2C", "Fundas personalizadas — ejemplo adyacente", "research"),
    L("iShop Mixup", "https://www.ishopmixup.com/", "", "", "CDMX", "CDMX", "Retail Apple/acc", "Cadena nacional", "brand"),
    L("MacStore", "", "", "", "CDMX", "CDMX", "Retail Apple", "Autorizado", "brand"),
    L("Office Depot tech", "https://www.officedepot.com.mx/", "", "", "México", "México", "Retail oficina", "Cables, mochilas, cargadores", "brand"),
    L("OfficeMax MX", "", "", "", "México", "México", "Retail oficina", "Accesorios", "brand"),
    L("Sanborns electrónica", "https://www.sanborns.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Cables y accesorios", "brand"),
    L("Liverpool tech", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Departamental", "Accesorios", "brand"),
    L("Palacio tech", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Departamental", "Premium acc", "brand"),
    L("Coppel celulares/acc", "https://www.coppel.com/", "", "", "México", "México", "Retail crédito", "Volumen", "brand"),
    L("Elektra celulares", "https://www.elektra.mx/", "", "", "México", "México", "Retail crédito", "Volumen", "brand"),
    L("Walmart accesorios", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Onn / marcas", "brand"),
    L("Amazon MX accesorios sellers", "https://www.amazon.com.mx/", "", "", "México", "México", "Marketplace", "Sellers MX", "research"),
    L("Mercado Libre accesorios", "https://listado.mercadolibre.com.mx/cargadores-celular", "", "", "México", "México", "Marketplace", "Official stores", "research"),
    L("Ingram Micro México", "", "", "", "México", "México", "Distribuidor mayorista", "Enterprise/channel", "brand"),
    L("Intcomex México", "", "", "", "México", "México", "Distribuidor mayorista", "Channel", "brand"),
    L("CVA México", "https://www.cva.com.mx/", "", "", "México", "México", "Distribuidor mayorista", "Cómputo", "research"),
    L("CT Internacional", "", "", "", "México", "México", "Distribuidor", "Channel", "research"),
    L("Exel del Norte", "", "", "", "Monterrey", "NL", "Distribuidor norte", "Cómputo", "research"),
    L("Compusoluciones", "https://www.compusoluciones.com/", "", "", "Guadalajara", "Jalisco", "Integrador", "B2B", "research"),
    L("Grupo Dice", "", "", "", "México", "México", "Distribuidor", "Channel", "research"),
    L("High Pro", "", "", "", "México", "México", "Ecom gamer", "Componentes", "research"),
    L("PCMR México", "", "", "", "México", "México", "Ecom gamer", "Componentes", "research"),
    L("Human Computer", "", "", "", "México", "México", "Ecom", "Componentes", "research"),
    L("PCX", "", "", "", "México", "México", "Ecom", "Componentes", "research"),
    L("PC México", "", "", "", "México", "México", "Ecom", "Componentes", "research"),
    L("Ignite Mérida", "", "", "", "Mérida", "Yucatán", "Tienda regional", "Componentes sureste", "research"),
    L("Plaza de la Tecnología CDMX", "", "", "", "CDMX", "CDMX", "Cluster mayoreo", "Centro — accesorios celular", "research"),
    L("Plaza de la Computación CDMX", "", "", "", "CDMX", "CDMX", "Cluster", "Cómputo centro", "research"),
    L("Siglo XXI cómputo", "", "", "", "CDMX", "CDMX", "Cluster", "Vendedores reunidos", "research"),
    L("Centro celular Tepito", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Fundas y cables", "research"),
    L("Mayoreo celular Eje Central", "https://unicell.com.mx/", "", "5563681724", "CDMX", "CDMX", "Cluster", "Unicell y vecinos", "research"),
    L("Mayoreo celular GDL centro", "", "", "3328462843", "Guadalajara", "Jalisco", "Cluster", "16 de Septiembre / Juárez", "research"),
    L("Mayoreo celular MTY centro", "https://mocadistribuidora.com/", "", "813882554", "Monterrey", "NL", "Cluster", "Juárez 745", "research"),
    L("Mayoreo celular Puebla", "", "", "", "Puebla", "Puebla", "Cluster", "Centro / Fixoem", "research"),
    L("Mayoreo celular Tijuana", "", "", "", "Tijuana", "BC", "Cluster frontera", "Fixoem + locales", "research"),
    L("Belkin México", "", "", "", "México", "México", "Marca accesorios", "Cargadores y hubs", "brand"),
    L("Anker México", "", "", "", "México", "México", "Marca accesorios", "Power banks / GaN", "brand"),
    L("Baseus México", "", "", "", "México", "México", "Marca accesorios", "Cables y cargadores", "brand"),
    L("Ugreen México", "", "", "", "México", "México", "Marca accesorios", "Hubs y cables", "brand"),
    L("Spigen México", "", "", "", "México", "México", "Marca fundas", "Retail / ecom", "brand"),
    L("OtterBox México", "", "", "", "México", "México", "Marca fundas", "Rugged", "brand"),
    L("Ringke / ESR México", "", "", "", "México", "México", "Marca fundas", "Ecom", "brand"),
    L("Logitech México", "", "", "", "México", "México", "Marca períferos", "Mice / teclados", "brand"),
    L("Targus México", "", "", "", "México", "México", "Marca porta laptop", "Maletines", "brand"),
    L("Case Logic México", "", "", "", "México", "México", "Marca maletines", "Porta laptop", "brand"),
    L("Samsonite tech / porta laptop", "https://samsonite.com.mx/", "", "", "México", "México", "Marca maletas", "Línea business", "brand"),
    L("Swissgear MX", "", "", "", "México", "México", "Marca mochilas", "Laptop bags", "brand"),
    L("Xiaomi / Mi Store MX", "", "", "", "México", "México", "Marca + accesorios", "Cargadores y fundas", "brand"),
    L("Samsung Experience Store acc", "https://www.samsung.com/mx/", "", "", "México", "México", "Marca", "Distribuidores", "brand"),
    L("Apple accesorios autorizados", "", "", "", "México", "México", "Marca", "iShop / MacStore", "brand"),
    L("Huawei / Honor accesorios MX", "", "", "", "México", "México", "Marca", "Retail", "brand"),
    L("Motorola accesorios MX", "", "", "", "México", "México", "Marca", "Retail", "brand"),
    L("Kingston / Adata / Sandisk canal", "https://coolook.mx/", "", "", "México", "México", "Storage", "Vía Coolook y mayoristas", "research"),
    L("Litio / Novoline / Tauro", "https://coolook.mx/", "", "", "México", "México", "Marcas accesorios", "Asociados Coolook", "research"),
    L("Koblenz / APC / Tripp Lite energía", "https://www.mcachis.com.mx/", "clientes@mcachis.com.mx", "9616132242", "Tuxtla Gutiérrez", "Chiapas", "Energía", "Reguladores y UPS", "research"),
    L("Sola Basic México", "", "", "", "México", "México", "Energía", "Reguladores", "brand"),
    L("Gameplanet", "https://gameplanet.com/", "", "", "CDMX", "CDMX", "Retail gamer", "Accesorios", "brand"),
    L("High Pro / gamer acc extra", "", "", "", "México", "México", "Gamer", "Periféricos", "research"),
    L("Razer / HyperX / Corsair canal MX", "", "", "", "México", "México", "Gamer marcas", "Retail ecom", "brand"),
    L("Cargadores GaN mayoreo", "", "", "", "CDMX", "CDMX", "Línea producto", "Unicell / ELE-GATE", "research"),
    L("Power banks mayoreo", "", "", "", "CDMX", "CDMX", "Línea producto", "Mayoreo celular", "research"),
    L("Cables USB-C mayoreo", "", "", "", "CDMX", "CDMX", "Línea producto", "Plaza Tecnología", "research"),
    L("Micas / screen protectors mayoreo", "https://unicell.com.mx/", "", "5563681724", "CDMX", "CDMX", "Línea producto", "Unicell", "research"),
    L("Soportes / car mounts mayoreo", "https://www.fundasmayoreo.com.mx/", "", "2411104310", "Apizaco", "Tlaxcala", "Línea producto", "Fundas Mayoreo", "research"),
    L("Audífonos TWS mayoreo", "https://coolook.mx/", "", "", "México", "México", "Línea producto", "Coolook / ELE-GATE", "research"),
    L("Mochilas porta laptop mayoreo", "", "", "", "México", "México", "Línea producto", "Targus / Case Logic / Doto", "research"),
    L("Hubs USB-C / docks mayoreo", "", "", "", "México", "México", "Línea producto", "Ugreen / Belkin", "research"),
    L("Cargadores auto mayoreo", "", "", "", "CDMX", "CDMX", "Línea producto", "Accesorios auto+cel", "research"),
    L("MagSafe / magnéticos mayoreo", "", "", "", "CDMX", "CDMX", "Línea producto", "Fundas y pads", "research"),
    L("Fundas AirPods mayoreo", "https://www.fundasmayoreo.com.mx/", "", "2411104310", "Apizaco", "Tlaxcala", "Línea producto", "Catálogo Fundas Mayoreo", "research"),
    L("Refacciones display / batería", "https://mocadistribuidora.com/", "", "813882554", "Monterrey", "NL", "Refacciones", "MOCA / Fixoem", "research"),
    L("Dropshipping ELE-GATE extra", "https://www.ele-gate.com/acerca-de-ele-gate/", "", "", "México", "México", "Modelo dropship", "Shopify / Tiendanube / TikTok Shop", "research"),
    L("Misceláneas canal ELE-GATE", "https://www.ele-gate.com/", "", "", "México", "México", "Canal retail chico", "Papelerías y accesorios", "research"),
    L("Vendedores ML/Amazon vía ELE-GATE", "https://www.ele-gate.com/", "", "", "México", "México", "Canal marketplace", "Abasto 32 estados", "research"),
    L("PCH sucursal CDMX extra", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "CDMX", "CDMX", "Sucursal", "Iztaccíhuatl 322", "research"),
    L("PCH sucursal Guadalajara", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "Guadalajara", "Jalisco", "Sucursal", "Occidente", "research"),
    L("PCH sucursal Mérida", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "Mérida", "Yucatán", "Sucursal", "Sureste", "research"),
    L("PCH sucursal Puebla", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "Puebla", "Puebla", "Sucursal", "Centro", "research"),
    L("OCURRE PCH recolecta", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "México", "México", "Logística", "Recoge en sucursal", "research"),
    L("DDTech sucursal GDL extra", "https://www.ddtech.mx/", "ventas@ddtech.mx", "(33) 1523-1303", "Guadalajara", "Jalisco", "Tienda", "Segundo tel", "research"),
    L("Digitalife sucursal GDL extra", "https://www.digitalife.com.mx/", "ventas.internet@digitalife.com.mx", "3336300660", "Guadalajara", "Jalisco", "Tienda", "Ext 1020", "research"),
    L("PCEL tienda Monterrey extra", "https://pcel.com/", "", "", "Monterrey", "NL", "Tienda física", "Norte", "research"),
    L("Comunitel sucursal matriz GDL", "https://celularesmayoreocomunitel.com/", "", "", "Guadalajara", "Jalisco", "Matriz", "Centro GDL + 2 suc", "research"),
    L("Telcel distribuidores accesorios", "https://www.telcel.com/", "", "", "México", "México", "Canal Telcel", "Equipos + acc", "brand"),
    L("Samsung Business distribuidores", "https://www.samsung.com/mx/business/contact-us/", "", "", "México", "México", "Canal Samsung", "Precio fábrica", "brand"),
    L("Xiaomi authorized acc MX", "", "", "", "México", "México", "Canal Xiaomi", "Fundas y cargadores", "brand"),
    L("Steren sucursales extra", "https://www.steren.com.mx/", "", "", "CDMX", "CDMX", "Cadena", "Cables nacionales", "brand"),
    L("RadioShack MX residual / sucursales", "", "", "", "México", "México", "Retail legado", "Accesorios", "brand"),
    L("Best Buy MX legado online", "", "", "", "México", "México", "Ecom legado", "Cerrado físico", "brand"),
    L("Mixup música + acc", "https://www.ishopmixup.com/", "", "", "CDMX", "CDMX", "Retail", "iShop grupo", "brand"),
    L("Gameplanet acc extra", "https://gameplanet.com/", "", "", "CDMX", "CDMX", "Gamer retail", "Periféricos", "brand"),
    L("Office Depot cables extra", "https://www.officedepot.com.mx/", "", "", "México", "México", "Oficina", "Cargadores laptop", "brand"),
    L("Coppel fundas extra", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Accesorios baratos", "brand"),
    L("Walmart Onn acc extra", "https://www.walmart.com.mx/", "", "", "México", "México", "Private label", "Cables / audífonos", "brand"),
    L("Costco Anker / Belkin extra", "https://www.costco.com.mx/", "", "", "México", "México", "Club", "Marcas acc", "brand"),
    L("Sam's accesorios extra", "https://www.sams.com.mx/", "", "", "México", "México", "Club", "Mayoreo cons", "brand"),
    L("HEB tech norte extra", "https://www.heb.com.mx/", "", "", "Monterrey", "NL", "Súper", "Accesorios", "brand"),
    L("Liverpool Apple Shop extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Shop-in-shop", "Accesorios Apple", "brand"),
    L("Palacio tech premium extra", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Premium", "Marcas", "brand"),
    L("Sanborns cables extra", "https://www.sanborns.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Último momento", "brand"),
    L("Mayoreo fundas Tlaxcala extra", "https://www.fundasmayoreo.com.mx/", "", "2411104310", "Apizaco", "Tlaxcala", "Fábrica/dist", "Desde 1 pza", "research"),
    L("Mayoreo fundas CDMX Unicell extra", "https://unicell.com.mx/", "", "5563681724", "CDMX", "CDMX", "Red nacional", "Calidad/precio 15 años", "research"),
    L("Mayoreo MTY MOCA extra", "https://mocadistribuidora.com/", "", "813882554", "Monterrey", "NL", "Red sucursales", "10k comunidad", "research"),
    L("Mayoreo GDL MOCA extra", "", "", "3328462843", "Guadalajara", "Jalisco", "Sucursal", "Piso 3", "research"),
    L("Coolook China-LATAM extra", "https://coolook.mx/", "", "", "México", "México", "Importador", "CN, CR, PA, VE, MX", "research"),
    L("ELE-GATE 2012 extra", "https://www.ele-gate.com/", "", "", "México", "México", "Plataforma B2B", "Electrónica + hogar + juguetes", "research"),
    L("DataComponents B-Robotix extra", "https://datacomponents.com.mx/", "info@datacomponents.com.mx", "5558948888", "México", "México", "Mayoreo", "Guías y catálogo", "research"),
    L("MCA Chiapas 1997 extra", "https://www.mcachis.com.mx/", "clientes@mcachis.com.mx", "9616132242", "Tuxtla Gutiérrez", "Chiapas", "Regional sureste", "Dell HP Apple acc", "research"),
    L("Soporte técnico MCA extra", "https://www.mcachis.com.mx/", "clientes@mcachis.com.mx", "9616132242", "Tuxtla Gutiérrez", "Chiapas", "Servicio", "Redes y CCTV", "research"),
    L("Hikvision / Dahua canal MCA", "https://www.mcachis.com.mx/", "", "9616132242", "Tuxtla Gutiérrez", "Chiapas", "CCTV", "Adyacente tech", "research"),
    L("Impresoras Lexmark Epson Brother canal", "https://www.mcachis.com.mx/", "", "9616132242", "Tuxtla Gutiérrez", "Chiapas", "Consumibles", "Adyacente", "research"),
    L("Ensamble PCs PCH extra", "https://shop.pchconnect.com/", "hola@pchconnect.com", "(33) 1368-4390", "México", "México", "Servicio", "PCs gamer / oficina", "research"),
    L("Laptops Dell Vostro PCH extra", "https://shop.pchconnect.com/", "", "(33) 1368-4390", "México", "México", "SKU", "Oficina", "research"),
    L("ASUS where-to-buy partners extra", "https://promos.asus.com/MX/where_to_buy/index.html", "", "", "México", "México", "Canal marca", "DDTech Digitalife MiPC Ventronic", "research"),
    L("Cyberpuerta ecom extra", "https://www.cyberpuerta.mx/", "", "", "México", "México", "Ecom líder", "Componentes", "research"),
    L("Zegucom GDL extra", "https://www.zegucom.com.mx/", "", "", "Guadalajara", "Jalisco", "Ecom GDL", "Stock/velocidad", "research"),
    L("Dimercom Puebla extra", "", "", "", "Puebla", "Puebla", "Regional", "Componentes", "research"),
    L("Ignite Mérida extra", "", "", "", "Mérida", "Yucatán", "Regional", "Sureste", "research"),
    L("Grupo DECME extra", "https://www.grupodecme.com/", "", "", "México", "México", "Ecom/ML", "RAM y fuentes", "research"),
    L("Intercompras extra", "https://www.intercompras.com/", "", "", "México", "México", "Ecom", "Tech", "research"),
    L("Gloma extra", "https://www.glomastore.mx/", "", "", "México", "México", "Ecom", "Norte/golfo", "research"),
    L("Lumen sucursales extra", "https://www.lumen.com.mx/", "", "", "México", "México", "Cadena", "Papelería+tech", "brand"),
    L("Compumex extra", "https://www.compumex.mx/", "", "", "México", "México", "Cadena", "Cómputo", "research"),
    L("Ofix extra", "https://www.ofix.com.mx/", "", "", "México", "México", "Cadena", "Oficina", "research"),
    L("Chapur extra", "https://www.chapur.com.mx/", "", "", "Mérida", "Yucatán", "Departamental", "Sureste", "brand"),
    L("Valta CDMX extra", "https://www.valta.com.mx/", "", "", "CDMX", "CDMX", "Mayoreo equipos", "Registro web", "research"),
    L("Gama Plus GDL extra", "https://gamaplus.com.mx/", "", "", "Guadalajara", "Jalisco", "Mayoreo mixto", "Equipos+acc", "research"),
    L("Celulandia open box extra", "https://celulandia.com.mx/mayoreo/", "", "", "México", "México", "Reacondicionado", "Mayoreo 6+", "research"),
    L("Celex Telcel extra", "https://www.celex.com/", "", "", "México", "México", "Telcel + acc", "25k SKU", "research"),
    L("Fixoem MTY extra", "", "", "", "Monterrey", "NL", "Refacciones", "Técnico/mayorista", "research"),
    L("Fixoem Puebla extra", "", "", "", "Puebla", "Puebla", "Refacciones", "Sucursal", "research"),
    L("Fixoem Tijuana extra", "", "", "", "Tijuana", "BC", "Refacciones", "Frontera", "research"),
    L("Todo para Smartphones MTY extra", "", "", "", "Monterrey", "NL", "Mayoreo", "Inventario", "research"),
    L("InstaCase sucursales extra", "https://instacase.mx/", "", "", "CDMX", "CDMX", "D2C multi", "Puebla/Cuernavaca", "research"),
    L("Casa de las Carcasas extra", "https://lacasadelascarcasas.com.mx/", "", "", "México", "México", "Retail", "Personalización", "research"),
    L("Happy Case extra", "https://happycase.com.mx/", "", "", "México", "México", "D2C", "Fundas", "research"),
    L("TARLA piel extra", "https://tarla.com.mx/", "", "", "México", "México", "D2C premium", "Piel", "research"),
    L("FunCases extra", "https://funcases.mx/", "", "", "México", "México", "D2C", "Personalizadas", "research"),
    L("Doto accesorios extra", "https://doto.com.mx/", "", "", "México", "México", "Ecom", "Cargadores / porta laptop", "research"),
    L("iShop extra", "https://www.ishopmixup.com/", "", "", "CDMX", "CDMX", "Apple retail", "Accesorios", "brand"),
    L("CVA mayoreo extra", "https://www.cva.com.mx/", "", "", "México", "México", "Mayorista", "Channel", "research"),
    L("Ingram extra", "", "", "", "México", "México", "Mayorista", "Enterprise", "brand"),
    L("Intcomex extra", "", "", "", "México", "México", "Mayorista", "Channel", "brand"),
    L("Compusoluciones extra", "https://www.compusoluciones.com/", "", "", "Guadalajara", "Jalisco", "Integrador", "B2B", "research"),
    L("Plaza Tecnología extra locales", "", "", "", "CDMX", "CDMX", "Cluster", "Decenas de locales", "research"),
    L("Plaza Computación extra locales", "", "", "", "CDMX", "CDMX", "Cluster", "Cómputo", "research"),
    L("Tepito accesorios extra", "", "", "", "CDMX", "CDMX", "Popular", "Cables/fundas", "research"),
    L("Mayoreo celular León", "", "", "", "León", "Guanajuato", "Cluster Bajío", "Accesorios", "research"),
    L("Mayoreo celular Querétaro", "", "", "", "Querétaro", "Querétaro", "Cluster Bajío", "Accesorios", "research"),
    L("Mayoreo celular Cancún", "", "", "", "Cancún", "Q. Roo", "Cluster turismo", "Accesorios", "research"),
    L("Mayoreo celular Chihuahua", "", "", "", "Chihuahua", "Chihuahua", "Cluster norte", "Accesorios", "research"),
    L("Mayoreo celular Culiacán", "", "", "", "Culiacán", "Sinaloa", "Cluster noroeste", "Accesorios", "research"),
    L("Mayoreo celular Hermosillo", "", "", "", "Hermosillo", "Sonora", "Cluster noroeste", "Accesorios", "research"),
    L("Mayoreo celular Juárez", "", "", "", "Cd. Juárez", "Chihuahua", "Cluster frontera", "Accesorios", "research"),
    L("Mayoreo celular Mexicali", "", "", "", "Mexicali", "BC", "Cluster frontera", "Accesorios", "research"),
    L("Mayoreo celular Veracruz", "", "", "", "Veracruz", "Veracruz", "Cluster golfo", "Accesorios", "research"),
    L("Mayoreo celular Mérida extra", "", "", "", "Mérida", "Yucatán", "Cluster sureste", "PCH + locales", "research"),
    L("Belkin / Anker / Baseus retail extra", "", "", "", "México", "México", "Marcas acc", "Canal moderno", "brand"),
    L("Spigen / OtterBox retail extra", "", "", "", "México", "México", "Marcas fundas", "Premium", "brand"),
    L("Targus / Case Logic extra", "", "", "", "México", "México", "Porta laptop", "Business", "brand"),
    L("Logitech retail extra", "", "", "", "México", "México", "Periféricos", "Retail", "brand"),
    L("Xiaomi Mi acc extra", "", "", "", "México", "México", "Ecosistema", "Cargadores", "brand"),
    L("Samsung acc extra", "https://www.samsung.com/mx/", "", "", "México", "México", "OEM acc", "Fundas oficiales", "brand"),
    L("Apple acc extra", "", "", "", "México", "México", "OEM acc", "iShop", "brand"),
]


def main():
    print("Generating lotes 09-10…")
    dump("09", "almohadas_cobijas", "Blancos: almohadas, cobijas, sábanas y textiles de cama MX", BLANCOS)
    dump("10", "cargadores_porta_laptop", "Tecnología: cargadores, fundas, accesorios y porta laptop MX", TECH)
    print(f"counts: 09={len(BLANCOS)} 10={len(TECH)}")


if __name__ == "__main__":
    main()
