#!/usr/bin/env python3
"""Generate seeds for lotes 11 trajes típicos and 12 zapatos danza (200-300)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def dump(lote, slug, desc, leads):
    path = ROOT / "config" / "seeds" / f"{lote}_{slug}.json"
    path.write_text(
        json.dumps({"lote": lote, "slug": slug, "description": desc, "leads": leads}, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"  {path.name}: {len(leads)} seeds")


TRAJES = [
    L("Dos Malinches", "https://dosmalinches.com/", "", "", "México", "México", "Ejemplo original", "Ejemplo del cliente — ropa étnica, huipiles y vestidos", "ejemplo_cliente"),
    L("El Charro", "https://www.elcharro1.com/", "sales@elcharro1.com", "9155347956", "Guadalajara", "Jalisco", "Fabricante", "Desde 1961 mariachi, folklórico, tiendas GDL/CDMX/El Paso", "research"),
    L("Fábrica Los Gabrieles", "https://fabricadetrajesdecharrogabrieles.com/", "ventas@fabricadetrajesdecharrogabrieles.com", "(55) 6794-1664", "CDMX", "CDMX", "Fabricante charro", "+45 años, Calle 5 #235 Azcapotzalco", "research"),
    L("Los Gabrieles sucursal León", "https://fabricadetrajesdecharrogabrieles.com/", "ventas@fabricadetrajesdecharrogabrieles.com", "(55) 3701-5964", "León", "Guanajuato", "Sucursal", "Plaza La Esperanza, Justo Sierra 224", "research"),
    L("Charros and Cowboys Toluca", "", "", "7223579599", "Toluca", "EdoMex", "Mayoreo/menudeo", "Ignacio López Rayón 200 Centro + Villa Charra", "research"),
    L("Mayakim", "https://www.mayakim.com.mx/", "", "", "Mérida", "Yucatán", "Marca yucateca", "Guayaberas y vestidos, Calle 40 #506 Los Pinos", "research"),
    L("JBO Lino", "https://www.jbolino.com/", "", "", "Mérida", "Yucatán", "Guayaberas", "Bazar García Rejón, lino ~1000 MXN", "research"),
    L("Isa y Alex Mayoreo Artesanal", "https://trajesartesanales.com/", "", "9711164783", "Juchitán", "Oaxaca", "Mayoreo istmeño", "Huipiles, enaguas, tehuana, envíos MX", "research"),
    L("Distribuidora Zucami CDMX", "", "", "5534516463", "CDMX", "CDMX", "Mayoreo artesanías", "República del Salvador 96 2o piso Centro", "research"),
    L("Charrería y Vestidos Reyes", "", "", "5511353982", "CDMX", "CDMX", "Lagunilla", "Trajes de charro y regionales", "research"),
    L("Disfrazia trajes regionales", "https://www.disfrazia.com.mx/", "", "5555262563", "CDMX", "CDMX", "Tienda", "Disfraces y típicos", "research"),
    L("El Famundi trajes regionales", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Fabricante", "Regionales y fantasía", "research"),
    L("Presuel guayaberas", "", "", "", "Mérida", "Yucatán", "Tienda", "Precios locales", "research"),
    L("G. Candila", "", "", "", "Mérida", "Yucatán", "Tienda", "Guayaberas temporada", "research"),
    L("La Joyita Portal de Granos", "", "", "", "Mérida", "Yucatán", "Tienda centro", "Bordados y guayaberas", "research"),
    L("Guayaberas Parque Eulogio Rosado", "", "", "", "Mérida", "Yucatán", "Cluster", "Varias tiendas", "research"),
    L("Guayaberas Parque Santa Ana", "", "", "", "Mérida", "Yucatán", "Cluster", "C. 45 y 60", "research"),
    L("Guayaberas Izamal", "", "", "", "Izamal", "Yucatán", "Cluster pueblo", "Varias tiendas", "research"),
    L("Guayaberas Valladolid", "", "", "", "Valladolid", "Yucatán", "Cluster", "Plaza principal", "research"),
    L("Guayaberas Campeche", "", "", "", "Campeche", "Campeche", "Cluster", "Mejores precios que Valladolid", "research"),
    L("Productos Regionales CT Tabasco", "", "", "", "Villahermosa", "Tabasco", "Tienda", "Plaza Campestre / Galerías", "research"),
    L("Trajes Tehuana Juchitán extra", "https://trajesartesanales.com/juchitan-ropa-artesanal/", "", "9711164783", "Juchitán", "Oaxaca", "Línea istmo", "Huipil y enagua", "research"),
    L("Huipiles Oaxaca mayoreo", "", "", "", "Oaxaca", "Oaxaca", "Mayoreo", "Bordado a mano", "research"),
    L("Huipiles Tehuacán / Sierra", "", "", "", "Tehuacán", "Puebla", "Artesanal", "Región", "research"),
    L("China Poblana Puebla tiendas", "", "", "", "Puebla", "Puebla", "Regional", "Traje típico Puebla", "research"),
    L("Trajes jalisco / escaramuza GDL", "", "", "", "Guadalajara", "Jalisco", "Charro/escaramuza", "Occidente", "research"),
    L("Trajes jarabe tapatío", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "Guadalajara", "Jalisco", "Folklórico", "El Charro línea", "research"),
    L("Sombreros de charro mayoreo", "", "", "", "México", "México", "Accesorio", "Complemento traje", "research"),
    L("Botonadura y herrajes charro", "", "", "", "León", "Guanajuato", "Insumos", "Piel y metal", "research"),
    L("Moños y corbatas de charro", "", "", "", "CDMX", "CDMX", "Accesorio", "Lagunilla / Centro", "research"),
    L("Botas charro León", "", "", "", "León", "Guanajuato", "Calzado", "Cluster cuero", "research"),
    L("Cintos piteados mayoreo", "", "", "", "Colotlán", "Jalisco", "Accesorio", "Piteado tradicional", "research"),
    L("Sarapes Saltillo", "", "", "", "Saltillo", "Coahuila", "Textil", "Sarape típico", "research"),
    L("Rebozos Tenancingo", "", "", "", "Tenancingo", "EdoMex", "Textil", "Rebozo tradicional", "research"),
    L("Rebozos Santa María del Río", "", "", "", "Santa María del Río", "SLP", "Textil", "Seda y algodón", "research"),
    L("Quechquémitl Hidalgo / Puebla", "", "", "", "Hidalgo", "Hidalgo", "Artesanal", "Sierra", "research"),
    L("Trajes de chinelo Morelos", "", "", "", "Tlayacapan", "Morelos", "Regional", "Carnaval", "research"),
    L("Trajes de concheros CDMX", "", "", "", "CDMX", "CDMX", "Danza ritual", "Insumos", "research"),
    L("Trajes yaquis / pascola Sonora", "", "", "", "Hermosillo", "Sonora", "Regional", "Noroeste", "research"),
    L("Trajes tarahumara / rarámuri", "", "", "", "Creel", "Chihuahua", "Artesanal", "Sierra Tarahumara", "research"),
    L("Trajes huichol / wixárika", "", "", "", "Tepic", "Nayarit", "Artesanal", "Chaquira y manta", "research"),
    L("Trajes purépecha Michoacán", "", "", "", "Pátzcuaro", "Michoacán", "Artesanal", "Rebozo y delantal", "research"),
    L("Trajes mazahua / otomí EdoMex", "", "", "", "Toluca", "EdoMex", "Artesanal", "Bordado", "research"),
    L("Trajes totonacos Veracruz", "", "", "", "Papantla", "Veracruz", "Regional", "Voladores / fiesta", "research"),
    L("Trajes jarocho Veracruz", "", "", "", "Veracruz", "Veracruz", "Regional", "Fandango", "research"),
    L("Trajes chiapanecos / chiapaneca", "", "", "", "Tuxtla Gutiérrez", "Chiapas", "Regional", "Enagua y blusa", "research"),
    L("Trajes Chamula / Zinacantán", "", "", "", "San Cristóbal", "Chiapas", "Artesanal", "Lana y brocado", "research"),
    L("Trajes Yucatán terno", "", "", "", "Mérida", "Yucatán", "Regional", "Terno y hipil", "research"),
    L("Hipiles mayas Quintana Roo", "", "", "", "Cancún", "Q. Roo", "Artesanal", "Turismo + local", "research"),
    L("Trajes Campeche regional", "", "", "", "Campeche", "Campeche", "Regional", "Guayabera y terno", "research"),
    L("Trajes tabasqueños", "", "", "", "Villahermosa", "Tabasco", "Regional", "Feria", "research"),
    L("Trajes guerrerenses / chilena", "", "", "", "Acapulco", "Guerrero", "Regional", "Costa chica", "research"),
    L("Trajes tlaxcaltecas", "", "", "", "Tlaxcala", "Tlaxcala", "Regional", "Carnaval", "research"),
    L("Trajes hidalguenses", "", "", "", "Pachuca", "Hidalgo", "Regional", "Sierra y valle", "research"),
    L("Trajes queretanos", "", "", "", "Querétaro", "Querétaro", "Regional", "Sierra gorda", "research"),
    L("Trajes guanajuatenses", "", "", "", "Guanajuato", "Guanajuato", "Regional", "Fiestas", "research"),
    L("Trajes zacatecanos", "", "", "", "Zacatecas", "Zacatecas", "Regional", "Charro norteño", "research"),
    L("Trajes duranguenses", "", "", "", "Durango", "Durango", "Regional", "Norte", "research"),
    L("Trajes sinaloenses / banda", "", "", "", "Culiacán", "Sinaloa", "Regional", "Occidente norte", "research"),
    L("Trajes nayaritas", "", "", "", "Tepic", "Nayarit", "Regional", "Costa + wixárika", "research"),
    L("Trajes colimenses", "", "", "", "Colima", "Colima", "Regional", "Pequeño mercado", "research"),
    L("Trajes morelenses extra", "", "", "", "Cuernavaca", "Morelos", "Regional", "Chinelo + fiesta", "research"),
    L("Trajes mexiquenses extra", "", "", "", "Toluca", "EdoMex", "Regional", "Mazahua/otomí", "research"),
    L("Trajes CDMX / chinampa / Xochimilco", "", "", "", "Xochimilco", "CDMX", "Regional", "Embarcadero / fiesta", "research"),
    L("Trajes Baja California folklórico", "", "", "", "Tijuana", "BC", "Escuelas danza", "Grupos folklóricos", "research"),
    L("Trajes Nuevo León folklórico", "", "", "", "Monterrey", "NL", "Escuelas danza", "Grupos", "research"),
    L("Trajes Coahuila folklórico", "", "", "", "Saltillo", "Coahuila", "Regional", "Sarape + danza", "research"),
    L("Mercado de Sonora regionales extra", "", "", "", "CDMX", "CDMX", "Mayoreo mercado", "Trajes y accesorios", "research"),
    L("Mercado Lagunilla charro extra", "", "", "5511353982", "CDMX", "CDMX", "Mayoreo", "Comonfort", "research"),
    L("Centro Histórico CDMX artesanías extra", "", "", "5534516463", "CDMX", "CDMX", "Mayoreo centro", "Salvador / Palma", "research"),
    L("La Ciudadela artesanías CDMX", "", "", "", "CDMX", "CDMX", "Mercado artesanal", "Textiles y trajes", "research"),
    L("FONART tiendas", "https://www.gob.mx/fonart", "", "", "CDMX", "CDMX", "Institucional", "Artesanías oficiales", "brand"),
    L("Casa de las Artesanías Puebla", "", "", "", "Puebla", "Puebla", "Institucional", "Trajes y textiles", "research"),
    L("Casa de las Artesanías Oaxaca", "", "", "", "Oaxaca", "Oaxaca", "Institucional", "Huipiles", "research"),
    L("Casa de las Artesanías Michoacán", "", "", "", "Morelia", "Michoacán", "Institucional", "Textiles", "research"),
    L("Casa de las Artesanías Jalisco", "", "", "", "Guadalajara", "Jalisco", "Institucional", "Charro y huichol", "research"),
    L("IEPA / artesanías Yucatán", "", "", "", "Mérida", "Yucatán", "Institucional", "Hipil y hamaca", "research"),
    L("Renta trajes regionales CDMX", "", "", "2283062367", "CDMX", "CDMX", "Renta", "Eventos escolares", "research"),
    L("Renta trajes regionales Oaxaca", "", "", "", "Oaxaca", "Oaxaca", "Renta", "Guelaguetza", "research"),
    L("Renta trajes Guelaguetza", "", "", "", "Oaxaca", "Oaxaca", "Temporada", "Julio", "research"),
    L("Renta china poblana Puebla", "", "", "", "Puebla", "Puebla", "Renta", "Escuelas", "research"),
    L("Renta charro GDL", "", "", "", "Guadalajara", "Jalisco", "Renta", "Eventos y XV", "research"),
    L("Renta charro León", "https://fabricadetrajesdecharrogabrieles.com/", "", "(55) 3701-5964", "León", "Guanajuato", "Renta/venta", "Sucursal Gabrieles", "research"),
    L("Renta charro Toluca", "", "", "7221603175", "Toluca", "EdoMex", "Renta", "Boutique charro", "research"),
    L("Confección a la medida charro CDMX", "https://fabricadetrajesdecharrogabrieles.com/", "ventas@fabricadetrajesdecharrogabrieles.com", "(55) 2631-6476", "CDMX", "CDMX", "Taller", "Azcapotzalco", "research"),
    L("Confección a la medida El Charro", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "Guadalajara", "Jalisco", "Taller", "Mayoreo US/MX", "research"),
    L("El Charro sucursal CDMX", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "CDMX", "CDMX", "Sucursal", "Retail", "research"),
    L("El Charro sucursal GDL extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "Guadalajara", "Jalisco", "Sucursal", "Matriz histórica", "research"),
    L("El Charro El Paso extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "8779801248", "El Paso", "TX", "Sucursal US", "Wyoming 2509 — export", "research"),
    L("Wrangler / western Toluca extra", "", "", "7223579599", "Toluca", "EdoMex", "Western + charro", "Mayoreo lives", "research"),
    L("Ropa vaquera mayoreo Bajío", "", "", "", "León", "Guanajuato", "Western", "Adyacente charro", "research"),
    L("Sombreros Stetson / texana MX", "", "", "", "México", "México", "Accesorio", "Complemento", "research"),
    L("Bordadoras Oaxaca cooperativas", "", "", "", "Oaxaca", "Oaxaca", "Cooperativa", "Huipil", "research"),
    L("Bordadoras Chiapas cooperativas", "", "", "", "San Cristóbal", "Chiapas", "Cooperativa", "Broches y huipil", "research"),
    L("Bordadoras Yucatán cooperativas", "", "", "", "Mérida", "Yucatán", "Cooperativa", "Hipil", "research"),
    L("Bordadoras Guerrero Costa Chica", "", "", "", "Ometepec", "Guerrero", "Cooperativa", "Textil afromexicano", "research"),
    L("Bordadoras Tenango Hidalgo", "", "", "", "Tenango de Doria", "Hidalgo", "Artesanal", "Tenangos", "research"),
    L("Bordadoras San Antonino Oaxaca", "", "", "", "Ocotlán", "Oaxaca", "Artesanal", "San Antonino Castillo Velasco", "research"),
    L("Agujas de oro / filigrana textil", "", "", "", "Oaxaca", "Oaxaca", "Artesanal premium", "Novia istmeña", "research"),
    L("Trajes infantiles folklóricos mayoreo", "", "", "", "CDMX", "CDMX", "Infantil", "Escuelas de danza", "research"),
    L("Trajes escolares folklor CDMX", "", "", "", "CDMX", "CDMX", "Canal escolar", "Primarias", "research"),
    L("Trajes universitarios folklor", "", "", "", "México", "México", "Canal uni", "Grupos representativos", "research"),
    L("Insumos listón y encaje folklor", "", "", "", "CDMX", "CDMX", "Insumos", "Mercería danza", "research"),
    L("Enaguas de listón mayoreo", "", "", "", "CDMX", "CDMX", "Prenda", "Folklor", "research"),
    L("Blusas campesinas mayoreo", "", "", "", "CDMX", "CDMX", "Prenda", "Folklor", "research"),
    L("Delantales folklóricos mayoreo", "", "", "", "México", "México", "Prenda", "Estados varios", "research"),
    L("Huaraches danza folklórica", "", "", "", "México", "México", "Calzado adyacente", "Complemento traje", "research"),
    L("Peinetas y accesorios peinado", "", "", "", "CDMX", "CDMX", "Accesorio", "Folklor / china poblana", "research"),
    L("Abanicos y mandiles típicos", "", "", "", "México", "México", "Accesorio", "Veracruz / Jalisco", "research"),
    L("Mayoreo Centro GDL típicos", "", "", "", "Guadalajara", "Jalisco", "Cluster", "San Juan de Dios adyacente", "research"),
    L("Tlaquepaque artesanías trajes", "", "", "", "Tlaquepaque", "Jalisco", "Turismo + local", "Textil", "research"),
    L("Tonalá artesanías textil", "", "", "", "Tonalá", "Jalisco", "Cluster", "Complemento", "research"),
    L("San Juan de Dios textiles extra", "", "", "", "Guadalajara", "Jalisco", "Mayoreo popular", "Típicos", "research"),
    L("Mercado 20 de Noviembre Oaxaca extra", "", "", "", "Oaxaca", "Oaxaca", "Mercado", "Huipiles", "research"),
    L("Mercado de Abastos Oaxaca extra", "", "", "", "Oaxaca", "Oaxaca", "Mayoreo", "Textil", "research"),
    L("Mercado Lucas de Gálvez Mérida extra", "", "", "", "Mérida", "Yucatán", "Mercado", "Hipiles", "research"),
    L("Bazar García Rejón extra", "https://www.jbolino.com/", "", "", "Mérida", "Yucatán", "Bazar", "JBO y vecinos", "research"),
    L("Plaza Campestre Tabasco extra", "", "", "", "Villahermosa", "Tabasco", "Plaza", "Regionales CT", "research"),
    L("Turismo Cancún hipiles extra", "", "", "", "Cancún", "Q. Roo", "Turismo", "Souvenir + real", "research"),
    L("Turismo Los Cabos típicos extra", "", "", "", "Los Cabos", "BCS", "Turismo", "Souvenir", "research"),
    L("Turismo Puerto Vallarta típicos extra", "", "", "", "Puerto Vallarta", "Jalisco", "Turismo", "Huichol + charro", "research"),
    L("Turismo San Miguel Allende extra", "", "", "", "San Miguel de Allende", "Guanajuato", "Turismo", "Textil boutique", "research"),
    L("Boutique típicos Roma / Condesa", "", "", "", "CDMX", "CDMX", "Boutique", "Diseño contemporáneo", "research"),
    L("Boutique típicos Polanco", "", "", "", "CDMX", "CDMX", "Boutique", "Premium", "research"),
    L("Boutique típicos Coyoacán", "", "", "", "CDMX", "CDMX", "Boutique", "Artesanal", "research"),
    L("Dos Malinches ecom extra", "https://dosmalinches.com/", "", "", "México", "México", "Ecom", "Huipiles y vestidos", "research"),
    L("Mayakim ecom extra", "https://www.mayakim.com.mx/", "", "", "Mérida", "Yucatán", "Ecom", "Envíos nacionales", "research"),
    L("El Charro ecom extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "9155347956", "Guadalajara", "Jalisco", "Ecom US/MX", "Mayoreo", "research"),
    L("Gabrieles ecom extra", "https://fabricadetrajesdecharrogabrieles.com/", "ventas@fabricadetrajesdecharrogabrieles.com", "(55) 6794-1664", "CDMX", "CDMX", "Ecom", "Mayoreo/menudeo", "research"),
    L("Isa y Alex ecom extra", "https://trajesartesanales.com/", "", "9711164783", "Juchitán", "Oaxaca", "Ecom mayoreo", "Istmo", "research"),
    L("ML vestidos típicos sellers", "https://listado.mercadolibre.com.mx/traje-tipico-mexicano", "", "", "México", "México", "Marketplace", "Tiendas oficiales", "research"),
    L("Amazon MX typical dresses", "https://www.amazon.com.mx/s?k=traje+tipico", "", "", "México", "México", "Marketplace", "Sellers", "research"),
    L("Liverpool ropa típica / fiestas", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada", "brand"),
    L("Palacio artesanías / textil", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Diseño", "brand"),
    L("FONART ecom extra", "https://www.gob.mx/fonart", "", "", "CDMX", "CDMX", "Institucional", "Catálogo", "brand"),
    L("Cooperativa textil Chiapas extra", "", "", "", "San Cristóbal", "Chiapas", "Cooperativa", "Mujeres tejedoras", "research"),
    L("Cooperativa textil Oaxaca extra", "", "", "", "Oaxaca", "Oaxaca", "Cooperativa", "Telar de cintura", "research"),
    L("Cooperativa textil Yucatán extra", "", "", "", "Mérida", "Yucatán", "Cooperativa", "Bordado maya", "research"),
    L("Taller charro Azcapotzalco extra", "https://fabricadetrajesdecharrogabrieles.com/", "", "(55) 2631-6476", "CDMX", "CDMX", "Taller", "Gabrieles", "research"),
    L("Villa Charra Toluca extra", "", "", "7223579599", "Toluca", "EdoMex", "Punto venta", "González y Pichardo 123", "research"),
    L("Lives mayoreo charro Toluca extra", "", "", "7221603175", "Toluca", "EdoMex", "Canal digital", "5:30 PM", "research"),
    L("Envíos nacionales típicos extra", "", "", "", "México", "México", "Logística", "Mayoreo", "research"),
    L("Personalización bordado logo extra", "", "", "", "México", "México", "Servicio", "Escuelas de danza", "research"),
    L("Trajes de gala folklor extra", "", "", "", "México", "México", "Gala", "Competencias", "research"),
    L("Trajes de ensayo folklor extra", "", "", "", "México", "México", "Ensayo", "Escuelas", "research"),
    L("Polleras y enaguas extra", "", "", "", "México", "México", "Prenda", "Folklor", "research"),
    L("Camisas de manta extra", "", "", "", "México", "México", "Prenda", "Campesino / danza", "research"),
    L("Calzones de manta extra", "", "", "", "México", "México", "Prenda", "Folklor varonil", "research"),
    L("Jorongos y gabanes extra", "", "", "", "México", "México", "Abrigo típico", "Norte/centro", "research"),
    L("Ponchos y gabanes norte extra", "", "", "", "Chihuahua", "Chihuahua", "Norte", "Frío", "research"),
    L("Fajas y ceñidores extra", "", "", "", "México", "México", "Accesorio", "Folklor", "research"),
    L("Collares y chaquiras huichol extra", "", "", "", "Tepic", "Nayarit", "Accesorio", "Wixárika", "research"),
    L("Huaraches de pita extra", "", "", "", "México", "México", "Calzado", "Complemento", "research"),
    L("Zapatos folklóricos Manzano canal traje", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Calzado adyacente", "Pareja del traje", "research"),
    L("El Charro zapatos folklor extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "Guadalajara", "Jalisco", "Calzado adyacente", "Misma marca", "research"),
    L("Escuelas de danza folklórica CDMX cluster", "", "", "", "CDMX", "CDMX", "Canal B2B", "Compran trajes", "research"),
    L("Escuelas folklor GDL cluster", "", "", "", "Guadalajara", "Jalisco", "Canal B2B", "Compran trajes", "research"),
    L("Escuelas folklor MTY cluster", "", "", "", "Monterrey", "NL", "Canal B2B", "Compran trajes", "research"),
    L("Ballet folklórico institucional extra", "", "", "", "México", "México", "Canal institucional", "Compañías", "research"),
    L("Municipios / casas de cultura extra", "", "", "", "México", "México", "Canal gobierno", "Eventos cívicos", "research"),
    L("XV años típico / charro extra", "", "", "", "México", "México", "Canal eventos", "Renta y venta", "research"),
    L("Bodas típicas / charro extra", "", "", "", "México", "México", "Canal eventos", "A la medida", "research"),
    L("Carnaval regionales extra", "", "", "", "México", "México", "Temporada", "Veracruz / Morelos", "research"),
    L("Fiestas patrias temporada extra", "", "", "", "México", "México", "Temporada sep", "Pico de venta", "research"),
    L("Día de Muertos textil extra", "", "", "", "México", "México", "Temporada", "Oaxaca / Mixquic", "research"),
    L("Navidad pastorela típicos extra", "", "", "", "México", "México", "Temporada", "Adyacente disfraz", "research"),
    L("Export US folklórico extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "8779801248", "El Paso", "TX", "Export", "Comunidades MX-US", "research"),
    L("Cinco de Mayo export extra", "", "", "", "México", "México", "Export temporada", "US retail", "research"),
    L("Mayoreo Centro León cuero+charro extra", "", "", "", "León", "Guanajuato", "Cluster", "Gabrieles + talleres", "research"),
    L("Mayoreo Azcapotzalco charro extra", "https://fabricadetrajesdecharrogabrieles.com/", "", "(55) 6794-1664", "CDMX", "CDMX", "Cluster", "Porvenir", "research"),
    L("Mayoreo Toluca charro extra", "", "", "7223579599", "Toluca", "EdoMex", "Cluster", "Cowboys + Villa Charra", "research"),
    L("Mayoreo Mérida guayabera extra", "https://www.mayakim.com.mx/", "", "", "Mérida", "Yucatán", "Cluster", "Varias fábricas", "research"),
    L("Mayoreo Juchitán extra", "https://trajesartesanales.com/", "", "9711164783", "Juchitán", "Oaxaca", "Cluster istmo", "Isa y Alex + talleres", "research"),
    L("Mayoreo Oaxaca centro extra", "", "", "", "Oaxaca", "Oaxaca", "Cluster", "Huipil", "research"),
    L("Mayoreo San Cristóbal extra", "", "", "", "San Cristóbal", "Chiapas", "Cluster", "Lana", "research"),
    L("Taller Los Gabrieles extra", "https://fabricadetrajesdecharrogabrieles.com/", "ventas@fabricadetrajesdecharrogabrieles.com", "(55) 3701-5964", "CDMX", "CDMX", "Taller", "WhatsApp", "research"),
    L("Oficina central Gabrieles extra", "https://fabricadetrajesdecharrogabrieles.com/", "", "(55) 6794-1664", "CDMX", "CDMX", "Oficina", "CP 02940", "research"),
    L("Plaza La Esperanza León extra", "https://fabricadetrajesdecharrogabrieles.com/", "", "", "León", "Guanajuato", "Punto venta", "Justo Sierra 224", "research"),
    L("Mayakim Los Pinos extra", "https://www.mayakim.com.mx/", "", "", "Mérida", "Yucatán", "Tienda", "Estacionamiento", "research"),
    L("JBO Lino extra", "https://www.jbolino.com/", "", "", "Mérida", "Yucatán", "Marca lino", "Calidad local", "research"),
    L("Dos Malinches vestidos extra", "https://dosmalinches.com/", "", "", "México", "México", "Línea vestido", "Ana, Roberta, Catalina", "research"),
    L("El Charro blusa Chiapas extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "Guadalajara", "Jalisco", "SKU", "Regionales por estado", "research"),
    L("El Charro catálogo estados extra", "https://www.elcharro1.com/", "sales@elcharro1.com", "", "Guadalajara", "Jalisco", "Catálogo", "Guerrero, Tamaulipas, Oaxaca…", "research"),
]

DANZA = [
    L("Calzado Manzano", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Ejemplo original", "Ejemplo del cliente — folklórico, Juan Aldama 603", "ejemplo_cliente"),
    L("ZA&ZA Dancewear", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "Monterrey", "NL", "Multimarca", "+15 años, MTY/Puebla/Oaxaca, envíos MX", "research"),
    L("Pirouette Dancewear", "https://www.pirouette.mx/", "tienda@pirouette.mx", "3336100291", "Zapopan", "Jalisco", "Tienda ballet", "Pablo Neruda 4341 Plaza Universidad Local G4", "research"),
    L("Allegro Dance Store", "https://allegro.mx/", "", "(222) 169-7869", "Puebla", "Puebla", "Retail danza", "Circuito Juan Pablo II 3111 Las Ánimas", "research"),
    L("Miguelito Dancing Shoes", "https://miguelitousa.com/home.html", "", "", "CDMX", "CDMX", "Fabricante teatral", "Ballet/flamenco/folklore CDMX", "research"),
    L("Kuali Shoes", "https://listado.mercadolibre.com.mx/zapatos-flamenco-danza_Store_kuali-shoes", "", "", "México", "México", "Marca ML", "Flamenco y folklórica", "research"),
    L("Dance Field", "https://www.dancefield.com.mx/", "", "3343160899", "Guadalajara", "Jalisco", "Tienda líder GDL", "Plaza Los Arcos Vallarta 2440 — 33 3616 2036", "research"),
    L("Andanzza", "https://andanzza.com.mx/", "", "(55) 6155-8577", "CDMX", "CDMX", "Tienda ballet", "Interlomas (55) 5580-5898", "research"),
    L("Bluëin Shoes", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Fabricante baile social", "Tango/salsa/bachata — Parroquia 637 Del Valle", "research"),
    L("Don León Calzado Danza Teatral", "", "", "", "San Mateo Atenco", "EdoMex", "Fabricante", "Guerrero 611 Barrio San Miguel", "research"),
    L("Danzar S.A. de C.V.", "", "", "", "San Mateo Atenco", "EdoMex", "Fabricante", "Industria Norte 59", "research"),
    L("Zapatos De Danza Regional Lagunilla", "", "castrolopezamerica@icloud.com", "5539682121", "CDMX", "CDMX", "Mayoreo mercado", "Lagunilla pasillo 1 local 97-98", "research"),
    L("ZA&ZA sucursal Monterrey", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "Monterrey", "NL", "Sucursal", "Hidalgo 2258 Pte Plaza Picachos Local 10", "research"),
    L("ZA&ZA sucursal Puebla", "https://info.zazadancewear.com/", "", "5561894779", "Puebla", "Puebla", "Sucursal", "Plaza Universidad Local 1C", "research"),
    L("ZA&ZA sucursal Oaxaca", "https://info.zazadancewear.com/", "", "5561894779", "Oaxaca", "Oaxaca", "Sucursal", "Heroico Colegio Militar 420 Reforma", "research"),
    L("ZA&ZA en Barbiboo Guadalupe", "", "", "8141883606", "Guadalupe", "NL", "Punto venta", "Plaza Santa María Pablo Livas 7500", "research"),
    L("Dance Field Plaza Los Arcos extra", "https://www.dancefield.com.mx/", "", "3323893706", "Guadalajara", "Jalisco", "Sucursal", "WhatsApp + tienda", "research"),
    L("Dance Field Los Robles Zapopan", "https://www.dancefield.com.mx/", "", "3343160899", "Zapopan", "Jalisco", "Dirección fiscal/tienda", "Av. Los Robles 2075", "research"),
    L("Andanzza Interlomas extra", "https://andanzza.com.mx/", "", "(55) 5580-5898", "Huixquilucan", "EdoMex", "Sucursal", "CC Interlomas", "research"),
    L("Allegro sucursal Las Ánimas extra", "", "", "(222) 168-9786", "Puebla", "Puebla", "Sucursal", "Juan Pablo II 3111", "research"),
    L("Calzado Manzano showroom extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Showroom", "Juan Aldama 603 Santiago", "research"),
    L("Capezio México vía retailers", "", "", "", "México", "México", "Marca internacional", "ZA&ZA / Dance Field / Andanzza", "brand"),
    L("Bloch México vía retailers", "", "", "", "México", "México", "Marca internacional", "Puntas y jazz", "brand"),
    L("Grishko México vía retailers", "", "", "", "México", "México", "Marca internacional", "Puntas rusas", "brand"),
    L("Sansha México", "", "", "", "México", "México", "Marca internacional", "Jazz/ballet", "brand"),
    L("So Danca México", "", "", "", "México", "México", "Marca internacional", "Retail danza", "brand"),
    L("Wear Moi México", "", "", "", "México", "México", "Marca internacional", "Mallas y puntas", "brand"),
    L("Gaynor Minden México", "", "", "", "México", "México", "Marca premium", "Puntas", "brand"),
    L("Freed of London México", "", "", "", "México", "México", "Marca premium", "Puntas", "brand"),
    L("Russian Pointe México", "", "", "", "México", "México", "Marca puntas", "Retail especialidad", "brand"),
    L("Leo's Dancewear México", "", "", "", "México", "México", "Marca", "Jazz/tap", "brand"),
    L("Bloch tap shoes extra", "", "", "", "México", "México", "Línea tap", "Retailers MX", "brand"),
    L("Capezio character extra", "", "", "", "México", "México", "Línea character", "Teatro", "brand"),
    L("Zapatos de flamenco MX fábricas", "", "", "", "México", "México", "Flamenco", "Manzano / Miguelito / Kuali", "research"),
    L("Zapatos de folklor San Mateo cluster", "", "", "", "San Mateo Atenco", "EdoMex", "Cluster fábrica", "Decenas de talleres", "research"),
    L("Plaza Azul calzado Atenco", "", "", "7282870863", "San Mateo Atenco", "EdoMex", "Grupo artesanal", "Mayoreo calzado", "research"),
    L("Ital Group de México", "", "", "7282880173", "San Mateo Atenco", "EdoMex", "Fabricante", "Del Panteón 309", "research"),
    L("Supllies de México / Berrendo", "", "", "7282882501", "San Mateo Atenco", "EdoMex", "Insumos calzado", "Benito Juárez 218", "research"),
    L("Centro Proveedora de Tacones", "", "", "7282872026", "San Mateo Atenco", "EdoMex", "Insumos", "Benito Juárez 821 San Luquitas", "research"),
    L("Gonze But", "", "", "7282874087", "San Mateo Atenco", "EdoMex", "Fabricante", "Independencia 432 San Francisco", "research"),
    L("Fábrica de Sandalias FASA", "", "", "", "San Mateo Atenco", "EdoMex", "Fabricante", "Blvd Miguel Alemán 65", "research"),
    L("Huaraches danza folklórica extra", "", "", "", "México", "México", "Huarache", "Complemento traje", "research"),
    L("Botín folklórico extra", "", "", "5539682121", "CDMX", "CDMX", "Botín", "Lagunilla", "research"),
    L("Zapatillas de punta fitting Pirouette", "https://www.pirouette.mx/", "tienda@pirouette.mx", "3336100291", "Zapopan", "Jalisco", "Fitting profesional", "Cita", "research"),
    L("Zapatillas de media punta mayoreo", "", "", "", "México", "México", "Mayoreo escuelas", "Retailers", "research"),
    L("Zapatillas de jazz mayoreo", "", "", "", "México", "México", "Jazz", "Capezio/Bloch canal", "research"),
    L("Zapatos de tap / claqué MX", "", "", "", "México", "México", "Tap", "Retail especialidad", "research"),
    L("Zapatos de contemporáneo MX", "", "", "", "México", "México", "Contemporáneo", "Foot thongs / paws", "research"),
    L("Zapatos de heels / exotic dance MX", "", "", "", "México", "México", "Heels", "ZA&ZA línea", "research"),
    L("Zapatos de salsa / bachata Bluëin extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Baile social", "Hecho en México", "research"),
    L("Zapatos de tango Bluëin extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Tango", "Del Valle", "research"),
    L("Zapatos de danzón / ballroom extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Salón", "Eventos", "research"),
    L("Zapatos XV / boda baile extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Eventos", "Comodidad", "research"),
    L("Mallas y maillots ZA&ZA extra", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "Monterrey", "NL", "Indumentaria", "Complemento calzado", "research"),
    L("Barras de ballet Dance Field extra", "https://www.dancefield.com.mx/", "", "3343160899", "Guadalajara", "Jalisco", "Equipo", "Flete especial", "research"),
    L("Accesorios danza Andanzza extra", "https://andanzza.com.mx/", "", "(55) 6155-8577", "CDMX", "CDMX", "Accesorios", "Ecom nacional", "research"),
    L("Tiendas danza CDMX cluster", "", "", "", "CDMX", "CDMX", "Cluster", "Andanzza + Miguelito + Lagunilla", "research"),
    L("Tiendas danza GDL cluster", "", "", "", "Guadalajara", "Jalisco", "Cluster", "Dance Field + Pirouette", "research"),
    L("Tiendas danza MTY cluster", "", "", "", "Monterrey", "NL", "Cluster", "ZA&ZA + Barbiboo", "research"),
    L("Tiendas danza Puebla cluster", "", "", "", "Puebla", "Puebla", "Cluster", "Allegro + ZA&ZA", "research"),
    L("Tiendas danza Oaxaca extra", "https://info.zazadancewear.com/", "", "5561894779", "Oaxaca", "Oaxaca", "Sucursal", "Colectivo Mujer Oaxaqueña", "research"),
    L("Tiendas danza León", "", "", "", "León", "Guanajuato", "Regional", "Escuelas ballet", "research"),
    L("Tiendas danza Querétaro", "", "", "", "Querétaro", "Querétaro", "Regional", "Ballet/jazz", "research"),
    L("Tiendas danza Mérida", "", "", "", "Mérida", "Yucatán", "Regional", "Ballet + folklor", "research"),
    L("Tiendas danza Tijuana", "", "", "", "Tijuana", "BC", "Regional", "Frontera", "research"),
    L("Tiendas danza Cancún", "", "", "", "Cancún", "Q. Roo", "Regional", "Turismo + escuelas", "research"),
    L("Tiendas danza Chihuahua", "", "", "", "Chihuahua", "Chihuahua", "Regional", "Norte", "research"),
    L("Tiendas danza Hermosillo", "", "", "", "Hermosillo", "Sonora", "Regional", "Noroeste", "research"),
    L("Tiendas danza Culiacán", "", "", "", "Culiacán", "Sinaloa", "Regional", "Noroeste", "research"),
    L("Tiendas danza Veracruz", "", "", "", "Veracruz", "Veracruz", "Regional", "Folklor jarocho + ballet", "research"),
    L("Tiendas danza Toluca", "", "", "", "Toluca", "EdoMex", "Regional", "Cerca Atenco", "research"),
    L("Tiendas danza Pachuca", "", "", "", "Pachuca", "Hidalgo", "Regional", "Escuelas", "research"),
    L("Tiendas danza Morelia", "", "", "", "Morelia", "Michoacán", "Regional", "Escuelas", "research"),
    L("Tiendas danza Tuxtla", "", "", "", "Tuxtla Gutiérrez", "Chiapas", "Regional", "Escuelas", "research"),
    L("Escuelas de ballet CDMX canal", "", "", "", "CDMX", "CDMX", "Canal B2B", "Compran calzado", "research"),
    L("Escuelas de ballet GDL canal", "", "", "", "Guadalajara", "Jalisco", "Canal B2B", "Fitting grupos", "research"),
    L("Escuelas folklor CDMX canal", "", "", "", "CDMX", "CDMX", "Canal B2B", "Manzano / Lagunilla", "research"),
    L("Compañías de danza institucionales", "", "", "", "México", "México", "Canal institucional", "INBAL / estatales", "research"),
    L("Mayoreo escuelas folklor Atenco", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Mayoreo escuelas", "Folklor", "research"),
    L("Mayoreo Lagunilla danza extra", "", "castrolopezamerica@icloud.com", "5539682121", "CDMX", "CDMX", "Mayoreo", "Ballet jazz huarache botín", "research"),
    L("Envíos nacionales ZA&ZA extra", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "México", "México", "Ecom", "Toda la República", "research"),
    L("Envío gratis Dance Field extra", "https://www.dancefield.com.mx/", "", "3343160899", "Guadalajara", "Jalisco", "Promo logística", ">$2500", "research"),
    L("Envío gratis Andanzza extra", "https://andanzza.com.mx/", "", "(55) 6155-8577", "CDMX", "CDMX", "Promo logística", ">$2000", "research"),
    L("Certificados de regalo Andanzza extra", "https://andanzza.com.mx/", "", "(55) 6155-8577", "CDMX", "CDMX", "Gift", "1500 MXN", "research"),
    L("Fitting profesional Pirouette extra", "https://www.pirouette.mx/", "tienda@pirouette.mx", "3336100291", "Zapopan", "Jalisco", "Servicio", "Puntas", "research"),
    L("Horario Manzano extra", "https://calzadomanzano.com/contacto/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Operación", "L-V 9-6 S 9-4", "research"),
    L("Pickup showroom Manzano extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Click & collect", "Compra en línea", "research"),
    L("Hecho en México Manzano extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Marca MX", "+20 años folklor", "research"),
    L("Hecho en México Bluëin extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Marca MX", "Diseño propio", "research"),
    L("Miguelito USA/MX extra", "https://miguelitousa.com/home.html", "", "", "CDMX", "CDMX", "Export", "Teatral", "research"),
    L("Kuali ML store extra", "https://listado.mercadolibre.com.mx/zapatos-flamenco-danza_Store_kuali-shoes", "", "", "México", "México", "Ecom ML", "Flamenco", "research"),
    L("ML zapatos danza sellers extra", "https://listado.mercadolibre.com.mx/zapatos-danza", "", "", "México", "México", "Marketplace", "Varios", "research"),
    L("Amazon MX dance shoes extra", "https://www.amazon.com.mx/s?k=zapatillas+ballet", "", "", "México", "México", "Marketplace", "Capezio import", "research"),
    L("Liverpool dancewear extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada", "brand"),
    L("Coppel zapatillas extra", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Precio", "brand"),
    L("Insumos suelas danza Atenco", "", "", "7282872026", "San Mateo Atenco", "EdoMex", "Insumo", "Tacones y suelas", "research"),
    L("Insumos clavos flamenco", "", "", "", "México", "México", "Insumo", "Taconeo", "research"),
    L("Resuela / reparación danza", "", "", "", "CDMX", "CDMX", "Servicio", "Puntas y folklor", "research"),
    L("Resuela GDL extra", "", "", "", "Guadalajara", "Jalisco", "Servicio", "Pirouette/Dance Field zona", "research"),
    L("Resuela MTY extra", "", "", "", "Monterrey", "NL", "Servicio", "ZA&ZA zona", "research"),
    L("Calcetas y protectores puntas extra", "", "", "", "México", "México", "Accesorio", "Retailers", "research"),
    L("Cinta elástica / listón extra", "", "", "", "México", "México", "Insumo", "Puntas", "research"),
    L("Bolsa porta zapatillas extra", "", "", "", "México", "México", "Accesorio", "Dancewear", "research"),
    L("Mochilas danza extra", "", "", "", "México", "México", "Accesorio", "ZA&ZA / Dance Field", "research"),
    L("Calentadores / warmup extra", "", "", "", "México", "México", "Indumentaria", "Retail", "research"),
    L("Zapatos character / teatro extra", "", "", "", "CDMX", "CDMX", "Teatro", "Miguelito", "research"),
    L("Zapatos de carácter español extra", "", "", "", "México", "México", "Español", "Flamenco adyacente", "research"),
    L("Zapatos sevillanas extra", "", "", "", "México", "México", "Sevillanas", "Retail flamenco", "research"),
    L("Zapatos de claqué mexicano extra", "", "", "", "México", "México", "Claqué", "Escuelas", "research"),
    L("Zapatos hip hop / urban dance extra", "", "", "", "México", "México", "Urban", "Sneakers danza", "research"),
    L("Dance sneakers Capezio extra", "", "", "", "México", "México", "Sneaker", "Retailers", "brand"),
    L("Split sole jazz extra", "", "", "", "México", "México", "Jazz", "Mayoreo escuelas", "research"),
    L("Footundeez / paws extra", "", "", "", "México", "México", "Contemporáneo", "Retail", "research"),
    L("Puntas de ensayo extra", "", "", "", "México", "México", "Ensayo", "Escuelas", "research"),
    L("Puntas de función extra", "", "", "", "México", "México", "Función", "Compañías", "research"),
    L("Tallas infantiles folklor extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Infantil", "Escuelas", "research"),
    L("Tallas infantiles ballet extra", "https://www.pirouette.mx/", "tienda@pirouette.mx", "3336100291", "Zapopan", "Jalisco", "Infantil", "Fitting", "research"),
    L("Tallas adultas folklor extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Adulto", "Grupos", "research"),
    L("Ancho especial / horma extra", "", "", "", "San Mateo Atenco", "EdoMex", "Custom", "Fábricas Atenco", "research"),
    L("Colores personalizados folklor extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Custom", "A juego con traje", "research"),
    L("Mayoreo grupos representativos extra", "", "", "", "México", "México", "B2B grupos", "Estados", "research"),
    L("Mayoreo universidades extra", "", "", "", "México", "México", "B2B uni", "Folklor universitario", "research"),
    L("Mayoreo casas de cultura extra", "", "", "", "México", "México", "B2G", "Municipios", "research"),
    L("Export folklor US extra", "https://miguelitousa.com/home.html", "", "", "CDMX", "CDMX", "Export", "Miguelito / Manzano", "research"),
    L("Cluster Atenco más talleres extra", "", "", "", "San Mateo Atenco", "EdoMex", "Cluster", "Calzado en general + danza", "research"),
    L("Barrio San Miguel Atenco extra", "", "", "", "San Mateo Atenco", "EdoMex", "Barrio fábricas", "Don León", "research"),
    L("Barrio Santiago Atenco extra", "https://calzadomanzano.com/", "", "7221016661", "San Mateo Atenco", "EdoMex", "Barrio", "Manzano", "research"),
    L("Barrio San Francisco Atenco extra", "", "", "7282874087", "San Mateo Atenco", "EdoMex", "Barrio", "Gonze But", "research"),
    L("Barrio San Juan Atenco extra", "", "", "7282882501", "San Mateo Atenco", "EdoMex", "Barrio", "Supllies", "research"),
    L("Barrio San Luquitas extra", "", "", "7282872026", "San Mateo Atenco", "EdoMex", "Barrio", "Tacones", "research"),
    L("Barrio La Magdalena extra", "", "", "7282880173", "San Mateo Atenco", "EdoMex", "Barrio", "Ital Group", "research"),
    L("Industria Norte Atenco extra", "", "", "", "San Mateo Atenco", "EdoMex", "Zona industrial", "Danzar", "research"),
    L("Blvd Miguel Alemán Atenco extra", "", "", "", "San Mateo Atenco", "EdoMex", "Corredor", "FASA", "research"),
    L("ZA&ZA +15 años extra", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "Monterrey", "NL", "Trayectoria", "Multimarca #1 MX", "research"),
    L("Dance Field líder GDL extra", "https://www.dancefield.com.mx/", "", "3343160899", "Guadalajara", "Jalisco", "Posicionamiento", "Líder occidente", "research"),
    L("Pirouette fitting GDL extra", "https://www.pirouette.mx/", "tienda@pirouette.mx", "3336100291", "Zapopan", "Jalisco", "Especialidad", "Calzado + fitting", "research"),
    L("Allegro Puebla extra", "https://allegro.mx/", "", "(222) 169-7869", "Puebla", "Puebla", "Regional", "Bloch/Grishko/Capezio", "research"),
    L("Andanzza CDMX extra", "https://andanzza.com.mx/", "", "(55) 6155-8577", "CDMX", "CDMX", "Ecom+tienda", "Nacional", "research"),
    L("Bluëin Del Valle extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Showroom", "Parroquia 637-2", "research"),
    L("Miguelito teatral extra", "https://miguelitousa.com/home.html", "", "", "CDMX", "CDMX", "Teatro", "Folklore+ballet+flamenco", "research"),
    L("Kuali flamenco extra", "", "", "", "México", "México", "Flamenco", "ML store", "research"),
    L("Capezio jazz extra", "", "", "", "México", "México", "Jazz", "Retailers", "brand"),
    L("Bloch ballet extra", "", "", "", "México", "México", "Ballet", "Retailers", "brand"),
    L("Grishko puntas extra", "", "", "", "México", "México", "Puntas", "Retailers", "brand"),
    L("Sansha jazz extra", "", "", "", "México", "México", "Jazz", "Retailers", "brand"),
    L("So Danca extra", "", "", "", "México", "México", "Indumentaria", "Retailers", "brand"),
    L("Wear Moi extra", "", "", "", "México", "México", "Mallas", "Retailers", "brand"),
    L("Gaynor Minden extra", "", "", "", "México", "México", "Puntas premium", "Pocas tiendas", "brand"),
    L("Freed extra", "", "", "", "México", "México", "Puntas premium", "Fitting", "brand"),
    L("Russian Pointe extra", "", "", "", "México", "México", "Puntas", "Retail", "brand"),
    L("Leo's extra", "", "", "", "México", "México", "Jazz/tap", "Retail", "brand"),
    L("Manzano folklor colores extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Catálogo", "Modelos folklor", "research"),
    L("ZA&ZA folklore línea extra", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "Monterrey", "NL", "Línea", "Folklore + heels + salsa", "research"),
    L("Dance Field unitardos extra", "https://www.dancefield.com.mx/", "", "3343160899", "Guadalajara", "Jalisco", "Indumentaria", "Complemento", "research"),
    L("Pirouette indumentaria extra", "https://www.pirouette.mx/", "tienda@pirouette.mx", "3336100291", "Zapopan", "Jalisco", "Indumentaria", "Ballet", "research"),
    L("Allegro Bloch Grishko Capezio extra", "https://allegro.mx/", "", "(222) 169-7869", "Puebla", "Puebla", "Multimarca", "Importados", "research"),
    L("WhatsApp ZA&ZA extra", "https://info.zazadancewear.com/", "contacto@zazadancewear.com", "5561371366", "México", "México", "Canal WA", "Consultas", "research"),
    L("WhatsApp Dance Field extra", "https://www.dancefield.com.mx/", "", "3323893706", "Guadalajara", "Jalisco", "Canal WA", "Pedidos", "research"),
    L("WhatsApp Andanzza extra", "https://andanzza.com.mx/", "", "(55) 6155-8577", "CDMX", "CDMX", "Canal WA", "Pedidos", "research"),
    L("WhatsApp Manzano extra", "https://calzadomanzano.com/", "hola@calzadomanzano.com", "7221016661", "San Mateo Atenco", "EdoMex", "Canal WA", "Cotización", "research"),
    L("WhatsApp Bluëin extra", "https://www.blueinshoes.com/", "", "5510082182", "CDMX", "CDMX", "Canal WA", "Pedidos", "research"),
    L("WhatsApp Lagunilla extra", "", "castrolopezamerica@icloud.com", "5539682121", "CDMX", "CDMX", "Canal WA", "Mayoreo", "research"),
    L("WhatsApp ZA&ZA Puebla/Oaxaca extra", "https://info.zazadancewear.com/", "", "5561894779", "Puebla", "Puebla", "Canal WA", "2 sucursales", "research"),
    L("WhatsApp Barbiboo extra", "", "", "8141883606", "Guadalupe", "NL", "Canal WA", "Punto ZA&ZA", "research"),
]


def main():
    print("Generating lotes 11-12…")
    dump("11", "trajes_tipicos", "Trajes típicos, charro, huipil y guayabera MX", TRAJES)
    dump("12", "zapatos_para_danza", "Calzado de danza: ballet, folklor, flamenco, jazz MX", DANZA)
    print(f"counts: 11={len(TRAJES)} 12={len(DANZA)}")


if __name__ == "__main__":
    main()
