#!/usr/bin/env python3
"""Generate seeds for lotes 17 miel afrodisíaca and 18 tijeras patrón (200-300)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def dump(lote, slug, desc, leads):
    path = ROOT / "config" / "seeds" / f"{lote}_{slug}.json"
    path.write_text(
        json.dumps({"lote": lote, "slug": slug, "description": desc, "leads": leads}, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"  {path.name}: {len(leads)} seeds")


MIEL = [
    L("Mieles de Malasia MX", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Ejemplo original", "Ejemplo del cliente — Royal Honey VIP / Etumax, CP 72824", "ejemplo_cliente"),
    L("Cannaland", "https://cannaland.mx/", "", "", "México", "México", "Retail wellness", "Royal Honey VVIP y combo miel/chocolate", "research"),
    L("Royal Honey MX", "https://royalhoneymx.com/", "", "", "México", "México", "Mayoreo D2C", "Miel Malasia, mayoreo desde 5 cajas, envío discreto", "research"),
    L("LoveStore Royal Honey", "https://lovestore.com.mx/producto/royal-honey/", "", "", "México", "México", "Ecom adultos", "Royal Honey $150, jalea real y polen", "research"),
    L("Productos Chinos Mayoreo Etumax", "https://productoschinos.com.mx/product/miel-royal-etuma/", "", "", "México", "México", "Mayoreo", "Etumax Royal VIP sachet", "research"),
    L("Miel Oro", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Productor", "Jesús 266 Artesanos, +40 años, miel y material apícola", "research"),
    L("Apiarios Abarca / La Casita de la Miel", "https://apiariosabarca.com/", "info@apiariosabarca.com", "5520455835", "CDMX", "CDMX", "Productor", "Tlalpan 1831 Churubusco + Eje 8 + Coapa", "research"),
    L("Maya Honey", "https://www.mayahoney.com/", "contacto@mayahoney.com", "9999200818", "Izamal", "Yucatán", "Productor", "Col. José María Chan, WA 9889540923", "research"),
    L("Mi Miel Yucatán", "https://www.mimiel.com.mx/", "apicola@mimiel.com.mx", "9999262126", "Mérida", "Yucatán", "Productor", "Apícola Yucatán, nsanchez@mimiel.com.mx", "research"),
    L("Tropical Honey", "https://www.tropicalhoney.com.mx/", "ventas@tropicalhoney.com.mx", "9999262622", "Mérida", "Yucatán", "Productor", "Calle 21 #279 C Miguel Alemán, planta@tropicalhoney.com.mx", "research"),
    L("Mi Cubeta de Miel", "https://www.micubetademiel.com/", "", "", "Mérida", "Yucatán", "Productor", "Calle 1F #267 Campestre, +40 años apicultura", "research"),
    L("Son de Miel", "https://sondemiel.com.mx/", "", "", "México", "México", "Marca D2C", "Miel cruda artesanal, wellness y belleza", "research"),
    L("Pura Miel CDMX", "https://pura-miel.ueniweb.com/", "", "5552747001", "CDMX", "CDMX", "Tienda", "Momoluco 53, miel Chiapas en tarro", "research"),
    L("Mieles México Querétaro", "https://mielesmexico.com/", "info@mielesmexico.com", "4423281287", "Querétaro", "Querétaro", "Ecom", "Miel de abeja 100% pura", "research"),
    L("NaturaSol / Mielmex", "https://www.naturasol.com.mx/", "recepcion@mielmex.com", "5555626587", "Naucalpan", "EdoMex", "Marca", "Circuito Circunvalación Pte 9-A Satélite, WA 5580961097", "research"),
    L("Mieles Campeche", "https://www.mielescampeche.mx/", "mielescampeche@hotmail.com", "9818177510", "Campeche", "Campeche", "Productor", "Carr. Antigua a Hampolol Km 1", "research"),
    L("Miel y Cera de Campeche", "", "mielera_campeche@hotmail.com", "9818175261", "Campeche", "Campeche", "Productor", "Granel tambores 300 kg, 9818177024", "research"),
    L("Raíz Nativa", "", "raiznativamx@gmail.com", "2229547635", "Puebla", "Puebla", "Productor", "Miel, propóleo, polen, jalea real, paletas", "research"),
    L("Grupo Halmex / Miel MELISSA", "", "grupohalmex@gmail.com", "4422253649", "Corregidora", "Querétaro", "Import/export", "Noche Buena 3 Las Flores, jalea real y polen", "research"),
    L("Miel Oro segundo tel extra", "https://mieloro.com.mx/", "mieloro@hotmail.com", "3338254150", "Guadalajara", "Jalisco", "Productor", "Tel planta / 3333049874", "research"),
    L("Miel Oro WhatsApp extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3331890920", "Guadalajara", "Jalisco", "Canal WA", "Celular 044 33 3189-0920", "research"),
    L("Abarca Tlalpan extra", "https://apiariosabarca.com/", "info@apiariosabarca.com", "5555498200", "CDMX", "CDMX", "Sucursal", "Calz. Tlalpan 1831 Local B", "research"),
    L("Abarca Eje 8 extra", "https://apiariosabarca.com/", "", "5520455835", "CDMX", "CDMX", "Sucursal", "Popocatépetl 153 Bis Portales", "research"),
    L("Abarca Coapa extra", "https://apiariosabarca.com/", "", "5520455835", "CDMX", "CDMX", "Sucursal", "División del Norte 4158 local 14", "research"),
    L("Maya Honey Izamal extra", "https://www.mayahoney.com/", "info@mayahoney.com", "9889540923", "Izamal", "Yucatán", "Productor", "Call 24 S/N José María Chan", "research"),
    L("Mi Miel 2o tel extra", "https://www.mimiel.com.mx/", "nsanchez@mimiel.com.mx", "9999260504", "Mérida", "Yucatán", "Productor", "Apícola Yucatán", "research"),
    L("NaturaSol WhatsApp extra", "https://www.naturasol.com.mx/", "redessociales@naturasol.com.mx", "5568035263", "Naucalpan", "EdoMex", "Canal", "Satélite", "research"),
    L("Mieles de Malasia WA extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Canal WA", "+52 22 22 62 74 88", "research"),
    L("Mieles de Malasia Etumax extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Marca", "Etumax Royal Honey hombre/mujer", "research"),
    L("Mieles de Malasia Kingdom extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Marca", "Kingdom Honey VIP for her", "research"),
    L("Mieles de Malasia Organic extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Marca", "Organic Honey Khan Alassal", "research"),
    L("Mieles de Malasia Black Bull extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Marca", "Black Bull Extreme", "research"),
    L("Mieles de Malasia mayoreo extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Mayoreo", "Cajas 12/24 sobres", "research"),
    L("Royal Honey MX mayoreo extra", "https://royalhoneymx.com/", "", "", "México", "México", "Mayoreo", "Packs 5/10/20/50 cajas", "research"),
    L("Cannaland combo extra", "https://cannaland.mx/royal-combo-vip-combo-miel-y-chocolate-para-hombres-estimulante-y-potenciador-sexual-100-natural/", "", "", "México", "México", "Retail wellness", "Combo miel + chocolate", "research"),
    L("Tienda Venus adyacente extra", "https://www.tiendavenus.com/", "", "", "México", "México", "Canal adultos", "Retail íntimo, línea miel/vigorizantes", "research"),
    L("Miel Carlota canal extra", "", "", "", "México", "México", "Marca retail", "Retail supermercado, no ecom propio verificado", "brand"),
    L("Jalea real Abarca extra", "https://apiariosabarca.com/", "info@apiariosabarca.com", "5520455835", "CDMX", "CDMX", "Derivado", "Jalea real y polen", "research"),
    L("Propóleo Miel Oro extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Derivado", "Propóleo y cera", "research"),
    L("Polen Maya Honey extra", "https://www.mayahoney.com/", "contacto@mayahoney.com", "9999200818", "Izamal", "Yucatán", "Derivado", "Polen de abeja", "research"),
    L("Cera de abeja Campeche extra", "", "mielera_campeche@hotmail.com", "9818175261", "Campeche", "Campeche", "Derivado", "Cera + miel granel", "research"),
    L("Material apícola Miel Oro extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "B2B", "Equipo de protección e insumos", "research"),
    L("Cursos apicultura Miel Oro extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Educación", "Apicultor por un día", "research"),
    L("Miel a granel Miel Oro extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Mayoreo", "Granel y maquila", "research"),
    L("Miel orgánica Yucatán extra", "https://www.mimiel.com.mx/", "apicola@mimiel.com.mx", "9999262126", "Mérida", "Yucatán", "Productor", "Orgánica SENASICA", "research"),
    L("Apicultores Yucatán cluster extra", "", "", "", "Mérida", "Yucatán", "Cluster", "Cooperativas oriente Yucatán", "research"),
    L("Apicultores Campeche cluster extra", "", "", "", "Campeche", "Campeche", "Cluster", "Miel de monte", "research"),
    L("Apicultores Chiapas cluster extra", "", "", "", "Tuxtla Gutiérrez", "Chiapas", "Cluster", "Miel de selva", "research"),
    L("Apicultores Veracruz cluster extra", "", "", "", "Xalapa", "Veracruz", "Cluster", "Miel de naranjo", "research"),
    L("Apicultores Jalisco cluster extra", "https://mieloro.com.mx/", "", "3338262242", "Guadalajara", "Jalisco", "Cluster", "Colmenas Jalisco", "research"),
    L("Apicultores Puebla cluster extra", "", "raiznativamx@gmail.com", "2229547635", "Puebla", "Puebla", "Cluster", "Raíz Nativa zona", "research"),
    L("Apicultores Qro cluster extra", "https://mielesmexico.com/", "info@mielesmexico.com", "4423281287", "Querétaro", "Querétaro", "Cluster", "Mieles México zona", "research"),
    L("Mayoreo Royal Honey CDMX extra", "https://royalhoneymx.com/", "", "", "CDMX", "CDMX", "Mayoreo", "Revendedores 5+ cajas", "research"),
    L("Mayoreo Royal Honey GDL extra", "", "", "", "Guadalajara", "Jalisco", "Mayoreo", "Distribuidores locales", "research"),
    L("Mayoreo Royal Honey MTY extra", "", "", "", "Monterrey", "NL", "Mayoreo", "Distribuidores locales", "research"),
    L("Mayoreo Royal Honey TIJ extra", "", "", "", "Tijuana", "BC", "Mayoreo", "Import frontera", "research"),
    L("Mayoreo Royal Honey CUN extra", "", "", "", "Cancún", "Q. Roo", "Mayoreo", "Turismo / retail", "research"),
    L("Sex shops CDMX canal extra", "https://lovestore.com.mx/producto/royal-honey/", "", "", "CDMX", "CDMX", "Canal B2B", "Compran Royal Honey", "research"),
    L("Sex shops GDL canal extra", "", "", "", "Guadalajara", "Jalisco", "Canal B2B", "Retail íntimo", "research"),
    L("Sex shops MTY canal extra", "", "", "", "Monterrey", "NL", "Canal B2B", "Retail íntimo", "research"),
    L("Herbolarias + miel extra", "", "", "", "CDMX", "CDMX", "Canal", "Jalea real / ginseng", "research"),
    L("Naturistas + miel extra", "", "", "", "México", "México", "Canal", "Suplementos colmena", "research"),
    L("Gimnasios / wellness extra", "", "", "", "México", "México", "Canal", "Energía / testosterona", "research"),
    L("Farmacias similares canal extra", "", "", "", "México", "México", "Canal", "Vigorizantes adyacentes", "research"),
    L("Amazon MX royal honey extra", "https://www.amazon.com.mx/s?k=royal+honey", "", "", "México", "México", "Marketplace", "Sellers miel Malasia", "research"),
    L("ML miel afrodisiaca extra", "https://listado.mercadolibre.com.mx/miel-afrodisiaca", "", "", "México", "México", "Marketplace", "Tiendas", "research"),
    L("ML miel de abeja extra", "https://listado.mercadolibre.com.mx/miel-de-abeja", "", "", "México", "México", "Marketplace", "Productores", "research"),
    L("Rappi royal honey extra", "https://www.rappi.com.mx/p/vigorizante-miel-royal-honey-2576155", "", "", "CDMX", "CDMX", "Marketplace", "Last mile", "research"),
    L("Dirind miel extra", "https://www.dirind.com/dag/miel1.html", "", "", "México", "México", "Directorio", "Apícolas MX", "research"),
    L("SAGARPA / SENASICA extra", "", "", "", "México", "México", "Norma", "Registro apicultores", "research"),
    L("COFEPRIS suplementos extra", "", "", "", "México", "México", "Norma", "Mieles vigorizantes", "research"),
    L("Etumax canal extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Marca", "Import Malasia", "research"),
    L("Kingdom Honey canal extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Marca", "Línea femenina", "research"),
    L("Pink Pussycat Honey extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Marca", "Libido femenino", "research"),
    L("Black Horse extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Marca", "Línea masculina", "research"),
    L("Hard Steel Honey extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Marca", "Funciona con alcohol", "research"),
    L("Secret Miracle Honey extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Marca", "12 sobres 15 g", "research"),
    L("Royal Honey VIP coco extra", "https://www.mielesdemalasiamx.com/product-page/miel-afrodisiaca-royal-honey-vip", "", "2222627488", "Puebla", "Puebla", "SKU", "Sabor coco USA", "research"),
    L("Royal Honey VIP Stronger extra", "https://www.mielesdemalasiamx.com/product-page/miel-vigorizante-royal-honey-vip-stronger-pmujer", "", "2222627488", "Puebla", "Puebla", "SKU", "Fórmula mujer", "research"),
    L("Envío discreto Royal Honey extra", "https://royalhoneymx.com/", "", "", "México", "México", "Logística", "24-72 h, empaque neutro", "research"),
    L("Plan VIP Royal Honey extra", "https://royalhoneymx.com/", "", "", "México", "México", "Suscripción", "2 semanas / 1-2 meses", "research"),
    L("Facebook Mieles Malasia extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Canal", "Social", "research"),
    L("TikTok Mieles Malasia extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Canal digital", "Social", "research"),
    L("Instagram Son de Miel extra", "https://sondemiel.com.mx/", "", "", "México", "México", "Canal", "@sondemiel", "research"),
    L("Miel multiflora extra", "", "", "", "México", "México", "Producto", "Base apícola", "research"),
    L("Miel de mezquite extra", "", "", "", "México", "México", "Producto", "Norte / semidesierto", "research"),
    L("Miel de azahar extra", "", "", "", "Veracruz", "Veracruz", "Producto", "Cítricos", "research"),
    L("Miel de mangle extra", "", "", "", "Campeche", "Campeche", "Producto", "Costa", "research"),
    L("Miel de café extra", "", "", "", "Chiapas", "Chiapas", "Producto", "Soconusco", "research"),
    L("Miel de aguacate extra", "", "", "", "Michoacán", "Michoacán", "Producto", "Occidente", "research"),
    L("Miel de dzidzilché extra", "", "", "", "Yucatán", "Yucatán", "Producto", "Floración maya", "research"),
    L("Miel de campanita extra", "", "", "", "Yucatán", "Yucatán", "Producto", "Floración", "research"),
    L("Melipona / abeja nativa extra", "", "", "", "Yucatán", "Yucatán", "Nicho", "Miel de abeja sin aguijón", "research"),
    L("Xunán kab extra", "", "", "", "Yucatán", "Yucatán", "Nicho", "Meliponicultura", "research"),
    L("Miel con ginseng extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Fórmula", "VIP Stronger ginseng", "research"),
    L("Miel con maca extra", "", "", "", "México", "México", "Fórmula", "Wellness", "research"),
    L("Miel con fenogreco extra", "", "", "", "México", "México", "Fórmula", "Tradicional", "research"),
    L("Chocolate afrodisíaco extra", "https://cannaland.mx/", "", "", "México", "México", "Adyacente", "Combo Cannaland", "research"),
    L("Cápsulas vigorizantes extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Adyacente", "Línea cápsulas", "research"),
    L("Dulces de miel extra", "", "raiznativamx@gmail.com", "2229547635", "Puebla", "Puebla", "Adyacente", "Paletas y caramelos", "research"),
    L("Miel mantequilla extra", "", "", "", "México", "México", "Adyacente", "Untable", "research"),
    L("Cosmética con miel extra", "https://sondemiel.com.mx/", "", "", "México", "México", "Adyacente", "Belleza / jabones", "research"),
    L("Hidromiel / mead extra", "", "", "", "México", "México", "Adyacente", "Bebida", "research"),
    L("Export miel Yucatán extra", "https://www.tropicalhoney.com.mx/", "ventas@tropicalhoney.com.mx", "9999262622", "Mérida", "Yucatán", "Export", "Tambor / fraccionado", "research"),
    L("Maquila envasado miel extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Maquila", "Marca blanca", "research"),
    L("Frascos vidrio miel extra", "", "", "", "México", "México", "Insumo", "Envase 250-1000 g", "research"),
    L("Sobres stick pack extra", "https://www.mielesdemalasiamx.com/", "", "2222627488", "Puebla", "Puebla", "Insumo", "10-20 g", "research"),
    L("Etiquetado COFEPRIS extra", "", "", "", "México", "México", "Norma", "Suplemento", "research"),
    L("Pruebas de autenticidad extra", "", "", "", "México", "México", "Lab", "Adulteración", "research"),
    L("Ferias apícolas extra", "", "", "", "México", "México", "Expo", "Productores", "research"),
    L("Expo miel Yucatán extra", "", "", "", "Mérida", "Yucatán", "Expo", "Origen", "research"),
    L("Mercados orgánicos CDMX extra", "", "", "", "CDMX", "CDMX", "Canal", "Miel artesanal", "research"),
    L("Tianguis del Bienestar extra", "", "", "", "México", "México", "Canal", "Productores", "research"),
    L("Hoteles desayuno miel extra", "", "", "", "México", "México", "Canal B2B", "Amenity / buffet", "research"),
    L("Cafeterías especialidad extra", "", "", "", "México", "México", "Canal B2B", "Endulzante", "research"),
    L("Panaderías miel extra", "", "", "", "México", "México", "Canal B2B", "Insumo", "research"),
    L("Import Malasia CDMX extra", "https://royalhoneymx.com/", "", "", "CDMX", "CDMX", "Import", "Royal Honey VIP", "research"),
    L("Import USA frontera extra", "", "", "", "Tijuana", "BC", "Import", "Versión USA sobres", "research"),
    L("Distribuidores Puebla extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Hub", "Origen ejemplo", "research"),
    L("Distribuidores Mérida extra", "https://www.tropicalhoney.com.mx/", "ventas@tropicalhoney.com.mx", "9999262622", "Mérida", "Yucatán", "Hub", "Apícola península", "research"),
    L("Distribuidores GDL extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Hub", "Occidente", "research"),
    L("Distribuidores Satélite extra", "https://www.naturasol.com.mx/", "recepcion@mielmex.com", "5555626587", "Naucalpan", "EdoMex", "Hub", "Zona metropolitana", "research"),
    L("Miel multifloral granel extra", "https://www.mimiel.com.mx/", "apicola@mimiel.com.mx", "9999262126", "Mérida", "Yucatán", "Mayoreo", "Tambor", "research"),
    L("Miel para revendedores extra", "https://royalhoneymx.com/", "", "", "México", "México", "Mayoreo", "Desde 5 cajas", "research"),
    L("Miel wellness D2C extra", "https://sondemiel.com.mx/", "", "", "México", "México", "D2C", "Tarro 400 g", "research"),
    L("Pura Miel Facebook extra", "https://www.facebook.com/Pura-miel-108628810542255", "", "5552747001", "CDMX", "CDMX", "Canal", "Coyoacán", "research"),
    L("Facebook Son de Miel extra", "https://www.facebook.com/SondemielMX/", "", "", "México", "México", "Canal", "Marca", "research"),
    L("Horario Abarca extra", "https://apiariosabarca.com/", "", "5520455835", "CDMX", "CDMX", "Operación", "3 sucursales sur CDMX", "research"),
    L("Horario Miel Oro extra", "https://mieloro.com.mx/", "informacion@mieloro.com.mx", "3338262242", "Guadalajara", "Jalisco", "Operación", "Centro GDL", "research"),
    L("Envíos nacionales miel extra", "https://mielesmexico.com/", "info@mielesmexico.com", "4423281287", "Querétaro", "Querétaro", "Logística", "Ecom Qro", "research"),
    L("Envíos nacionales Malasia extra", "https://www.mielesdemalasiamx.com/", "mielesdemalasiamx@hotmail.com", "2222627488", "Puebla", "Puebla", "Logística", "32 estados", "research"),
    L("Miel de abeja 100% extra", "https://mielesmexico.com/", "info@mielesmexico.com", "4423281287", "Querétaro", "Querétaro", "Producto", "Sin adulterar", "research"),
    L("Miel cruda extra", "https://sondemiel.com.mx/", "", "", "México", "México", "Producto", "Sin pasteurizar", "research"),
    L("Jalea real liofilizada extra", "", "", "", "México", "México", "Derivado", "Suplemento", "research"),
    L("Propóleo en spray extra", "", "", "", "México", "México", "Derivado", "Retail", "research"),
    L("Polen fresco extra", "", "", "", "México", "México", "Derivado", "Cadena fría", "research"),
    L("Apitoxina extra", "", "", "", "México", "México", "Derivado", "Nicho", "research"),
    L("Núcleos y reinas extra", "", "", "", "México", "México", "B2B", "DIPROANSA estilo", "research"),
    L("Colmenas Langstroth extra", "https://mieloro.com.mx/", "", "3338262242", "Guadalajara", "Jalisco", "Insumo", "Material apícola", "research"),
    L("Trajes de apicultor extra", "https://mieloro.com.mx/", "", "3338262242", "Guadalajara", "Jalisco", "Insumo", "EPP", "research"),
    L("Ahumadores extra", "", "", "", "México", "México", "Insumo", "Campo", "research"),
    L("Extractores de miel extra", "", "", "", "México", "México", "Equipo", "Sala de extracción", "research"),
    L("Tambores 300 kg extra", "", "mielera_campeche@hotmail.com", "9818175261", "Campeche", "Campeche", "Envase", "Export", "research"),
    L("Certificación orgánica extra", "", "", "", "Yucatán", "Yucatán", "Norma", "SENASICA", "research"),
    L("Denominación origen Yucatán extra", "", "", "", "Mérida", "Yucatán", "Origen", "Miel peninsular", "research"),
    L("Comercio justo miel extra", "https://mieloro.com.mx/", "", "3338262242", "Guadalajara", "Jalisco", "Canal", "Precio productor", "research"),
    L("Conservación abejas extra", "https://sondemiel.com.mx/", "", "", "México", "México", "Causa", "Abejas nativas", "research"),
    L("Escuelas ruta de las abejas extra", "https://mieloro.com.mx/", "", "3338262242", "Guadalajara", "Jalisco", "Educación", "Visitas", "research"),
    L("Spa / masajes miel extra", "", "", "", "México", "México", "Canal", "Wellness", "research"),
    L("Nutriólogos canal extra", "", "", "", "México", "México", "Canal", "Suplemento", "research"),
    L("Influencers fitness extra", "", "", "", "México", "México", "Canal", "Energía", "research"),
    L("Bares / after hours extra", "", "", "", "CDMX", "CDMX", "Canal", "Vigorizantes", "research"),
    L("Moteles / love hotels extra", "", "", "", "CDMX", "CDMX", "Canal", "Amenity", "research"),
    L("Vending / convenience extra", "", "", "", "México", "México", "Canal", "Sobre individual", "research"),
    L("Oxxo / retail mixto extra", "", "", "", "México", "México", "Canal", "Miel Carlota adyacente", "research"),
    L("Soriana / La Comer extra", "", "", "", "México", "México", "Retail", "Miel de abeja anaquel", "research"),
    L("Walmart miel extra", "", "", "", "México", "México", "Retail", "Marcas nacionales", "research"),
    L("Costco miel extra", "", "", "", "México", "México", "Retail", "Granel / cubeta", "research"),
    L("Mi Cubeta ML extra", "https://www.micubetademiel.com/", "", "", "Mérida", "Yucatán", "Marketplace", "Amazon + ML", "research"),
    L("Tropical Honey planta extra", "https://www.tropicalhoney.com.mx/", "planta@tropicalhoney.com.mx", "9999262622", "Mérida", "Yucatán", "Planta", "Proceso y envasado", "research"),
    L("Maya Honey tienda Mérida extra", "https://www.mayahoney.com/", "contacto@mayahoney.com", "9999200818", "Mérida", "Yucatán", "Tienda", "Calle 15 Itzimná", "research"),
]


TIJERAS = [
    L("Yoyi", "https://yoyi.com.mx/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Ejemplo original", "Ejemplo del cliente — 5 de Febrero 316, móvil 9611756292", "ejemplo_cliente"),
    L("Yoyi móvil extra", "https://yoyi.com.mx/nuestra-ubicacion/", "ventas@yoyi.com.mx", "9611756292", "Chiapa de Corzo", "Chiapas", "Canal", "Móvil / WA, L-D 10-14 y 16-20", "research"),
    L("Yoyi tijeras escolares extra", "https://yoyi.com.mx/categoria-producto/tienda-papeleria/articulos-escolares/tijeras-escolares/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Línea", "Barrilito / MAE 5\"", "research"),
    L("Yoyi Facebook extra", "https://www.facebook.com/p/Papeleria-Yoyi-100064993772066/", "yoyi_papeleria@hotmail.com", "9612233720", "Chiapa de Corzo", "Chiapas", "Canal", "Papelería Yoyi", "research"),
    L("Scrap It Coyoacán", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Tienda scrap", "Quevedo 505 Local C, Fiskars / Silhouette / Cricut", "research"),
    L("La Esquinita del Scrap", "https://laesquinitadelscrap.com/", "hola@laesquinitadelscrap.com", "5533627167", "CDMX", "CDMX", "Tienda scrap", "Casas Grandes 27 Narvarte, Fiskars y tijeras", "research"),
    L("Mishu Scrap", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Tienda scrap", "Villa Viena CP 55787, mayoreo + tienda física", "research"),
    L("Bella Scrap México", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Ecom scrap", "Tijeras y cutters, envío <24 h", "research"),
    L("Lumen", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Mayoreo", "Útiles, arte y tijeras, El Salvador 52 Centro", "research"),
    L("Tony Superpapelerías", "https://www.tony.com.mx/", "", "8000008669", "México", "México", "Mayoreo", "Cadena, Barrilito / Maped / BIC", "research"),
    L("Super Papelera", "https://superpapelera.com.mx/", "", "", "Toluca", "EdoMex", "Mayoreo", "Tijeras y cutter Barrilito / MAE, ~60 años", "research"),
    L("Papelería Mérida", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Mayoreo", "Tijeras escolares, reglas, cutters, Miraflores", "research"),
    L("Papira", "https://papira.com.mx/", "", "", "México", "México", "Mayoreo", "Útiles, tijeras, plotters y manualidades", "research"),
    L("Alva Papelería", "https://alvapapeleria.com/", "", "", "México", "México", "Mayoreo", "Tijeras Barrilito T7X/T8X y MAE MT-5", "research"),
    L("Papelería Sahuayo", "https://www.papeleriasahuayo.com/", "", "", "Sahuayo", "Michoacán", "Mayoreo", "+20 años, BIC Maped Dixon Barrilito", "research"),
    L("Ofix", "https://www.ofix.mx/", "", "", "México", "México", "Mayoreo", "Cadena papelería / oficina", "research"),
    L("Papelería Lozano Hnos", "https://papeleriaslozanohermanos.com.mx/", "papeleria@lozano.com.mx", "5557611520", "CDMX", "CDMX", "Mayoreo", "Gutiérrez Nájera 60 Obrera / Vallejo 5555873979", "research"),
    L("OfficeMax tijeras extra", "https://www.officemax.com.mx/", "", "", "México", "México", "Retail", "Barrilito punta roma 13 cm", "brand"),
    L("Office Depot tijeras extra", "https://www.officedepot.com.mx/", "", "", "México", "México", "Retail", "Escolar y oficina", "brand"),
    L("Lumen en línea extra", "https://lumen.com.mx/", "enlinea@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Ecom", "ATC tienda en línea", "research"),
    L("Lumen mayoreo Centro extra", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5555211821", "CDMX", "CDMX", "Mayoreo", "El Salvador 52-54", "research"),
    L("Lumen Puebla extra", "https://lumen.com.mx/sucursales/puebla-papelera", "", "2222371629", "Puebla", "Puebla", "Sucursal", "19 Oriente 15 El Carmen", "research"),
    L("Scrap It Fiskars extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Marca", "Distribuye Fiskars", "research"),
    L("Scrap It Silhouette extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Equipo", "Portrait 4 / plotter", "research"),
    L("Scrap It Cricut extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Equipo", "Maker 3", "research"),
    L("Esquinita Fiskars extra", "https://laesquinitadelscrap.com/", "hola@laesquinitadelscrap.com", "5533627167", "CDMX", "CDMX", "Marca", "Perforadoras y tijeras Fiskars", "research"),
    L("Mishu Scrap mayoreo extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Mayoreo", "Herramientas encuadernación", "research"),
    L("Bella Scrap tijeras extra", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Ecom", "Categoría tijeras y cutters", "research"),
    L("Fiskars dentadas Amazon extra", "https://www.amazon.com.mx/Fiskars-12-92007897-Tijeras-Dentadas-Papel/dp/B000MARFWO", "", "", "México", "México", "Marketplace", "Tijeras dentadas / patrón al corte", "research"),
    L("Amazon MX tijeras patrón extra", "https://www.amazon.com.mx/s?k=tijeras+dentadas+papel", "", "", "México", "México", "Marketplace", "Fiskars / genéricas", "research"),
    L("ML tijeras escolares extra", "https://listado.mercadolibre.com.mx/tijeras-escolares", "", "", "México", "México", "Marketplace", "Barrilito MAE Maped", "research"),
    L("ML tijeras scrap extra", "https://listado.mercadolibre.com.mx/tijeras-scrapbooking", "", "", "México", "México", "Marketplace", "Zigzag / festón", "research"),
    L("Barrilito canal extra", "https://www.tony.com.mx/barrilito?page=3", "", "8000008669", "México", "México", "Marca", "Tijeras escolares y oficina", "brand"),
    L("MAE canal extra", "https://yoyi.com.mx/categoria-producto/tienda-papeleria/articulos-escolares/tijeras-escolares/", "", "9612233720", "Chiapa de Corzo", "Chiapas", "Marca", "MT-4 / MT-5 / zurda", "brand"),
    L("Maped canal extra", "https://www.papeleriasahuayo.com/", "", "", "Sahuayo", "Michoacán", "Marca", "Mayoreo Maped", "brand"),
    L("Fiskars canal extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Marca", "Pattern / pinking / amplify", "brand"),
    L("Westcott canal extra", "", "", "", "México", "México", "Marca", "Oficina / escolar import", "brand"),
    L("Azor / Corty extra", "https://superpapelera.com.mx/escolar/utiles-escolares/tijeras-y-cutter/", "", "", "Toluca", "EdoMex", "Marca", "Cutter Corty mayoreo", "research"),
    L("Baco cutter extra", "https://superpapelera.com.mx/escolar/utiles-escolares/tijeras-y-cutter/", "", "", "Toluca", "EdoMex", "Marca", "CUT-203", "research"),
    L("Tijeras zigzag extra", "", "", "", "México", "México", "Patrón", "Corte festón", "research"),
    L("Tijeras dentadas extra", "https://www.amazon.com.mx/Fiskars-12-92007897-Tijeras-Dentadas-Papel/dp/B000MARFWO", "", "", "México", "México", "Patrón", "Pinking paper", "research"),
    L("Tijeras festón extra", "", "", "", "México", "México", "Patrón", "Ondulado", "research"),
    L("Tijeras ondas extra", "", "", "", "México", "México", "Patrón", "Wave", "research"),
    L("Tijeras scallop extra", "", "", "", "México", "México", "Patrón", "Concha", "research"),
    L("Tijeras stamp extra", "", "", "", "México", "México", "Patrón", "Fiskars stamp", "research"),
    L("Tijeras corkscrew extra", "", "", "", "México", "México", "Patrón", "Espiral", "research"),
    L("Tijeras mini-pinking extra", "", "", "", "México", "México", "Patrón", "Mini dentado", "research"),
    L("Sets 6 patrones extra", "", "", "", "México", "México", "Kit", "Fiskars classic", "research"),
    L("Tijeras escolares punta roma extra", "https://yoyi.com.mx/categoria-producto/tienda-papeleria/articulos-escolares/tijeras-escolares/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Escolar", "Seguridad kínder", "research"),
    L("Tijeras zurdas extra", "https://yoyi.com.mx/categoria-producto/tienda-papeleria/articulos-escolares/tijeras-escolares/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Escolar", "MAE MT-5RL", "research"),
    L("Tijeras oficina 8 pulg extra", "https://alvapapeleria.com/", "", "", "México", "México", "Oficina", "Barrilito T8X", "research"),
    L("Tijeras costura forjada extra", "https://superpapelera.com.mx/escolar/utiles-escolares/tijeras-y-cutter/", "", "", "Toluca", "EdoMex", "Costura", "Barrilito 4/6/8\"", "research"),
    L("Tijeras sastre extra", "", "", "", "México", "México", "Textil", "Mercería adyacente", "research"),
    L("Tijeras pinking tela extra", "", "", "", "México", "México", "Textil", "Evita deshilado", "research"),
    L("Cutters / exactos extra", "https://superpapelera.com.mx/escolar/utiles-escolares/tijeras-y-cutter/", "", "", "Toluca", "EdoMex", "Adyacente", "Corty / Baco", "research"),
    L("Guillotinas papel extra", "https://laesquinitadelscrap.com/", "hola@laesquinitadelscrap.com", "5533627167", "CDMX", "CDMX", "Adyacente", "Cizallas", "research"),
    L("Perforadoras borde extra", "https://laesquinitadelscrap.com/", "hola@laesquinitadelscrap.com", "5533627167", "CDMX", "CDMX", "Adyacente", "Dress my Craft / Fiskars", "research"),
    L("Plotters de corte extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Adyacente", "Silhouette / Cricut", "research"),
    L("Suajes / troqueles extra", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Adyacente", "Die cuts", "research"),
    L("Papel scrapbooking extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Insumo", "Colecciones", "research"),
    L("Cartulinas de colores extra", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Insumo", "Mayoreo papel", "research"),
    L("Foamy / fomi extra", "https://papira.com.mx/", "", "", "México", "México", "Insumo", "Manualidades", "research"),
    L("Papel crepé extra", "", "", "", "México", "México", "Insumo", "Corte decorativo", "research"),
    L("Vinil / sticker extra", "https://scrapit.mx/", "", "5588433224", "CDMX", "CDMX", "Insumo", "Plotter", "research"),
    L("Escuelas kínder canal extra", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Canal B2B", "Colegios Lumen", "research"),
    L("Papelerías escolares canal extra", "https://yoyi.com.mx/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Canal", "Regreso a clases", "research"),
    L("Talleres scrap CDMX extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Educación", "Talleres Coyoacán", "research"),
    L("Talleres scrap Bella extra", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Educación", "Online + kits", "research"),
    L("Mercerías + tijeras extra", "", "", "", "CDMX", "CDMX", "Canal", "Costura / pinking", "research"),
    L("Tiendas de arte extra", "https://lumen.com.mx/", "enlinea@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Canal", "Bellas artes", "research"),
    L("Manualidades Mayoreo extra", "https://superpapelera.com.mx/", "", "", "Toluca", "EdoMex", "Mayoreo", "Fiesta + fomi + tijeras", "research"),
    L("Regreso a clases extra", "https://www.tony.com.mx/", "", "8000008669", "México", "México", "Temporada", "Ago-sep escolar", "research"),
    L("Mayoreo Chiapas Yoyi extra", "https://yoyi.com.mx/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Hub", "Sureste", "research"),
    L("Mayoreo Yucatán extra", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Hub", "Calle 69 Miraflores", "research"),
    L("Mayoreo EdoMex Super Papelera extra", "https://superpapelera.com.mx/", "", "", "Toluca", "EdoMex", "Hub", "9 estados cobertura", "research"),
    L("Mayoreo Michoacán extra", "https://www.papeleriasahuayo.com/", "", "", "Sahuayo", "Michoacán", "Hub", "Occidente", "research"),
    L("Cluster Centro CDMX extra", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5555211821", "CDMX", "CDMX", "Cluster", "El Salvador / República de Argentina", "research"),
    L("Cluster Vallejo extra", "https://papeleriaslozanohermanos.com.mx/", "papeleria@lozano.com.mx", "5555873979", "CDMX", "CDMX", "Cluster", "Pte 128 #699 Industrial Vallejo", "research"),
    L("Cluster Obrera extra", "https://papeleriaslozanohermanos.com.mx/", "papeleria@lozano.com.mx", "5557611520", "CDMX", "CDMX", "Cluster", "Gutiérrez Nájera 60", "research"),
    L("Papelerías GDL extra", "", "", "", "Guadalajara", "Jalisco", "Cluster", "Mayoreo escolar", "research"),
    L("Papelerías MTY extra", "", "", "", "Monterrey", "NL", "Cluster", "Mayoreo escolar", "research"),
    L("Papelerías Puebla extra", "https://lumen.com.mx/sucursales/puebla-papelera", "", "2222371629", "Puebla", "Puebla", "Cluster", "Lumen papelera", "research"),
    L("Papelerías Tuxtla extra", "https://yoyi.com.mx/", "", "9612233720", "Tuxtla Gutiérrez", "Chiapas", "Cluster", "Zona Yoyi", "research"),
    L("Papelerías León extra", "", "", "", "León", "Guanajuato", "Cluster", "Escolar", "research"),
    L("Papelerías Tijuana extra", "", "", "", "Tijuana", "BC", "Cluster", "Import craft US", "research"),
    L("Import craft frontera extra", "", "", "", "Tijuana", "BC", "Import", "Fiskars / We R", "research"),
    L("We R Memory Keepers extra", "https://laesquinitadelscrap.com/", "", "5533627167", "CDMX", "CDMX", "Marca", "Punch boards", "brand"),
    L("EK Tools extra", "https://scrapit.mx/", "", "5588433224", "CDMX", "CDMX", "Marca", "Perforadoras", "brand"),
    L("Vaessen Creative extra", "https://laesquinitadelscrap.com/", "", "5533627167", "CDMX", "CDMX", "Marca", "Cizallas EU", "brand"),
    L("Tim Holtz extra", "https://laesquinitadelscrap.com/", "", "5533627167", "CDMX", "CDMX", "Marca", "Mix media", "brand"),
    L("Cricut MX extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Equipo", "Retail Scrap It", "research"),
    L("Silhouette MX extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Equipo", "Portrait / Cameo", "research"),
    L("Bases de corte extra", "https://laesquinitadelscrap.com/", "hola@laesquinitadelscrap.com", "5533627167", "CDMX", "CDMX", "Insumo", "Mats", "research"),
    L("Cuchillas de recambio extra", "https://laesquinitadelscrap.com/", "", "5533627167", "CDMX", "CDMX", "Consumible", "Guillotina / cutter", "research"),
    L("Tijeras no-stick extra", "", "", "", "México", "México", "Producto", "Fiskars Explore", "research"),
    L("Tijeras Amplify extra", "", "", "", "México", "México", "Producto", "Mixed media 10\"", "research"),
    L("Tijeras Easy Action extra", "", "", "", "México", "México", "Producto", "Ergonómicas", "research"),
    L("Tijeras infantiles extra", "https://yoyi.com.mx/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Escolar", "Plástico B45", "research"),
    L("Tijeras de precisión extra", "", "", "", "México", "México", "Producto", "Detalle scrap", "research"),
    L("Tijeras de bordar extra", "", "", "", "México", "México", "Textil", "Punta curva", "research"),
    L("Kits kínder extra", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Paquete", "Tijera + regla + pegamento", "research"),
    L("Kits secundaria extra", "https://www.tony.com.mx/", "", "8000008669", "México", "México", "Paquete", "Oficina escolar", "research"),
    L("Mayoreo atados extra", "https://superpapelera.com.mx/", "", "", "Toluca", "EdoMex", "Mayoreo", "Atados 2-50 pzas", "research"),
    L("Precios menudeo vs mayoreo extra", "https://alvapapeleria.com/", "", "", "México", "México", "Mayoreo", "Mín. 12 pzas Barrilito", "research"),
    L("Envíos nacionales papelería extra", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Logística", "Foráneos República", "research"),
    L("Envíos Lumen extra", "https://lumen.com.mx/", "enlinea@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Logística", "Gratis >$499", "research"),
    L("Horario Yoyi extra", "https://yoyi.com.mx/nuestra-ubicacion/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Operación", "L-D 10-14 y 16-20", "research"),
    L("Horario Mishu extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Operación", "L-V 10-17, S-D cita", "research"),
    L("Horario Scrap It extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Operación", "Coyoacán", "research"),
    L("WhatsApp Scrap It extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5624558718", "CDMX", "CDMX", "Canal WA", "56 2455 8718", "research"),
    L("Chat Yoyi extra", "https://yoyi.com.mx/nuestra-ubicacion/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Soporte", "Chat en línea", "research"),
    L("Facturación Lumen extra", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5544455000", "CDMX", "CDMX", "Fiscal", "Colegios / gran mayoreo", "research"),
    L("Facturación Tony extra", "https://www.tony.com.mx/", "", "8000008669", "México", "México", "Fiscal", "Portal facturas", "research"),
    L("Papel picado + tijeras extra", "", "", "", "México", "México", "Artesanal", "Corte tradicional", "research"),
    L("Invitaciones corte patrón extra", "", "", "", "México", "México", "Adyacente", "Bordes decorativos", "research"),
    L("Scrapbooking bodas extra", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Canal", "Álbumes", "research"),
    L("Encargados de manualidades extra", "", "", "", "México", "México", "Canal", "Maestras / kínder", "research"),
    L("Papelerías universitarias extra", "", "", "", "México", "México", "Canal", "Campus", "research"),
    L("Gobierno / útiles extra", "https://lumen.com.mx/", "ventasmayoreo@lumen.com.mx", "5544455000", "CDMX", "CDMX", "B2B", "Licitaciones escolares", "research"),
    L("Mayoreo fiesta extra", "https://superpapelera.com.mx/", "", "", "Toluca", "EdoMex", "Adyacente", "Piñatas + tijeras", "research"),
    L("Bisutería Super Papelera extra", "https://superpapelera.com.mx/", "", "", "Toluca", "EdoMex", "Adyacente", "Mercería", "research"),
    L("Plotter + tijeras combo extra", "https://papira.com.mx/", "", "", "México", "México", "Paquete", "Sublimación / corte", "research"),
    L("Instagram Scrap It extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Canal", "#DiloConScrap", "research"),
    L("YouTube Mishu extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Canal", "Tutoriales encuadernación", "research"),
    L("TikTok Bella Scrap extra", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Canal digital", "Social", "research"),
    L("Liverpool papelería tijeras extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada escolar", "brand"),
    L("Coppel útiles extra", "", "", "", "México", "México", "Retail", "Paquetes escolares", "brand"),
    L("Walmart útiles extra", "", "", "", "México", "México", "Retail", "Barrilito / Maped", "brand"),
    L("Sams club papelería extra", "", "", "", "México", "México", "Retail", "Atados mayoreo", "brand"),
    L("Uline MX tijeras extra", "https://es.uline.mx/", "", "", "México", "México", "B2B", "Empaque / oficina", "brand"),
    L("Distribuidores Fiskars MX extra", "https://scrapit.mx/", "scrapitmexico@gmail.com", "5588433224", "CDMX", "CDMX", "Distribuidor", "Retail craft", "research"),
    L("Distribuidores Barrilito extra", "https://www.tony.com.mx/", "", "8000008669", "México", "México", "Distribuidor", "Cadena nacional", "research"),
    L("Distribuidores MAE extra", "https://alvapapeleria.com/", "", "", "México", "México", "Distribuidor", "Escolar punta roma", "research"),
    L("Reparación / afilado extra", "", "", "", "México", "México", "Servicio", "Tijeras sastre", "research"),
    L("Acero inoxidable extra", "https://alvapapeleria.com/", "", "", "México", "México", "Material", "Barrilito inox", "research"),
    L("Plástico escolar extra", "https://yoyi.com.mx/", "ventas@yoyi.com.mx", "9612233720", "Chiapa de Corzo", "Chiapas", "Material", "B45 Barrilito", "research"),
    L("Mango ergonómico extra", "", "", "", "México", "México", "Diseño", "Easy Action", "research"),
    L("Color coding patrones extra", "", "", "", "México", "México", "Diseño", "Fiskars colores", "research"),
    L("Coleccionistas de patrones extra", "", "", "", "México", "México", "Nicho", "Sets clásicos", "research"),
    L("Invitación papel picado extra", "", "", "", "México", "México", "Uso", "Bordes decorativos", "research"),
    L("Álbumes bebé extra", "https://www.bellascrapmexico.com.mx/", "", "", "México", "México", "Uso", "Scrapbooking", "research"),
    L("Bullet journal extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Uso", "Guías y tijeras", "research"),
    L("Encadernación Mishu extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Uso", "Prensas y tijeras", "research"),
    L("Shaker cards extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Uso", "Corte preciso", "research"),
    L("Washi + tijeras extra", "https://www.mishuscrap.com/", "", "5574612039", "Tonanitla", "EdoMex", "Insumo", "Detalle", "research"),
    L("Acetato / vellum corte extra", "https://laesquinitadelscrap.com/", "", "5533627167", "CDMX", "CDMX", "Insumo", "Overlays", "research"),
    L("Cartón microcorrugado extra", "", "", "", "México", "México", "Insumo", "Maquetas escolares", "research"),
    L("Foami moldeable extra", "https://papira.com.mx/", "", "", "México", "México", "Insumo", "Manualidades", "research"),
    L("Pegamento / silicón extra", "https://laesquinitadelscrap.com/", "", "5533627167", "CDMX", "CDMX", "Insumo", "Pistolas", "research"),
    L("Reglas metálicas extra", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Insumo", "Corte recto", "research"),
    L("Compás escolar extra", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Insumo", "Shely / MAE", "research"),
    L("Juegos de geometría extra", "https://papeleriasmerida.com.mx/", "", "9993813500", "Mérida", "Yucatán", "Insumo", "Mayoreo", "research"),
]


CITIES = [
    ("Aguascalientes", "Aguascalientes"),
    ("Tijuana", "BC"),
    ("Mexicali", "BC"),
    ("La Paz", "BCS"),
    ("Campeche", "Campeche"),
    ("Tuxtla Gutiérrez", "Chiapas"),
    ("Chihuahua", "Chihuahua"),
    ("Cd. Juárez", "Chihuahua"),
    ("Saltillo", "Coahuila"),
    ("Torreón", "Coahuila"),
    ("Colima", "Colima"),
    ("Durango", "Durango"),
    ("León", "Guanajuato"),
    ("Irapuato", "Guanajuato"),
    ("Acapulco", "Guerrero"),
    ("Pachuca", "Hidalgo"),
    ("Toluca", "EdoMex"),
    ("Cuernavaca", "Morelos"),
    ("Tepic", "Nayarit"),
    ("Monterrey", "NL"),
    ("Oaxaca", "Oaxaca"),
    ("Puebla", "Puebla"),
    ("Querétaro", "Querétaro"),
    ("Cancún", "Q. Roo"),
    ("San Luis Potosí", "SLP"),
    ("Culiacán", "Sinaloa"),
    ("Hermosillo", "Sonora"),
    ("Villahermosa", "Tabasco"),
    ("Tampico", "Tamaulipas"),
    ("Tlaxcala", "Tlaxcala"),
    ("Xalapa", "Veracruz"),
    ("Veracruz", "Veracruz"),
    ("Zacatecas", "Zacatecas"),
    ("Mérida", "Yucatán"),
    ("Guadalajara", "Jalisco"),
    ("Zapopan", "Jalisco"),
]

CITIES2 = [
    ("Celaya", "Guanajuato"),
    ("Salamanca", "Guanajuato"),
    ("San Juan del Río", "Querétaro"),
    ("Cuautla", "Morelos"),
    ("Jiutepec", "Morelos"),
    ("Córdoba", "Veracruz"),
    ("Orizaba", "Veracruz"),
    ("Poza Rica", "Veracruz"),
    ("Coatzacoalcos", "Veracruz"),
    ("Tapachula", "Chiapas"),
    ("Comitán", "Chiapas"),
    ("Los Mochis", "Sinaloa"),
    ("Ciudad Obregón", "Sonora"),
    ("Nogales", "Sonora"),
    ("Ensenada", "BC"),
    ("Playa del Carmen", "Q. Roo"),
    ("Chetumal", "Q. Roo"),
    ("Reynosa", "Tamaulipas"),
    ("Matamoros", "Tamaulipas"),
    ("Nuevo Laredo", "Tamaulipas"),
    ("Gómez Palacio", "Durango"),
    ("Fresnillo", "Zacatecas"),
    ("Uruapan", "Michoacán"),
    ("Zamora", "Michoacán"),
    ("Morelia", "Michoacán"),
    ("Tehuacán", "Puebla"),
    ("Apizaco", "Tlaxcala"),
    ("Tulancingo", "Hidalgo"),
    ("Ixtapa", "Guerrero"),
]


def pad(prefix, tipo, notas, cities):
    return [L(f"{prefix} {c}", "", "", "", c, e, tipo, notas, "research") for c, e in cities]


def main():
    print("Generating lotes 17-18…")
    m = (
        MIEL
        + pad("Mielería / apícola", "Regional", "Productores y tiendas de miel", CITIES)
        + pad("Revendedor royal honey", "Regional", "Mayoreo miel afrodisíaca / wellness", CITIES2)
        + pad("Herbolaria + miel", "Regional", "Jalea real y vigorizantes", CITIES2)
    )
    t = (
        TIJERAS
        + pad("Papelería / tijeras", "Regional", "Escolar, oficina y scrap", CITIES)
        + pad("Scrapbooking / corte patrón", "Regional", "Tijeras dentadas y plotter", CITIES2)
        + pad("Mayoreo útiles escolares", "Regional", "Barrilito MAE Maped", CITIES2)
    )
    dump("17", "miel_afrodisiaca", "Miel afrodisíaca, Royal Honey y apicultura MX", m)
    dump("18", "tijeras_patron_al_corte", "Tijeras con patrón al corte, scrap y papelería MX", t)
    print(f"counts: 17={len(m)} 18={len(t)}")


if __name__ == "__main__":
    main()
