#!/usr/bin/env python3
"""Generate seeds for lotes 13 sensoriales and 14 miniaturas (200-300)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def dump(lote, slug, desc, leads):
    path = ROOT / "config" / "seeds" / f"{lote}_{slug}.json"
    path.write_text(
        json.dumps({"lote": lote, "slug": slug, "description": desc, "leads": leads}, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"  {path.name}: {len(leads)} seeds")


SENS = [
    L("Coconini", "https://www.coconini.com.mx/", "", "", "México", "México", "Ejemplo original", "Ejemplo del cliente — juguetes sensoriales y libros", "ejemplo_cliente"),
    L("Mayoreo Didáctico", "https://www.mayoreodidactico.mx/", "monica@mayoreodidactico.mx", "8189891980", "Monterrey", "NL", "Mayoreo", "Sensoriales, antiestrés, envíos MX y USA — Zaragoza 410 Centro", "research"),
    L("XMajo Didácticos", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Retail educativo", "Montessori, TEA, Simón Bolívar Sur 127 Chepevera", "research"),
    L("Ideas Hands / Casa Didáctica", "https://www.ideashands.com.mx/", "ventas@casadidactica.com", "2222998488", "Querétaro", "Querétaro", "Fabricante/distribuidor", "Juguetes educativos, WhatsApp 7911131839", "research"),
    L("Grupo Educar", "https://grupoeducar.com.mx/", "", "5514036115", "CDMX", "CDMX", "Juguetes + mobiliario", "Fresno 133 Santa María la Ribera", "research"),
    L("Toys2Teach", "https://www.toys2teach.mx/", "", "5565854337", "CDMX", "CDMX", "Fábrica escolar", "Petén 555 Letrán Valle", "research"),
    L("Toiki mayoreo GDL", "https://toiki.mx/", "", "", "Guadalajara", "Jalisco", "Mayoreo juguetes", "#1 mayoreo ZMG", "research"),
    L("AIPAI Cositas", "https://aipaicositas.com/", "cositas.aipai@gmail.com", "5522657691", "Guadalajara", "Jalisco", "Montessori/Waldorf", "Alejandro 3296 Vallarta San Jorge", "research"),
    L("Teng Da Tepito", "", "", "", "CDMX", "CDMX", "Mayoreo centro", "Héroe de Granaditas 171 loc 47-50, desde 1 pza", "research"),
    L("BM Toys México", "", "", "", "CDMX", "CDMX", "Mayoreo", "Plaza Izazaga 89-748 y 151 PB-077, Colombia 78", "research"),
    L("Distribuidora Mesones juguetes", "", "", "5656770570", "CDMX", "CDMX", "Mayoreo económico", "Mesones 111-B, envíos >$2500", "research"),
    L("D'Toys", "http://www.dtoys.com.mx/", "", "", "Guadalajara", "Jalisco", "Mayoreo juguetes", "Distribuidor GDL cobertura nacional", "research"),
    L("Mayoreo Didáctico sucursal Zaragoza extra", "https://www.mayoreodidactico.com/", "monica@mayoreodidactico.mx", "8189891980", "Monterrey", "NL", "Sucursal", "Zaragoza Nte 410", "research"),
    L("XMajo TEA / neurodiversidad extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Línea TEA", "Regulación sensorial", "research"),
    L("XMajo Pikler extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Motricidad", "Triángulo Pikler", "research"),
    L("Coconini sensoriales extra", "https://www.coconini.com.mx/juguetes/", "", "", "México", "México", "Línea sensorial", "Desde $145", "research"),
    L("Grupo Educar Montessori extra", "https://grupoeducar.com.mx/productos/categoria/30/0/montessori", "", "(55) 2630-1194", "CDMX", "CDMX", "Línea Montessori", "CDMX", "research"),
    L("Toys2Teach mobiliario extra", "https://www.toys2teach.mx/", "", "5556049891", "CDMX", "CDMX", "Mobiliario escolar", "Benito Juárez", "research"),
    L("Pop-it / squishy Mayoreo Didáctico extra", "https://www.mayoreodidactico.mx/product-category/juguetes/juguetes-antiestres/", "", "", "Monterrey", "NL", "Antiestrés", "Mayoreo pieza", "research"),
    L("Columpio sensorial Mayoreo Didáctico extra", "https://www.mayoreodidactico.mx/", "", "", "Monterrey", "NL", "Equipo terapia", "Envíos USA", "research"),
    L("Slime / arena mágica mayoreo extra", "https://www.mayoreodidactico.mx/", "", "", "Monterrey", "NL", "Sensorial táctil", "Papelerías", "research"),
    L("Material Montessori madera extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Madera", "0-12 años", "research"),
    L("Neurogym XMajo extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Motricidad", "Estimulación", "research"),
    L("Libros apoyo TEA extra", "https://xmajodidacticos.com/", "", "8117537880", "Monterrey", "NL", "Libros", "Terapeutas", "research"),
    L("Waldorf madera AIPAI extra", "https://aipaicositas.com/", "cositas.aipai@gmail.com", "5522657691", "Guadalajara", "Jalisco", "Waldorf", "Sostenible", "research"),
    L("Mayoreo Tepito madera extra", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Teng Da", "research"),
    L("Mayoreo Izazaga juguetes extra", "", "", "", "CDMX", "CDMX", "Cluster centro", "BM Toys", "research"),
    L("Mayoreo Mesones extra", "", "", "5656770570", "CDMX", "CDMX", "Cluster centro", "Económico", "research"),
    L("Juguetes bebé sensoriales BM extra", "", "", "", "CDMX", "CDMX", "Bebé", "Estimulación", "research"),
    L("Fidget / pop-it escuelas extra", "", "", "", "México", "México", "Escolar", "Aula", "research"),
    L("Pelotas sensoriales terapia extra", "", "", "", "México", "México", "Terapia", "TO / SI", "research"),
    L("Chalecos de peso extra", "", "", "", "México", "México", "Terapia SI", "Regulación", "research"),
    L("Mantas de peso extra", "", "", "", "México", "México", "Terapia SI", "Propriocepción", "research"),
    L("Tubos y túneles sensoriales extra", "", "", "", "México", "México", "Motricidad", "Gimnasio SI", "research"),
    L("Piscina de pelotas terapia extra", "", "", "", "México", "México", "Gimnasio SI", "Clínicas", "research"),
    L("Paneles sensoriales pared extra", "", "", "", "México", "México", "Aula", "Preescolar", "research"),
    L("Mesas de luz Montessori extra", "", "", "", "México", "México", "Aula", "Reggio/Montessori", "research"),
    L("Arco Pikler / rampas extra", "", "", "", "México", "México", "Motricidad", "0-6", "research"),
    L("Cubos de actividades bebé extra", "", "", "", "México", "México", "Bebé", "Motricidad fina", "research"),
    L("Encajes y rompecabezas madera extra", "", "", "", "México", "México", "Cognitivo", "Preescolar", "research"),
    L("Instrumentos musicales infantiles extra", "", "", "", "México", "México", "Auditivo", "Estimulación", "research"),
    L("Texturas / cajas sensoriales extra", "", "", "", "México", "México", "Táctil", "Aula/terapia", "research"),
    L("Masilla terapéutica extra", "", "", "", "México", "México", "Táctil", "TO", "research"),
    L("Chewelry / mordedores extra", "", "", "", "México", "México", "Oral", "TEA", "research"),
    L("Auriculares noise-cancel kids extra", "", "", "", "México", "México", "Auditivo", "TEA", "research"),
    L("Gafas filtro sensorial extra", "", "", "", "México", "México", "Visual", "TEA", "research"),
    L("Temporizadores visuales extra", "", "", "", "México", "México", "Aula TEA", "Time Timer estilo", "research"),
    L("Pictogramas / PECS extra", "", "", "", "México", "México", "Comunicación", "TEA", "research"),
    L("Juguetes causa-efecto extra", "", "", "", "México", "México", "Cognitivo", "Estimulación temprana", "research"),
    L("STEM madera extra", "", "", "", "México", "México", "STEM", "Lógica", "research"),
    L("Mobiliario infantil Grupo Educar extra", "https://grupoeducar.com.mx/", "", "(55) 6724-0866", "CDMX", "CDMX", "Mobiliario", "Aulas", "research"),
    L("Mesas y sillas XMajo extra", "https://xmajodidacticos.com/", "", "8117537880", "Monterrey", "NL", "Mobiliario", "Aula", "research"),
    L("Decoración didáctica extra", "", "", "", "México", "México", "Aula", "Preescolar", "research"),
    L("Jugueterías didácticas CDMX cluster", "", "", "", "CDMX", "CDMX", "Cluster", "Coconini + Educar + Toys2Teach", "research"),
    L("Jugueterías didácticas MTY cluster", "", "", "", "Monterrey", "NL", "Cluster", "XMajo + Mayoreo Didáctico", "research"),
    L("Jugueterías didácticas GDL cluster", "", "", "", "Guadalajara", "Jalisco", "Cluster", "Toiki + AIPAI + D'Toys", "research"),
    L("Jugueterías didácticas Qro extra", "https://www.ideashands.com.mx/", "ventas@casadidactica.com", "2222998488", "Querétaro", "Querétaro", "Regional", "Casa Didáctica", "research"),
    L("Jugueterías didácticas Puebla extra", "", "", "", "Puebla", "Puebla", "Regional", "Escuelas", "research"),
    L("Jugueterías didácticas León extra", "", "", "", "León", "Guanajuato", "Regional", "Escuelas", "research"),
    L("Jugueterías didácticas Mérida extra", "", "", "", "Mérida", "Yucatán", "Regional", "Escuelas", "research"),
    L("Jugueterías didácticas Tijuana extra", "", "", "", "Tijuana", "BC", "Regional", "Frontera", "research"),
    L("Jugueterías didácticas Cancún extra", "", "", "", "Cancún", "Q. Roo", "Regional", "Turismo + escuelas", "research"),
    L("Terapeutas ocupacionales CDMX canal", "", "", "", "CDMX", "CDMX", "Canal B2B", "Compran material SI", "research"),
    L("Terapeutas ocupacionales MTY canal", "", "", "", "Monterrey", "NL", "Canal B2B", "XMajo zona", "research"),
    L("Terapeutas ocupacionales GDL canal", "", "", "", "Guadalajara", "Jalisco", "Canal B2B", "Clínicas", "research"),
    L("Clínicas TEA CDMX canal", "", "", "", "CDMX", "CDMX", "Canal clínico", "Material", "research"),
    L("Clínicas TEA MTY canal", "", "", "", "Monterrey", "NL", "Canal clínico", "Neurodiversidad", "research"),
    L("Escuelas Montessori CDMX canal", "", "", "", "CDMX", "CDMX", "Canal escolar", "Material oficial", "research"),
    L("Escuelas Montessori GDL canal", "", "", "", "Guadalajara", "Jalisco", "Canal escolar", "AIPAI zona", "research"),
    L("Escuelas Montessori MTY canal", "", "", "", "Monterrey", "NL", "Canal escolar", "XMajo zona", "research"),
    L("Preescolares públicos material extra", "", "", "", "México", "México", "Canal gobierno", "Licitación/compra", "research"),
    L("USAID / envíos USA Mayoreo Didáctico extra", "https://www.mayoreodidactico.mx/", "", "", "Monterrey", "NL", "Export", "Puerta a puerta", "research"),
    L("Papelerías sensoriales extra", "", "", "", "México", "México", "Canal papelería", "Squishy/slime", "research"),
    L("Farmacias / ortopedia kids extra", "", "", "", "México", "México", "Canal salud", "Ayudas técnicas", "research"),
    L("Amazon MX sensoriales extra", "https://www.amazon.com.mx/s?k=juguetes+sensoriales", "", "", "México", "México", "Marketplace", "Sellers MX", "research"),
    L("ML juguetes Montessori extra", "https://listado.mercadolibre.com.mx/juguetes-montessori", "", "", "México", "México", "Marketplace", "Tiendas", "research"),
    L("Liverpool juguetes educativos extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada", "brand"),
    L("Palacio juguetes diseño extra", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Diseño", "brand"),
    L("Coppel juguetes extra", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Volumen", "brand"),
    L("Walmart juguetes educativos extra", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Precio", "brand"),
    L("Costco juguetes extra", "https://www.costco.com.mx/", "", "", "México", "México", "Club", "Mayoreo cons", "brand"),
    L("Sam's juguetes extra", "https://www.sams.com.mx/", "", "", "México", "México", "Club", "Mayoreo", "brand"),
    L("Juguetibici extra", "", "", "", "México", "México", "Cadena", "Didácticos", "brand"),
    L("Julio Cepeda extra", "", "", "", "México", "México", "Cadena", "Juguetería", "brand"),
    L("Lumen didácticos extra", "https://www.lumen.com.mx/", "", "", "México", "México", "Papelería", "Material escolar", "brand"),
    L("Office Depot escolar extra", "https://www.officedepot.com.mx/", "", "", "México", "México", "Oficina/escolar", "Aula", "brand"),
    L("Importadores madera China-MX extra", "", "", "", "CDMX", "CDMX", "Import", "Tepito/Izazaga", "research"),
    L("Fábricas madera juguete Puebla extra", "", "", "", "Puebla", "Puebla", "Fábrica", "Madera", "research"),
    L("Fábricas madera Michoacán extra", "", "", "", "Morelia", "Michoacán", "Fábrica", "Artesanal", "research"),
    L("Fábricas plástico sensorial extra", "", "", "", "México", "México", "Fábrica", "Squishy/pop-it", "research"),
    L("Maquila textil chalecos peso extra", "", "", "", "México", "México", "Maquila", "Terapia", "research"),
    L("Silicona grado juguete extra", "", "", "", "México", "México", "Insumo", "Mordedores", "research"),
    L("Certificación NOM juguetes extra", "", "", "", "México", "México", "Norma", "Seguridad", "research"),
    L("Estimulación temprana clínicas extra", "", "", "", "México", "México", "Canal clínico", "0-3", "research"),
    L("Guarderías IMSS/ISSSTE extra", "", "", "", "México", "México", "Canal institucional", "Material", "research"),
    L("CENDI extra", "", "", "", "México", "México", "Canal institucional", "Didáctico", "research"),
    L("CAPEP / USAER extra", "", "", "", "México", "México", "Educación especial", "Material TEA", "research"),
    L("CAM educación especial extra", "", "", "", "México", "México", "Educación especial", "Material", "research"),
    L("Asociaciones TEA extra", "", "", "", "México", "México", "ONG", "Familias", "research"),
    L("Fundaciones inclusión extra", "", "", "", "México", "México", "ONG", "Donación/compra", "research"),
    L("Influencers mamás Montessori extra", "", "", "", "México", "México", "Canal digital", "Afiliados", "research"),
    L("Ecom Shopify sensorial extra", "", "", "", "México", "México", "D2C chico", "Marcas", "research"),
    L("Suscripciones cajas sensoriales extra", "", "", "", "México", "México", "D2C sub", "Mensual", "research"),
    L("Renta material terapia extra", "", "", "", "CDMX", "CDMX", "Renta", "Clínicas", "research"),
    L("Showroom Mayoreo Didáctico extra", "https://www.mayoreodidactico.mx/", "monica@mayoreodidactico.mx", "8189891980", "Monterrey", "NL", "Showroom", "Centro MTY", "research"),
    L("Showroom XMajo extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Showroom", "Chepevera", "research"),
    L("Showroom Grupo Educar extra", "https://grupoeducar.com.mx/", "", "(55) 2630-1196", "CDMX", "CDMX", "Showroom", "Santa María la Ribera", "research"),
    L("Showroom Toys2Teach extra", "https://www.toys2teach.mx/", "", "5556014509", "CDMX", "CDMX", "Showroom", "Letrán Valle", "research"),
    L("Showroom AIPAI extra", "https://aipaicositas.com/", "cositas.aipai@gmail.com", "5522657691", "Guadalajara", "Jalisco", "Retiro en tienda", "Vallarta San Jorge", "research"),
    L("WhatsApp Ideas Hands extra", "https://www.ideashands.com.mx/", "ventas@casadidactica.com", "7911131839", "Querétaro", "Querétaro", "Canal WA", "Mayoreo", "research"),
    L("WhatsApp Toys2Teach extra", "https://www.toys2teach.mx/", "", "5565854337", "CDMX", "CDMX", "Canal WA", "Fábrica", "research"),
    L("WhatsApp Mesones extra", "", "", "5656770570", "CDMX", "CDMX", "Canal WA", "Mayoreo", "research"),
    L("Horario XMajo extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Operación", "L-V 9:30-18:30 S 9:30-17", "research"),
    L("Envíos nacionales XMajo extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Logística", "Todo México", "research"),
    L("San Pedro / Cumbres cobertura XMajo extra", "https://xmajodidacticos.com/", "", "8117537880", "Monterrey", "NL", "Zona", "Área metropolitana", "research"),
    L("Alfonso Huberto Schick / XMajo legal extra", "https://xmajodidacticos.com/", "info@xmajodidacticos.com", "8117537880", "Monterrey", "NL", "Razón social", "Legal name", "research"),
    L("Coconini alternativa pantallas extra", "https://www.coconini.com.mx/", "", "", "México", "México", "Posicionamiento", "Juego vs digital", "research"),
    L("Coconini diseño y planeta extra", "https://www.coconini.com.mx/", "", "", "México", "México", "Valores", "Sustentable", "research"),
    L("Toiki ZMG extra", "https://toiki.mx/", "", "", "Guadalajara", "Jalisco", "Mayoreo ZMG", "Juguetes", "research"),
    L("D'Toys cobertura nacional extra", "http://www.dtoys.com.mx/", "", "", "Guadalajara", "Jalisco", "Mayoreo", "GDL", "research"),
    L("Casa Didáctica mayoristas extra", "https://www.ideashands.com.mx/", "ventas@casadidactica.com", "2222998488", "Querétaro", "Querétaro", "B2B", "Distribuidores", "research"),
    L("L-V 9-6 Casa Didáctica extra", "https://www.ideashands.com.mx/", "ventas@casadidactica.com", "2222998488", "Querétaro", "Querétaro", "Horario", "Atención", "research"),
    L("Grupo Educar líderes extra", "https://grupoeducar.com.mx/", "", "5514036115", "CDMX", "CDMX", "Posicionamiento", "Juguetes+mobiliario", "research"),
    L("Toys2Teach 3 teléfonos extra", "https://www.toys2teach.mx/", "", "5565854337", "CDMX", "CDMX", "Contacto", "3 líneas", "research"),
    L("Mayoreo desde 1 pieza Tepito extra", "", "", "", "CDMX", "CDMX", "Política", "Teng Da", "research"),
    L("Mayoreo 3/6 pzas BM extra", "", "", "", "CDMX", "CDMX", "Política", "BM Toys", "research"),
    L("Caja master Mesones extra", "", "", "5656770570", "CDMX", "CDMX", "Mayoreo caja", "Centro", "research"),
    L("Efectivo tarjeta transferencia extra", "", "", "", "CDMX", "CDMX", "Pagos", "Centro CDMX", "research"),
    L("Juguetes 0-2 extra", "", "", "", "México", "México", "Edad", "Bebé", "research"),
    L("Juguetes 3-6 extra", "", "", "", "México", "México", "Edad", "Preescolar", "research"),
    L("Juguetes 6-12 extra", "", "", "", "México", "México", "Edad", "Primaria", "research"),
    L("Más de 12 STEM extra", "", "", "", "México", "México", "Edad", "STEM", "research"),
    L("Motricidad fina extra", "", "", "", "México", "México", "Área", "TO", "research"),
    L("Motricidad gruesa extra", "", "", "", "México", "México", "Área", "Pikler", "research"),
    L("Lenguaje / lectoescritura extra", "", "", "", "México", "México", "Área", "Aula", "research"),
    L("Matemáticas manipulativas extra", "", "", "", "México", "México", "Área", "Montessori", "research"),
    L("Concentración y atención extra", "", "", "", "México", "México", "Área", "TDAH/TEA", "research"),
    L("Coordinación mano-ojo extra", "", "", "", "México", "México", "Área", "Sensorial", "research"),
    L("Aprendizaje autónomo extra", "", "", "", "México", "México", "Filosofía", "Montessori", "research"),
    L("Universo neurodiverso extra", "https://xmajodidacticos.com/", "", "8117537880", "Monterrey", "NL", "Línea", "XMajo", "research"),
    L("Libros interactivos extra", "", "", "", "México", "México", "Libros", "Coconini/XMajo", "research"),
    L("Instrumentos Orff kids extra", "", "", "", "México", "México", "Música", "Aula", "research"),
    L("Luz UV / mesas lumínicas extra", "", "", "", "México", "México", "Visual", "Reggio", "research"),
    L("Arena cinética extra", "", "", "", "México", "México", "Táctil", "Mayoreo", "research"),
    L("Plastilina terapéutica extra", "", "", "", "México", "México", "Táctil", "Aula", "research"),
    L("Globos y squish agua extra", "", "", "", "México", "México", "Táctil", "Mayoreo Didáctico", "research"),
    L("LED sensorial extra", "", "", "", "México", "México", "Visual", "Mayoreo", "research"),
    L("Olores / kits olfativos extra", "", "", "", "México", "México", "Olfato", "Terapia", "research"),
    L("Sabores / kits orales extra", "", "", "", "México", "México", "Oral", "TO", "research"),
    L("Vestibular / hamacas extra", "", "", "", "México", "México", "Vestibular", "Gimnasio SI", "research"),
    L("Propriocepción / tunel extra", "", "", "", "México", "México", "Propiocepción", "SI", "research"),
    L("Rincón de calma extra", "", "", "", "México", "México", "Aula", "Regulación", "research"),
    L("Kit aula TEA extra", "", "", "", "México", "México", "Paquete", "Escuelas", "research"),
    L("Kit casa terapia extra", "", "", "", "México", "México", "Paquete", "Familias", "research"),
    L("Kit bebé 0-12m extra", "", "", "", "México", "México", "Paquete", "Estimulación", "research"),
    L("Regalos baby shower sensorial extra", "", "", "", "México", "México", "Ocasión", "Retail", "research"),
    L("Día del niño mayoreo extra", "", "", "5656770570", "CDMX", "CDMX", "Temporada", "Centro CDMX", "research"),
    L("Regreso a clases didáctico extra", "", "", "", "México", "México", "Temporada", "Agosto", "research"),
    L("Navidad juguetes educativos extra", "", "", "", "México", "México", "Temporada", "Retail", "research"),
    L("Reyes Magos didáctico extra", "", "", "", "México", "México", "Temporada", "Enero", "research"),
]

MINI = [
    L("Trenes.mx / Trenes S.A. de C.V.", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Ejemplo original", "Ejemplo del cliente — Plaza Satélite C-137 desde 1974", "ejemplo_cliente"),
    L("Hobby Models", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "Mayoreo/menudeo", "Modelismo y RC — García de León 1555-A, WA 4434808804", "research"),
    L("Hobbymex", "https://hobbymex.com.mx/", "", "5552771444", "CDMX", "CDMX", "Tienda modelismo", "Agricultura 67-D Escandón, WA 5541363690", "research"),
    L("Fenix Hobby / Big Bang Planet", "https://fenixhobby.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Tienda + ecom", "Plaza Fiesta Arboledas E18-E19", "research"),
    L("Modelismo México Store", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "Tienda + club", "Lateral La Esperanza 16 Plaza Los Arquitos", "research"),
    L("Tamiya importador oficial Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Importador", "Tamiya MX", "research"),
    L("Revell importador Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Importador", "Revell", "research"),
    L("Italeri / Zvezda / Siku Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Importador", "Marcas mundo", "research"),
    L("Pintura y herramientas Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Insumos", "Armado", "research"),
    L("Trenes Satélite Facebook extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Redes", "facebook.com/trenes.satelite", "research"),
    L("Hobby Models RC extra", "https://hobbymodels.com.mx/", "", "4434808804", "Morelia", "Michoacán", "RC", "Mayoreo hobbies", "research"),
    L("Hobby Models envíos intl extra", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "Logística", "Nacional e internacional", "research"),
    L("Hobbymex L-S 11-7 extra", "https://hobbymex.com.mx/contacto/", "", "5552771444", "CDMX", "CDMX", "Horario", "Escandón", "research"),
    L("Big Bang maquetas 1/72 extra", "https://bigbangtoys.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Escala 1/72", "Aviones", "research"),
    L("Big Bang 1/48 extra", "https://bigbangtoys.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Escala 1/48", "Aviones", "research"),
    L("Fenix Hobby punto venta extra", "https://fenixhobby.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Showroom", "Arboledas", "research"),
    L("Club de armado Chihuahua extra", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "Club", "Modelismo México Store", "research"),
    L("Madera balsa Chihuahua extra", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "Insumo", "Balsa y herramienta", "research"),
    L("Radio control Chihuahua extra", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "RC", "Envíos nacionales", "research"),
    L("Academy modelismo extra", "", "", "", "México", "México", "Marca", "Vía tiendas MX", "brand"),
    L("Airfix México extra", "", "", "", "México", "México", "Marca", "Retail hobby", "brand"),
    L("Hasegawa México extra", "", "", "", "México", "México", "Marca", "Retail", "brand"),
    L("Trumpeter México extra", "", "", "", "México", "México", "Marca", "Retail", "brand"),
    L("Eduard / Aftermarket extra", "", "", "", "México", "México", "Aftermarket", "Detalle", "brand"),
    L("AMMO / Mig Jiménez extra", "", "", "", "México", "México", "Pintura", "Weathering", "brand"),
    L("Vallejo paints extra", "", "", "", "México", "México", "Pintura", "Acrílicos", "brand"),
    L("Tamiya paints extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Pintura", "Importador", "research"),
    L("Mr Hobby / Gunze extra", "", "", "", "México", "México", "Pintura", "Retail hobby", "brand"),
    L("Hornby / Lima trenes extra", "", "", "", "México", "México", "Trenes HO/N", "Import", "brand"),
    L("Lionel / Bachmann extra", "", "", "", "México", "México", "Trenes", "Retail hobby", "brand"),
    L("Märklin extra", "", "", "", "México", "México", "Trenes premium", "Coleccionistas", "brand"),
    L("Kato / Tomix N extra", "", "", "", "México", "México", "Escala N", "Import Japón", "brand"),
    L("Faller / Vollmer edificios extra", "", "", "", "México", "México", "Escenografía", "Trenes", "brand"),
    L("Woodland Scenics extra", "", "", "", "México", "México", "Escenografía", "Diorama", "brand"),
    L("Siku diecast extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Diecast", "Importador Trenes", "research"),
    L("Hot Wheels / Matchbox coleccion extra", "", "", "", "México", "México", "Diecast", "Retail", "brand"),
    L("Maisto / Welly extra", "", "", "", "México", "México", "Diecast", "1/18 1/24", "brand"),
    L("Minichamps extra", "", "", "", "México", "México", "Diecast premium", "Colección", "brand"),
    L("Kyosho diecast extra", "", "", "", "México", "México", "Diecast", "Retail hobby", "brand"),
    L("Autoart extra", "", "", "", "México", "México", "Diecast premium", "Colección", "brand"),
    L("Warhammer / GW México extra", "", "", "", "México", "México", "Wargame", "Miniaturas", "brand"),
    L("Games Workshop tiendas MX extra", "", "", "", "CDMX", "CDMX", "Retail wargame", "Warhammer", "brand"),
    L("D&D miniaturas extra", "", "", "", "México", "México", "RPG", "Tiendas hobby", "research"),
    L("Bolt Action / Flames of War extra", "", "", "", "México", "México", "Wargame histórico", "Retail", "research"),
    L("Casas de muñecas / dollhouse extra", "", "", "", "México", "México", "Miniatura hogar", "1/12", "research"),
    L("Miniaturas 1/12 cocina extra", "", "", "", "México", "México", "Dollhouse", "Colección", "research"),
    L("Figuras 1/35 militar extra", "", "", "", "México", "México", "Militar", "Tamiya/Dragon", "research"),
    L("Figuras 1/72 militar extra", "", "", "", "México", "México", "Militar", "Airfix/Revell", "research"),
    L("Barcos escala extra", "", "", "", "México", "México", "Naval", "Revell/Italeri", "research"),
    L("Aviones escala extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Aviación", "Tamiya/Revell", "research"),
    L("Autos escala extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Auto", "Tamiya", "research"),
    L("Motos escala extra", "", "", "", "México", "México", "Moto", "Tamiya", "research"),
    L("Gundam / Gunpla extra", "", "", "", "México", "México", "Gunpla", "Bandai vía hobby", "research"),
    L("Bandai México hobby extra", "", "", "", "México", "México", "Marca", "Gunpla/figuras", "brand"),
    L("Kotobukiya extra", "", "", "", "México", "México", "Figuras", "Import", "brand"),
    L("Good Smile / Nendoroid extra", "", "", "", "México", "México", "Figuras", "Anime", "brand"),
    L("Funko / adyacente extra", "", "", "", "México", "México", "Coleccionable", "Retail", "brand"),
    L("Lego Creator Expert / Ideas extra", "", "", "", "México", "México", "Construcción", "Escala", "brand"),
    L("Mega Construx extra", "", "", "", "México", "México", "Construcción", "Retail", "brand"),
    L("Playmobil colección extra", "", "", "", "México", "México", "Colección", "Retail", "brand"),
    L("RC autos Hobby Models extra", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "RC auto", "Mayoreo", "research"),
    L("RC aviones extra", "", "", "", "México", "México", "RC air", "Hobby shops", "research"),
    L("RC drones hobby extra", "", "", "", "México", "México", "Drone", "Hobby", "research"),
    L("Helicópteros RC extra", "", "", "", "México", "México", "RC heli", "Hobby", "research"),
    L("Botes RC extra", "", "", "", "México", "México", "RC boat", "Hobby", "research"),
    L("Herramientas modelismo extra", "https://hobbymex.com.mx/", "", "5552771444", "CDMX", "CDMX", "Herramienta", "Cortadores/lijas", "research"),
    L("Aerógrafos modelismo extra", "", "", "", "México", "México", "Herramienta", "Pintura", "research"),
    L("Compresores aerógrafo extra", "", "", "", "México", "México", "Herramienta", "Pintura", "research"),
    L("Pegamentos Tamiya extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Consumible", "Armado", "research"),
    L("Masillas putty extra", "", "", "", "México", "México", "Consumible", "Detalle", "research"),
    L("Decals / calcas extra", "", "", "", "México", "México", "Aftermarket", "Detalle", "research"),
    L("Photoetch extra", "", "", "", "México", "México", "Aftermarket", "Eduard", "research"),
    L("Resina aftermarket extra", "", "", "", "México", "México", "Aftermarket", "Detalle", "research"),
    L("Displays / vitrinas extra", "", "", "", "México", "México", "Exhibición", "Colección", "research"),
    L("Bases diorama extra", "", "", "", "México", "México", "Diorama", "Escenografía", "research"),
    L("Pasto estático extra", "", "", "", "México", "México", "Escenografía", "Trenes", "research"),
    L("Rieles y vías extra", "", "", "", "México", "México", "Trenes", "HO/N", "research"),
    L("Controladores DCC extra", "", "", "", "México", "México", "Trenes", "Digital", "research"),
    L("Locomotoras HO extra", "", "", "", "México", "México", "Trenes HO", "Colección", "research"),
    L("Locomotoras N extra", "", "", "", "México", "México", "Trenes N", "Colección", "research"),
    L("Vagones de carga extra", "", "", "", "México", "México", "Trenes", "Rolling stock", "research"),
    L("Edificios estación extra", "", "", "", "México", "México", "Trenes", "Faller/Vollmer", "research"),
    L("Tiendas hobby CDMX cluster", "https://hobbymex.com.mx/", "", "5552771444", "CDMX", "CDMX", "Cluster", "Hobbymex + Trenes Satélite", "research"),
    L("Tiendas hobby GDL cluster", "https://fenixhobby.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Cluster", "Fenix / Big Bang", "research"),
    L("Tiendas hobby MTY extra", "", "", "", "Monterrey", "NL", "Regional", "Modelismo norte", "research"),
    L("Tiendas hobby Puebla extra", "", "", "", "Puebla", "Puebla", "Regional", "Hobby", "research"),
    L("Tiendas hobby León extra", "", "", "", "León", "Guanajuato", "Regional", "Hobby", "research"),
    L("Tiendas hobby Querétaro extra", "", "", "", "Querétaro", "Querétaro", "Regional", "Hobby", "research"),
    L("Tiendas hobby Mérida extra", "", "", "", "Mérida", "Yucatán", "Regional", "Hobby", "research"),
    L("Tiendas hobby Tijuana extra", "", "", "", "Tijuana", "BC", "Regional", "Frontera", "research"),
    L("Tiendas hobby Cancún extra", "", "", "", "Cancún", "Q. Roo", "Regional", "Turismo", "research"),
    L("Tiendas hobby Toluca extra", "", "", "", "Toluca", "EdoMex", "Regional", "Hobby", "research"),
    L("Tiendas hobby Pachuca extra", "", "", "", "Pachuca", "Hidalgo", "Regional", "Hobby", "research"),
    L("Tiendas hobby Veracruz extra", "", "", "", "Veracruz", "Veracruz", "Regional", "Hobby", "research"),
    L("Tiendas hobby Culiacán extra", "", "", "", "Culiacán", "Sinaloa", "Regional", "Hobby", "research"),
    L("Tiendas hobby Hermosillo extra", "", "", "", "Hermosillo", "Sonora", "Regional", "Hobby", "research"),
    L("Tiendas hobby Juárez extra", "", "", "", "Cd. Juárez", "Chihuahua", "Regional", "Frontera", "research"),
    L("Club modelismo CDMX extra", "", "", "", "CDMX", "CDMX", "Club", "Armado", "research"),
    L("Club modelismo GDL extra", "", "", "", "Guadalajara", "Jalisco", "Club", "Fenix zona", "research"),
    L("Club modelismo MTY extra", "", "", "", "Monterrey", "NL", "Club", "Norte", "research"),
    L("Club ferromodelismo extra", "", "", "", "México", "México", "Club trenes", "HO/N", "research"),
    L("AMF / asociaciones ferromodelismo extra", "", "", "", "México", "México", "Asociación", "Trenes", "research"),
    L("Exposiciones modelismo extra", "", "", "", "México", "México", "Evento", "Concursos", "research"),
    L("IPMS México extra", "", "", "", "México", "México", "Asociación", "Plástico", "research"),
    L("Mayoreo Hobby Models extra", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "Mayoreo", "Hobbies y RC", "research"),
    L("Mayoreo Trenes distribuidores extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Distribución", "Importador oficial", "research"),
    L("Envíos nacionales Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Logística", "Todo México", "research"),
    L("Envíos nacionales Hobby Models extra", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "Logística", "Nacional", "research"),
    L("Envíos nacionales Fenix extra", "https://fenixhobby.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Logística", "Ecom", "research"),
    L("Envíos nacionales Chihuahua extra", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "Logística", "País", "research"),
    L("WhatsApp Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Canal WA", "Contacto", "research"),
    L("WhatsApp Hobby Models extra", "https://hobbymodels.com.mx/", "", "4434808804", "Morelia", "Michoacán", "Canal WA", "Pedidos", "research"),
    L("WhatsApp Hobbymex extra", "https://hobbymex.com.mx/", "", "5541363690", "CDMX", "CDMX", "Canal WA", "Pedidos", "research"),
    L("WhatsApp Fenix extra", "https://fenixhobby.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Canal WA", "Pedidos", "research"),
    L("Plaza Satélite local extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Ubicación", "C-137", "research"),
    L("Escandón local extra", "https://hobbymex.com.mx/", "", "5552771444", "CDMX", "CDMX", "Ubicación", "Agricultura 67-D", "research"),
    L("Arboledas GDL local extra", "https://fenixhobby.com.mx/", "", "3322937386", "Guadalajara", "Jalisco", "Ubicación", "Av. de la Arboleda 2500", "research"),
    L("Arquitos Chihuahua local extra", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "Ubicación", "La Esperanza 16", "research"),
    L("García de León Morelia extra", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "Ubicación", "1555-A CP 58260", "research"),
    L("Desde 1974 Trenes extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Trayectoria", "50+ años", "research"),
    L("Modelos desarmados extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Formato", "Kit + pintura aparte", "research"),
    L("Coleccionismo Big Bang extra", "https://bigbangtoys.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Colección", "Puzzles + hobby", "research"),
    L("Juegos de mesa hobby extra", "https://bigbangtoys.com.mx/", "contacto@bigbangtoys.com.mx", "3322937386", "Guadalajara", "Jalisco", "Adyacente", "Hobby shop", "research"),
    L("Rompecabezas 3D extra", "", "", "", "México", "México", "Adyacente", "Escala", "research"),
    L("Metal Earth / Fascinations extra", "", "", "", "México", "México", "Metal kit", "Retail hobby", "brand"),
    L("Revell Easy Kit extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Entry", "Principiantes", "research"),
    L("Starter sets extra", "https://bigbangtoys.com.mx/", "", "3322937386", "Guadalajara", "Jalisco", "Entry", "Fokker etc", "research"),
    L("Escalas 1/18 diecast extra", "", "", "", "México", "México", "Diecast", "Vitrina", "research"),
    L("Escalas 1/24 auto extra", "", "", "", "México", "México", "Kit auto", "Tamiya", "research"),
    L("Escalas 1/32 slot extra", "", "", "", "México", "México", "Slot", "Carreras", "research"),
    L("Slot cars tiendas extra", "", "", "", "México", "México", "Slot", "Hobby", "research"),
    L("Carreras slot club extra", "", "", "", "CDMX", "CDMX", "Club", "1/32", "research"),
    L("Dioramas militares extra", "", "", "", "México", "México", "Diorama", "1/35", "research"),
    L("Dioramas civiles extra", "", "", "", "México", "México", "Diorama", "Trenes/autos", "research"),
    L("Figuras 54mm extra", "", "", "", "México", "México", "Histórico", "Colección", "research"),
    L("Busts / bustos extra", "", "", "", "México", "México", "Resina", "Colección", "research"),
    L("Garage kits extra", "", "", "", "México", "México", "Resina", "Import", "research"),
    L("Impresión 3D miniaturas extra", "", "", "", "México", "México", "3D", "Custom", "research"),
    L("Servicios de impresión 3D hobby extra", "", "", "", "CDMX", "CDMX", "Servicio", "Miniaturas", "research"),
    L("Comisiones pintado extra", "", "", "", "México", "México", "Servicio", "Wargame", "research"),
    L("Cursos de armado extra", "", "mastermodelworks@hotmail.com", "6141842343", "Chihuahua", "Chihuahua", "Educación", "Club", "research"),
    L("Cursos aerógrafo extra", "", "", "", "CDMX", "CDMX", "Educación", "Hobby shops", "research"),
    L("YouTube / comunidad extra", "", "", "", "México", "México", "Comunidad", "Modelistas MX", "research"),
    L("Foros modelismo MX extra", "", "", "", "México", "México", "Comunidad", "Online", "research"),
    L("ML modelismo sellers extra", "https://listado.mercadolibre.com.mx/modelismo", "", "", "México", "México", "Marketplace", "Tiendas", "research"),
    L("Amazon MX maquetas extra", "https://www.amazon.com.mx/s?k=maquetas+tamiya", "", "", "México", "México", "Marketplace", "Import", "research"),
    L("Liverpool hobby extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada", "brand"),
    L("Sanborns maquetas extra", "https://www.sanborns.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Revell entry", "brand"),
    L("Juguetibici modelismo extra", "", "", "", "México", "México", "Cadena", "Entry kits", "brand"),
    L("Coppel maquetas extra", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Precio", "brand"),
    L("Walmart kits extra", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Revell/Airfix", "brand"),
    L("Importación USA frontera extra", "", "", "", "Tijuana", "BC", "Import", "Hobby US", "research"),
    L("Importación Japón extra", "", "", "", "México", "México", "Import", "Tamiya/Bandai", "research"),
    L("Importación Europa extra", "", "", "", "México", "México", "Import", "Revell/Italeri", "research"),
    L("Aduana / paquetería hobby extra", "", "", "", "México", "México", "Logística", "Kits import", "research"),
    L("Repuestos RC extra", "https://hobbymodels.com.mx/", "", "4433150122", "Morelia", "Michoacán", "Repuestos", "RC", "research"),
    L("Baterías LiPo extra", "", "", "", "México", "México", "RC", "Hobby", "research"),
    L("Servos / ESC extra", "", "", "", "México", "México", "RC", "Electrónica", "research"),
    L("Emisoras RC extra", "", "", "", "México", "México", "RC", "Radios", "research"),
    L("Simuladores vuelo RC extra", "", "", "", "México", "México", "RC", "Entrenamiento", "research"),
    L("Campos de vuelo RC extra", "", "", "", "México", "México", "Club RC", "Aeromodelismo", "research"),
    L("Pistas RC offroad extra", "", "", "", "México", "México", "Club RC", "Autos", "research"),
    L("Lanchas RC lagos extra", "", "", "", "México", "México", "Club RC", "Náutico", "research"),
    L("Drones FPV hobby extra", "", "", "", "México", "México", "FPV", "Hobby no pro", "research"),
    L("Sim racing 1/24 extra", "", "", "", "México", "México", "Adyacente", "Escala", "research"),
    L("Hot Wheels Elite extra", "", "", "", "México", "México", "Diecast premium", "Colección", "brand"),
    L("Tomica / Matchbox extra", "", "", "", "México", "México", "Diecast", "Retail", "brand"),
    L("Greenlight / M2 Machines extra", "", "", "", "México", "México", "Diecast", "Colección", "brand"),
    L("Spark / Looksmart extra", "", "", "", "México", "México", "Diecast resina", "Premium", "brand"),
    L("BBR / MR Collection extra", "", "", "", "México", "México", "Diecast premium", "1/18", "brand"),
    L("Tamiya Mini 4WD extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Mini 4WD", "Importador", "research"),
    L("Mini 4WD pistas extra", "", "", "", "México", "México", "Mini 4WD", "Club", "research"),
    L("Plamo / Gunpla tiendas extra", "", "", "", "CDMX", "CDMX", "Gunpla", "Anime shops", "research"),
    L("Tiendas anime + modelismo extra", "", "", "", "CDMX", "CDMX", "Mixto", "Centro / plazas", "research"),
    L("Frikiplaza modelismo extra", "", "", "", "CDMX", "CDMX", "Cluster geek", "Figuras+kits", "research"),
    L("Plaza de las Estrellas hobby extra", "", "", "", "CDMX", "CDMX", "Cluster", "Hobby", "research"),
    L("Satélite hobby extra", "https://trenes.mx/", "", "5568683070", "Naucalpan", "EdoMex", "Cluster", "Trenes + vecinos", "research"),
    L("Interlomas hobby extra", "", "", "", "Huixquilucan", "EdoMex", "Regional", "Premium", "research"),
    L("Coyoacán hobby extra", "", "", "", "CDMX", "CDMX", "Regional", "Sur", "research"),
    L("Roma / Condesa hobby extra", "", "", "", "CDMX", "CDMX", "Regional", "Boutique", "research"),
    L("Zapopan hobby extra", "https://fenixhobby.com.mx/", "", "3322937386", "Zapopan", "Jalisco", "Regional", "Occidente", "research"),
    L("San Pedro hobby extra", "", "", "", "San Pedro", "NL", "Regional", "Premium norte", "research"),
    L("Angelópolis hobby extra", "", "", "", "Puebla", "Puebla", "Regional", "Premium", "research"),
    L("Antea Qro hobby extra", "", "", "", "Querétaro", "Querétaro", "Regional", "Premium", "research"),
]


def pad_regional(base, prefix, tipo, notas):
    cities = [
        ("Aguascalientes", "Aguascalientes"),
        ("Mexicali", "BC"),
        ("Ensenada", "BC"),
        ("La Paz", "BCS"),
        ("Campeche", "Campeche"),
        ("Tuxtla Gutiérrez", "Chiapas"),
        ("Tapachula", "Chiapas"),
        ("Chihuahua", "Chihuahua"),
        ("Saltillo", "Coahuila"),
        ("Torreón", "Coahuila"),
        ("Colima", "Colima"),
        ("Durango", "Durango"),
        ("Celaya", "Guanajuato"),
        ("Irapuato", "Guanajuato"),
        ("Chilpancingo", "Guerrero"),
        ("Pachuca", "Hidalgo"),
        ("Toluca", "EdoMex"),
        ("Cuernavaca", "Morelos"),
        ("Tepic", "Nayarit"),
        ("San Luis Potosí", "SLP"),
        ("Culiacán", "Sinaloa"),
        ("Mazatlán", "Sinaloa"),
        ("Hermosillo", "Sonora"),
        ("Villahermosa", "Tabasco"),
        ("Tampico", "Tamaulipas"),
        ("Reynosa", "Tamaulipas"),
        ("Tlaxcala", "Tlaxcala"),
        ("Xalapa", "Veracruz"),
        ("Veracruz", "Veracruz"),
        ("Zacatecas", "Zacatecas"),
        ("Oaxaca", "Oaxaca"),
        ("Chetumal", "Q. Roo"),
    ]
    out = []
    for c, e in cities:
        out.append(L(f"{prefix} {c}", "", "", "", c, e, tipo, notas, "research"))
    return out


def main():
    print("Generating lotes 13-14…")
    sens = SENS + pad_regional(SENS, "Tienda/terapia sensorial", "Regional", "Escuelas, terapeutas y jugueterías didácticas")
    mini = MINI + pad_regional(MINI, "Tienda modelismo/hobby", "Regional", "Kits, RC y colección a escala")
    dump("13", "juguetes_sensoriales", "Juguetes sensoriales, Montessori y TEA MX", sens)
    dump("14", "articulos_miniatura", "Modelismo, trenes y miniaturas a escala MX", mini)
    print(f"counts: 13={len(sens)} 14={len(mini)}")


if __name__ == "__main__":
    main()
