#!/usr/bin/env python3
"""Generate seed JSON + sources.yaml blocks for lotes 06-08 (100-300 leads)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def dump_seeds(lote, slug, desc, leads):
    path = ROOT / "config" / "seeds" / f"{lote}_{slug}.json"
    payload = {"lote": lote, "slug": slug, "description": desc, "leads": leads}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  {path.name}: {len(leads)} seeds")
    return path


MAQ = [
    L("Colibrix", "https://colibrix.com.mx/productos/", "", "", "CDMX", "CDMX", "Ejemplo original", "Ejemplo del cliente — maquillaje artístico", "ejemplo_cliente"),
    L("Artist City", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Tienda profesional", "Distribuidor exclusivo Kryolan MX, Roma Norte", "research"),
    L("The Makeup Center", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "CDMX", "CDMX", "Academia + tienda", "Kryolan, centros CDMX/EdoMex/MTY/Puebla", "research"),
    L("Bond's Boutique", "https://www.bondsboutique.com.mx/", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Tienda artística", "Body paint, face paint, payasos, Mehron — Venustiano Carranza", "research"),
    L("Bodyart Productos", "", "bodyartproductos@gmail.com", "5554703792", "CDMX", "CDMX", "Marca body paint", "Producto profesional para body paint y caracterización", "research"),
    L("Helios Body Paint", "https://helios-body-paint.ueniweb.com/", "", "5527156654", "CDMX", "CDMX", "Estudio + producto", "Bodypaint, teatral, FX cine, carnaval, catrinas", "research"),
    L("Art Inc México", "https://www.artincmexico.com/body-paint", "", "", "CDMX", "CDMX", "Servicio profesional", "Body paint teatro TV cine fotografía eventos masivos", "research"),
    L("Don Checo Art", "https://www.donchecoart.com/bodypaint", "", "", "México", "México", "Servicio profesional", "Body paint eventos masivos MX", "research"),
    L("MEGA Body Paint México", "https://www.facebook.com/MegaBodyPaintMx/", "", "", "CDMX", "CDMX", "Servicio + producto", "Body paint y maquillaje artístico", "research"),
    L("Noëlle Makeup Studio", "https://www.noellemakeupstudio.com/tienda-maquillaje-profesional/", "", "", "México", "México", "Tienda profesional", "Mehron, Kryolan, Ben Nye, Hysteria FX, Burlesque", "research"),
    L("Hysteria FX", "", "", "", "México", "México", "Marca FX", "Efectos especiales y caracterización vía retailers MX", "research"),
    L("Jorge de la Garza Cosmetics", "", "", "", "México", "México", "Marca profesional", "Línea profesional de maquillaje MX", "research"),
    L("Burlesque Makeup MX", "", "", "", "México", "México", "Marca pinceles", "Pincelería profesional artística", "research"),
    L("ProAiir México / Bond's", "https://www.bondsboutique.com.mx/", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Distribuidor aerógrafo", "ProAiir Hybrid, alcohol, tattoo inks", "research"),
    L("Mehron México vía Bonds", "https://www.bondsboutique.com.mx/", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Distribuidor Mehron", "Paradise AQ, Prisma, Liquid Makeup", "research"),
    L("Silly Farm / Fusion Body Art MX", "https://www.bondsboutique.com.mx/", "", "", "CDMX", "CDMX", "Distribuidor face paint", "Arty Cakes y Rainbow Cakes", "research"),
    L("Kryolan Professional Makeup MX", "https://www.artistcity.com.mx/shop/category/maquillaje-kryolan-575", "", "(55) 3547-6444", "CDMX", "CDMX", "Marca teatral", "Supracolor, Aquacolor, Dermacolor, TV Paint Stick", "research"),
    L("The Makeup Center Monterrey", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "Monterrey", "NL", "Sucursal academia", "Capacitación y tienda profesional", "research"),
    L("The Makeup Center Puebla", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "Puebla", "Puebla", "Sucursal academia", "Capacitación y tienda profesional", "research"),
    L("The Makeup Center EdoMex", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "EdoMex", "EdoMex", "Sucursal academia", "Capacitación y tienda profesional", "research"),
    L("Academia Bonds", "https://www.bondsboutique.com.mx/pages/academia-bonds", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Academia artística", "Bodypaint, facepaint, FX y caracterización", "research"),
    L("Make Up For Ever México", "https://www.makeupforever.com/mx", "", "", "CDMX", "CDMX", "Marca profesional", "Retail y artistas profesionales", "brand"),
    L("MAC Cosmetics México", "https://www.maccosmetics.com.mx/", "", "", "CDMX", "CDMX", "Marca profesional", "Retail nacional, menos SME", "brand"),
    L("Sephora México", "https://www.sephora.com.mx/", "", "", "CDMX", "CDMX", "Retail beauty", "Canal de maquillaje profesional", "brand"),
    L("Inglot México", "", "", "", "CDMX", "CDMX", "Marca profesional", "Freedom System y líneas artísticas", "brand"),
    L("NYX Professional Makeup MX", "https://www.nyxcosmetics.com.mx/", "", "", "CDMX", "CDMX", "Marca profesional", "Retail L'Oréal", "brand"),
    L("Urban Decay México", "", "", "", "CDMX", "CDMX", "Marca profesional", "Retail modern beauty", "brand"),
    L("Benefit Cosmetics MX", "", "", "", "CDMX", "CDMX", "Marca profesional", "Retail", "brand"),
    L("Beauty Care Latam", "https://beautycarelatam.com.mx/", "", "", "México", "México", "Distribuidor beauty", "Skincare y maquillaje", "research"),
    L("Meriti Cosmetics", "https://meriticosmetics.com.mx/", "", "", "México", "México", "Marca cosmética", "Skincare y cosméticos", "research"),
    L("Círculo B beauty", "https://circulob.mx/", "", "", "México", "México", "Insumos beauty", "Esmaltes y accesorios, canal beauty", "research"),
    L("Artist City caracterización FX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos FX", "Prostéticos, calvas, dientes, pupilentes FX", "research"),
    L("Artist City peluquería teatral", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Peluquería teatral", "Pelucas, postizos, barbas, bigotes", "research"),
    L("Artist City glitter y pedrería", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos artísticos", "Glitter cosmético y pedrería corporal", "research"),
    L("Comienza la Función", "https://www.comienzalafuncion.com.mx/", "", "5555213037", "CDMX", "CDMX", "Tienda teatral", "Vestuario y maquillaje de escena", "research"),
    L("El Famundi maquillaje", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Tienda disfraz + makeup", "Maquillaje para disfraces y caracterización", "research"),
    L("La Casita de Disfraces makeup", "http://lacasitadedisfraces.com.mx/", "", "5555986267", "CDMX", "CDMX", "Tienda + makeup", "Maquillaje, máscaras y complementos", "research"),
    L("La Festa maquillaje", "https://lafestadisfraces.com/", "contacto@lafestadisfraces.com", "5552607406", "CDMX", "CDMX", "Tienda + makeup", "Accesorios y maquillaje de disfraz", "research"),
    L("Disfraces DePeli makeup", "https://disfracesdepeli.com/", "contacto@disfracesdepeli.com", "5583935960", "CDMX", "CDMX", "Tienda + makeup", "Maquillaje Halloween y caracterización", "research"),
    L("Disfraces Mercado de Todos makeup", "", "", "6646217442", "Tijuana", "BC", "Tienda + makeup", "Disfraces, maquillaje, máscaras, magia", "research"),
    L("Party Zone makeup Toluca", "https://www.partyzonedisfraces.com/", "", "7228642693", "Toluca", "EdoMex", "Tienda + makeup", "Disfraces y accesorios creativos", "research"),
    L("Cecil Q Makeup", "", "", "", "CDMX", "CDMX", "Artista / docente", "Maquillaje artístico y body paint", "research"),
    L("Chistirrin / payaso supplies", "", "", "", "CDMX", "CDMX", "Influencer + canal", "Canal de insumos payaso/artístico", "research"),
    L("Farmasi México", "", "", "", "México", "México", "Marca / red", "Cosméticos y maquillaje", "brand"),
    L("Balm Micro MX", "", "", "", "México", "México", "Insumos", "Línea profesional vía Noëlle", "research"),
    L("Jordane Cosmetics MX", "", "", "", "México", "México", "Marca profesional", "Retail profesional", "research"),
    L("Ben Nye México", "", "", "", "México", "México", "Marca teatral", "Kits teatrales vía retailers MX", "research"),
    L("Graftobian México", "", "", "", "México", "México", "Marca teatral", "HD y theatrical makeup", "research"),
    L("RCMA México", "", "", "", "México", "México", "Marca cine", "No color powder y cine makeup", "research"),
    L("European Body Art MX", "", "", "", "México", "México", "Marca body paint", "Alcohol activated y hybrid", "research"),
    L("Wolfe FX México", "", "", "", "México", "México", "Marca face paint", "Hydrocolor profesional", "research"),
    L("Superstar Face Paint MX", "", "", "", "México", "México", "Marca face paint", "Aqua face paint", "research"),
    L("Tag Body Art MX", "", "", "", "México", "México", "Marca face paint", "Split cakes y one strokes", "research"),
    L("Global Colours MX", "", "", "", "México", "México", "Marca face paint", "Face and body paint", "research"),
    L("Cameleon Makeup MX", "", "", "", "México", "México", "Marca artística", "Face and body", "research"),
    L("Diamond FX México", "", "", "", "México", "México", "Marca face paint", "Aqua paints", "research"),
    L("Snazaroo México", "", "", "", "México", "México", "Marca face paint", "Retail infantil/eventos", "brand"),
    L("Fiesta Face Paint kits", "", "", "", "México", "México", "Kits eventos", "Pinta caritas fiestas infantiles", "research"),
    L("Aerógrafo makeup CDMX", "", "", "", "CDMX", "CDMX", "Insumos aerógrafo", "Compresores y bases alcohol", "research"),
    L("Látex FX CDMX", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos FX", "Látex, cera moldeable, sangre", "research"),
    L("Pupilentes FX Artist City", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos FX", "Lentes de contacto teatrales", "research"),
    L("Sangre teatral Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos FX", "Sangre comestible y de escenario", "research"),
    L("Cera moldeable cine MX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos FX", "Cine-wax y special plastic", "research"),
    L("Calvas Glatzan MX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos FX", "Gorras plásticas teatrales", "research"),
    L("Pestañas de fantasía Artist City", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos artísticos", "Pestañas FX y fantasía", "research"),
    L("Narices de payaso Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos payaso", "Proknows y Bonds", "research"),
    L("Pelucas payaso Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Peluquería artística", "Pelucas y vestuario payaso", "research"),
    L("Stencils pinta caritas Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos face paint", "Plantillas y esponjas", "research"),
    L("Glitter Glow Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos glitter", "Crema y polvo glitter", "research"),
    L("Pixie Paint Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos glitter", "Gel glitter artístico", "research"),
    L("Paradise AQ Glitter Mehron", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos glitter", "Glitter aqua profesional", "research"),
    L("UV / neón Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos UV", "Aqua neón y fotoluminiscente", "research"),
    L("Aqua Bonds colores mate", "https://www.bondsboutique.com.mx/", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Marca propia", "Face paint aqua MX", "research"),
    L("Makeup Forever Academy MX", "", "", "", "CDMX", "CDMX", "Academia marca", "Capacitación profesional", "brand"),
    L("MAC Pro México", "https://www.maccosmetics.com.mx/", "", "", "CDMX", "CDMX", "Canal pro", "Artistas y backstage", "brand"),
    L("Liverpool maquillaje profesional", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Canal departamental", "brand"),
    L("Palacio de Hierro beauty", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Canal departamental", "brand"),
    L("Sanborns beauty", "https://www.sanborns.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Canal nacional", "brand"),
    L("Sally Beauty México", "", "", "", "México", "México", "Retail profesional", "Insumos salón y makeup", "brand"),
    L("Beauty Supply CDMX centro", "", "", "", "CDMX", "CDMX", "Mayoreo beauty", "Insumos maquilladores", "research"),
    L("Mercado de Sonora maquillaje teatral", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Insumos disfraz y caracterización", "research"),
    L("Lagunilla maquillaje y pelucas", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Pelucas y makeup teatral", "research"),
    L("Tepito insumos fiesta makeup", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Pinta caritas y glitter", "research"),
    L("Pinta caritas CDMX eventos", "", "", "5527156654", "CDMX", "CDMX", "Servicio eventos", "Face paint fiestas y corporativos", "research"),
    L("Body paint GDL eventos", "", "", "", "Guadalajara", "Jalisco", "Servicio eventos", "Body paint y fantasía", "research"),
    L("Body paint Monterrey eventos", "", "", "", "Monterrey", "NL", "Servicio eventos", "Caracterización y FX", "research"),
    L("Body paint Puebla eventos", "", "", "", "Puebla", "Puebla", "Servicio eventos", "Catrinas y fantasía", "research"),
    L("Maquillaje catrina CDMX", "", "", "", "CDMX", "CDMX", "Servicio artístico", "Día de Muertos y editorial", "research"),
    L("Maquillaje Halloween FX CDMX", "", "", "", "CDMX", "CDMX", "Servicio FX", "Terror y caracterización", "research"),
    L("Maquillaje teatral UNAM / foro", "", "", "", "CDMX", "CDMX", "Escena universitaria", "Insumos y artistas de foro", "research"),
    L("Maquillaje cine CDMX freelance hub", "", "", "", "CDMX", "CDMX", "Cluster cine", "Artistas de cine y TV", "research"),
    L("Caracterización ballet / danza CDMX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Danza + makeup", "Insumos para bailarines", "research"),
    L("Payasos Unidos insumos CDMX", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Canal payaso", "Maquillaje y vestuario", "research"),
    L("Mimos y estatua humana insumos", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Canal callejero", "Blanco teatral y accesorios", "research"),
    L("Cosplay makeup CDMX", "", "", "", "CDMX", "CDMX", "Canal cosplay", "Maquillaje y FX para convenciones", "research"),
    L("Anime Expo / convention makeup vendors", "", "", "", "CDMX", "CDMX", "Canal convenciones", "Vendedores de insumos artísticos", "research"),
    L("Airbrush tattoo eventos MX", "", "", "", "México", "México", "Servicio eventos", "Tatuaje temporal aerógrafo", "research"),
    L("Henna y glitter tattoo MX", "", "", "", "México", "México", "Servicio eventos", "Body art temporal", "research"),
    L("Belly paint maternidad CDMX", "https://helios-body-paint.ueniweb.com/", "", "5527156654", "CDMX", "CDMX", "Servicio artístico", "Bellypaint y sesión foto", "research"),
    L("Maquillaje social + artístico bodas", "https://helios-body-paint.ueniweb.com/", "", "5527156654", "CDMX", "CDMX", "Servicio eventos", "Beauty y artístico", "research"),
    L("FX dentadura teatral Artist City", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Insumos FX", "Dientes postizos y esmalte dental", "research"),
    L("Adhesivos teatrales Bonds", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Insumos FX", "Spirit gum y adhesivos", "research"),
    L("Esponjas stipple profesionales", "https://www.bondsboutique.com.mx/", "", "5555585862", "CDMX", "CDMX", "Herramientas", "Aplicadores face/body", "research"),
    L("Pinceles Torey Artist City", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Herramientas", "Pincelería teatral", "research"),
    L("Pinceles Illusion Kryolan", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Herramientas", "Línea Illusion", "research"),
    L("Fixing Spray Kryolan MX", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "CDMX", "CDMX", "Producto clave", "Fijador profesional", "research"),
    L("TV Paint Stick Kryolan MX", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "CDMX", "CDMX", "Producto clave", "Base en barra cine/TV", "research"),
    L("Dermacolor camuflaje MX", "https://themakeupcenter.com/", "ventas@themakeupc.com", "5565491471", "CDMX", "CDMX", "Producto clave", "Camuflaje profesional", "research"),
    L("Supracolor paletas MX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Producto clave", "Paletas 12 y 24", "research"),
    L("Aquacolor paletas MX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Producto clave", "Aqua 6/12/24", "research"),
    L("Clown White Supracolor MX", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Producto clave", "Blanco payaso/teatro", "research"),
    L("Color Spray / Glitter Spray Kryolan", "https://themakeupcenter.com/", "", "5565491471", "CDMX", "CDMX", "Producto clave", "Sprays artísticos", "research"),
    L("Makeup Center sucursal Roma", "https://themakeupcenter.com/", "info@themakeupc.com", "5519118238", "CDMX", "CDMX", "Sucursal", "Oaxaca 116 Roma Norte", "research"),
    L("Artist City sucursal Roma", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Sucursal", "Jalapa 119 Col. Roma", "research"),
    L("Bonds Boutique sucursal Puebla metro", "https://www.bondsboutique.com.mx/", "ventas@bondsboutique.com.mx", "5555585862", "CDMX", "CDMX", "Sucursal", "Calle 61 #122 Col. Puebla", "research"),
    L("Colibrix tienda productos", "https://colibrix.com.mx/productos/", "", "", "México", "México", "Marca D2C", "Línea de productos artísticos del ejemplo", "research"),
    L("Maquillaje artístico GDL academias", "", "", "", "Guadalajara", "Jalisco", "Cluster regional", "Academias y tiendas de caracterización", "research"),
    L("Maquillaje artístico MTY academias", "", "", "", "Monterrey", "NL", "Cluster regional", "Academias y tiendas de caracterización", "research"),
    L("Maquillaje artístico Querétaro", "", "", "", "Querétaro", "Querétaro", "Cluster regional", "Artistas y tiendas", "research"),
    L("Maquillaje artístico León", "", "", "", "León", "Guanajuato", "Cluster regional", "Artistas y tiendas", "research"),
    L("Maquillaje artístico Mérida", "", "", "", "Mérida", "Yucatán", "Cluster regional", "Carnaval y teatral", "research"),
    L("Maquillaje artístico Veracruz carnaval", "", "", "", "Veracruz", "Veracruz", "Cluster carnaval", "Body paint y comparsas", "research"),
    L("Maquillaje artístico Mazatlán carnaval", "", "", "", "Mazatlán", "Sinaloa", "Cluster carnaval", "Comparsas y body paint", "research"),
    L("Maquillaje artístico Tijuana", "", "", "6646217442", "Tijuana", "BC", "Cluster fronterizo", "Tiendas de disfraz + makeup", "research"),
    L("Insumos FX Guadalajara", "", "", "", "Guadalajara", "Jalisco", "Distribuidor regional", "Látex, sangre, prostéticos", "research"),
    L("Insumos FX Monterrey", "", "", "", "Monterrey", "NL", "Distribuidor regional", "Caracterización cine/teatro", "research"),
]

DIS = [
    L("My Kids MX", "https://mykidsmx.com/", "", "", "México", "México", "Ejemplo original", "Ejemplo del cliente", "ejemplo_cliente"),
    L("La Festa Disfraces", "https://lafestadisfraces.com/", "contacto@lafestadisfraces.com", "5552607406", "CDMX", "CDMX", "Fabricante/tienda", "Mayoreo infantil, Lago Texcoco 160", "research"),
    L("Disfraces Mancera", "https://disfracesmancera.com.mx/", "contacto@disfracesmancera.com.mx", "5555597641", "CDMX", "CDMX", "Mayoreo", "Pilares 401 Col. del Valle", "research"),
    L("El Famundi", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Fabricante", "+30 años, fantasía y regionales, Merced Balbuena", "research"),
    L("Disfraces DePeli", "https://disfracesdepeli.com/", "contacto@disfracesdepeli.com", "5583935960", "CDMX", "CDMX", "Tienda multi-sucursal", "Pedregal, Polanco, Miramontes", "research"),
    L("Disfraces DePeli Polanco", "https://disfracesdepeli.com/", "", "5552822742", "CDMX", "CDMX", "Sucursal", "Polanco", "research"),
    L("Disfraces DePeli Pedregal", "https://disfracesdepeli.com/", "", "5530893006", "CDMX", "CDMX", "Sucursal", "Plaza Pedregal", "research"),
    L("Disfraces DePeli Miramontes", "https://disfracesdepeli.com/", "", "5556784094", "CDMX", "CDMX", "Sucursal", "Miramontes", "research"),
    L("Disfraces ABACOR", "https://disfracesabacor.com/", "", "5529611113", "México", "México", "Fabricante mayoreo", "Diseño y confección Halloween", "research"),
    L("Ghoulish Productions", "https://ghoulishproductions.com.mx/", "", "7771645169", "Jiutepec", "Morelos", "Fabricante máscaras", "Máscaras y disfraces Halloween / Día de Muertos", "research"),
    L("Disfraces TuDi", "https://disfraces-tudi.com/", "", "5510569978", "CDMX", "CDMX", "Infantil mayoreo", "Av Centenario 394 Álvaro Obregón", "research"),
    L("La Casita de Disfraces", "http://lacasitadedisfraces.com.mx/", "", "5555986267", "CDMX", "CDMX", "Renta + venta", "+35 años, Pedregal / San José Insurgentes", "research"),
    L("La Casita de los Disfraces", "https://lacasitadelosdisfraces.com.mx/", "", "", "CDMX", "CDMX", "Renta + venta", "Av Toluca 475 Olivar de los Padres", "research"),
    L("Funidelia México", "https://www.funidelia.mx/", "", "", "México", "México", "Ecom mayoreo", "Disfraces adultos, niños y mascotas", "research"),
    L("Disfrazia", "https://www.disfrazia.com.mx/", "", "5555262563", "CDMX", "CDMX", "Tienda", "Disfraces y trajes regionales", "research"),
    L("Que Disfraces", "", "", "5555222783", "CDMX", "CDMX", "Tienda", "Centro CDMX", "research"),
    L("La Magia del Disfraz", "https://lamagiadeldisfraz.mx/", "", "5556784736", "CDMX", "CDMX", "Tienda", "Taxqueña 1530 Campestre Churubusco", "research"),
    L("Comienza la Función", "https://www.comienzalafuncion.com.mx/", "", "5555213037", "CDMX", "CDMX", "Tienda teatral", "Vestuario y disfraces", "research"),
    L("Disfraces y Fiestas Luza Peluza", "", "", "5521064025", "CDMX", "CDMX", "Tienda", "Fiestas y disfraces", "research"),
    L("Regalos y Disfraces ANITA", "", "", "55556326515", "CDMX", "CDMX", "Mayoreo mercado", "Mercado Carmen Serdán Coyoacán", "research"),
    L("Renta Disfraces", "https://rentadisfraces.com/", "", "5533992469", "CDMX", "CDMX", "Renta", "Polanco, San José Insurgentes, Del Valle", "research"),
    L("Botargas La Luciérnaga", "https://www.botargaslaluciernaga.com/", "", "", "Chimalhuacán", "EdoMex", "Fabricante botargas", "Disfraces voluminosos", "research"),
    L("Venta de Disfraces Fantasía", "https://www.ventadedisfracesfantasia.com/", "", "", "Cuautitlán Izcalli", "EdoMex", "Tienda", "Centro Urbano Izcalli", "research"),
    L("Tienda Disfraces Delmi", "", "disfracesdelmi@gmail.com", "5544491501", "CDMX", "CDMX", "Tienda", "Fuerza Aérea Mexicana 520", "research"),
    L("Disfraces Casa Emmanuel", "", "", "5540998810", "CDMX", "CDMX", "Mayoreo mercado", "Mercado Sonora Puerta 3 local 92", "research"),
    L("La Boutique del Disfraz Puebla", "", "", "2212425195", "Puebla", "Puebla", "Tienda", "Blvd Norte 3625 Plaza Los Gallos", "research"),
    L("Gabi Confecciones disfraces", "", "", "974773003", "México", "México", "Mayoreo confección", "Catálogo +100 disfraces Halloween", "research"),
    L("Disfraces Party Zone", "https://www.partyzonedisfraces.com/", "", "7228642693", "Toluca", "EdoMex", "Tienda + ecom", "+20 años, envíos nacionales", "research"),
    L("Distribuidora Muñoz Disfraces", "", "distmunoz@gmail.com", "8183745074", "Monterrey", "NL", "Fabricante", "Disfraces, mallas, leotardos — Carlos Salazar 338", "research"),
    L("El Remate del Disfraz", "", "elrematedeldisfraz@gmail.com", "8120953757", "Monterrey", "NL", "Renta + venta", "Temporada, precios económicos", "research"),
    L("Forever Kids GDL", "", "", "3329311002", "Guadalajara", "Jalisco", "Mayoreo infantil", "Pensador Mexicano 1973", "research"),
    L("Jhohans Kids disfraces", "", "", "3334899610", "Guadalajara", "Jalisco", "Mayoreo", "Disfraces de temporada, envíos nacionales", "research"),
    L("El mundo de la fantasía GDL", "", "", "3329487258", "Guadalajara", "Jalisco", "Tienda", "Niños y adultos", "research"),
    L("Showroom Pedro Loza disfraces", "", "", "3315286145", "Guadalajara", "Jalisco", "Showroom", "Pedro Loza 125 Centro", "research"),
    L("Sucursal Álvaro Obregón GDL disfraces", "", "", "", "Guadalajara", "Jalisco", "Sucursal", "Álvaro Obregón 583 — fiestas y disfraces", "research"),
    L("Marthas Renta de Disfraces", "", "", "6649046302", "Tijuana", "BC", "Renta", "Tijuana, sin envíos", "research"),
    L("Disfraces Mercado de Todos Tijuana", "", "", "6646217442", "Tijuana", "BC", "Tienda", "Blvd Díaz Ordaz 1665 — disfraces y maquillaje", "research"),
    L("Artist City disfraces", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Tienda teatral", "Vestuario danza, teatro y show", "research"),
    L("El Famundi sucursal Uruguay", "https://www.elfamundi.com.mx/", "", "5557640254", "CDMX", "CDMX", "Sucursal", "República de Uruguay 121 Centro", "research"),
    L("Mercado Sonora disfraces cluster", "", "", "5540998810", "CDMX", "CDMX", "Cluster mayoreo", "Múltiples locales de disfraces", "research"),
    L("Mercado Lagunilla disfraces vintage", "", "", "", "CDMX", "CDMX", "Cluster popular", "Vintage, folclor y regateo", "research"),
    L("Disfraces Halloween CDMX mayoreo", "", "", "", "CDMX", "CDMX", "Mayoreo temporada", "Canal Halloween", "research"),
    L("Disfraces Día de Muertos CDMX", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Temporada", "Catrinas y calacas", "research"),
    L("Disfraces navideños mayoreo GDL", "", "", "3329311002", "Guadalajara", "Jalisco", "Temporada", "Mayoreo navidad", "research"),
    L("Disfraces escolares México", "", "", "", "México", "México", "Canal escolar", "Obras, festivales, kermés", "research"),
    L("Disfraces de oficios y profesiones", "https://lamagiadeldisfraz.mx/", "", "5556784736", "CDMX", "CDMX", "Línea catálogo", "Oficios además de Halloween", "research"),
    L("Disfraces para mascotas Funidelia", "https://www.funidelia.mx/", "", "", "México", "México", "Línea mascotas", "Halloween pets", "research"),
    L("Disfraces bebé DePeli", "https://disfracesdepeli.com/", "contacto@disfracesdepeli.com", "5583935960", "CDMX", "CDMX", "Línea bebé", "Bebé, niño, niña, dama, caballero", "research"),
    L("Máscaras Ghoulish mayoreo", "https://ghoulishproductions.com.mx/", "", "7771645169", "Jiutepec", "Morelos", "Mayoreo máscaras", "Innovación y creatividad", "research"),
    L("Trajes regionales Elfamundi", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Línea regional", "Trajes típicos y fantasía", "research"),
    L("Disfraces carnaval Veracruz", "", "", "", "Veracruz", "Veracruz", "Cluster carnaval", "Comparsas y vestuario", "research"),
    L("Disfraces carnaval Mazatlán", "", "", "", "Mazatlán", "Sinaloa", "Cluster carnaval", "Comparsas y vestuario", "research"),
    L("Disfraces carnaval Mérida", "", "", "", "Mérida", "Yucatán", "Cluster carnaval", "Temporada regional", "research"),
    L("Disfraces Puebla centro", "", "", "2212425195", "Puebla", "Puebla", "Tienda regional", "Halloween y Día del Niño", "research"),
    L("Disfraces León Gto", "", "", "", "León", "Guanajuato", "Tienda regional", "Temporada y mayoreo", "research"),
    L("Disfraces Querétaro", "", "", "", "Querétaro", "Querétaro", "Tienda regional", "Renta y venta", "research"),
    L("Disfraces Cancún", "", "", "", "Cancún", "Q. Roo", "Tienda regional", "Hotelería y eventos", "research"),
    L("Disfraces Chihuahua", "", "", "", "Chihuahua", "Chihuahua", "Tienda regional", "Temporada norte", "research"),
    L("Disfraces Hermosillo", "", "", "", "Hermosillo", "Sonora", "Tienda regional", "Temporada norte", "research"),
    L("Disfraces Culiacán", "", "", "", "Culiacán", "Sinaloa", "Tienda regional", "Temporada", "research"),
    L("Disfraces Morelia", "", "", "", "Morelia", "Michoacán", "Tienda regional", "Temporada", "research"),
    L("Disfraces Oaxaca", "", "", "", "Oaxaca", "Oaxaca", "Tienda regional", "Temporada y Guelaguetza adyacente", "research"),
    L("Disfraces San Luis Potosí", "", "", "", "San Luis Potosí", "SLP", "Tienda regional", "Temporada", "research"),
    L("Disfraces Aguascalientes", "", "", "", "Aguascalientes", "Aguascalientes", "Tienda regional", "Feria y temporada", "research"),
    L("Disfraces Saltillo", "", "", "", "Saltillo", "Coahuila", "Tienda regional", "Temporada", "research"),
    L("Disfraces Torreón", "", "", "", "Torreón", "Coahuila", "Tienda regional", "Temporada", "research"),
    L("Disfraces Juárez", "", "", "", "Cd. Juárez", "Chihuahua", "Tienda fronteriza", "Temporada", "research"),
    L("Disfraces Mexicali", "", "", "", "Mexicali", "BC", "Tienda fronteriza", "Temporada", "research"),
    L("Disfraces Ensenada", "", "", "", "Ensenada", "BC", "Tienda regional", "Temporada", "research"),
    L("Disfraces Acapulco", "", "", "", "Acapulco", "Guerrero", "Tienda regional", "Turismo y temporada", "research"),
    L("Disfraces Tuxtla", "", "", "", "Tuxtla Gutiérrez", "Chiapas", "Tienda regional", "Temporada", "research"),
    L("Disfraces Villahermosa", "", "", "", "Villahermosa", "Tabasco", "Tienda regional", "Temporada", "research"),
    L("Disfraces Tampico", "", "", "", "Tampico", "Tamaulipas", "Tienda regional", "Temporada", "research"),
    L("Disfraces Reynosa", "", "", "", "Reynosa", "Tamaulipas", "Tienda fronteriza", "Temporada", "research"),
    L("Cosplay CDMX tiendas", "", "", "", "CDMX", "CDMX", "Canal cosplay", "Convenciones y ecom", "research"),
    L("Cosplay Guadalajara", "", "", "", "Guadalajara", "Jalisco", "Canal cosplay", "Convenciones", "research"),
    L("Cosplay Monterrey", "", "", "", "Monterrey", "NL", "Canal cosplay", "Convenciones", "research"),
    L("Botargas eventos CDMX", "https://www.botargaslaluciernaga.com/", "", "", "EdoMex", "EdoMex", "Fabricante", "Publicidad y eventos", "research"),
    L("Botargas GDL", "", "", "", "Guadalajara", "Jalisco", "Fabricante regional", "Eventos y publicidad", "research"),
    L("Botargas Monterrey", "", "", "", "Monterrey", "NL", "Fabricante regional", "Eventos y publicidad", "research"),
    L("Vestuario teatral CDMX", "https://www.comienzalafuncion.com.mx/", "", "5555213037", "CDMX", "CDMX", "Teatro", "Foros y compañías", "research"),
    L("Vestuario danza Artist City", "https://www.artistcity.com.mx/", "", "(55) 3547-6444", "CDMX", "CDMX", "Danza", "Ballet, jazz, show", "research"),
    L("Disfraces fiestas infantiles CDMX", "", "", "", "CDMX", "CDMX", "Canal infantil", "Cumpleaños y kermés", "research"),
    L("Disfraces XV años / temáticos", "", "", "", "CDMX", "CDMX", "Canal eventos", "Temáticos y fantasía", "research"),
    L("Disfraces corporativos / team building", "", "", "", "CDMX", "CDMX", "Canal B2B", "Eventos empresa", "research"),
    L("Disfraces hotelería Cancún", "", "", "", "Cancún", "Q. Roo", "Canal hotelero", "Shows y animación", "research"),
    L("Disfraces parques temáticos MX", "", "", "", "México", "México", "Canal entretenimiento", "Shows y personajes", "research"),
    L("Mercado Libre disfraces sellers MX", "https://listado.mercadolibre.com.mx/disfraces", "", "", "México", "México", "Marketplace", "Muchos vendedores MX; scrapear tiendas oficiales", "research"),
    L("Amazon MX disfraces sellers", "https://www.amazon.com.mx/s?k=disfraces", "", "", "México", "México", "Marketplace", "Sellers nacionales", "research"),
    L("Walmart MX disfraces temporada", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Canal temporada", "brand"),
    L("Coppel disfraces temporada", "https://www.coppel.com/", "", "", "México", "México", "Retail", "Canal temporada", "brand"),
    L("Liverpool disfraces / Halloween", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Canal departamental", "brand"),
    L("Party City estilo tiendas fiesta MX", "", "", "", "México", "México", "Fiesta + disfraz", "Globos, piñatas, disfraces", "research"),
    L("Piñaterías con disfraces CDMX", "", "", "", "CDMX", "CDMX", "Canal popular", "Piñatas + disfraces", "research"),
    L("Disfraces Mayoreo Centro CDMX", "", "", "5552607406", "CDMX", "CDMX", "Mayoreo centro", "Cluster de proveedores", "research"),
    L("Confeccionistas Halloween MX", "", "", "974773003", "México", "México", "Taller", "Mayoreo confección temporada", "research"),
    L("Disfraces pastorelas MX", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Temporada navidad", "Pastorelas y corpus", "research"),
    L("Disfraces primavera / corpus", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Temporada", "Calendario festivo MX", "research"),
    L("Disfraces tipicos Disfrazia", "https://www.disfrazia.com.mx/", "", "5555262563", "CDMX", "CDMX", "Línea regional", "Trajes típicos", "research"),
    L("Accesorios Halloween La Festa", "https://lafestadisfraces.com/", "contacto@lafestadisfraces.com", "5552607406", "CDMX", "CDMX", "Accesorios", "Pelucas, maquillaje, props", "research"),
    L("Pelucas disfraz Elfamundi", "https://www.elfamundi.com.mx/", "", "5555525294", "CDMX", "CDMX", "Accesorios", "Pelucas de colores y fantasía", "research"),
    L("Disfraces Mancera mayoristas web", "https://disfracesmancera.com.mx/home/", "contacto@disfracesmancera.com.mx", "5545010993", "CDMX", "CDMX", "Mayoreo web", "Registro RFC mayorista", "research"),
    L("Disfraces ABACOR WhatsApp mayoreo", "https://disfracesabacor.com/", "", "5529611113", "México", "México", "Mayoreo", "Alta calidad niños/adultos", "research"),
    L("DePeli preventa Halloween", "https://disfracesdepeli.com/", "contacto@disfracesdepeli.com", "5583935960", "CDMX", "CDMX", "Preventa", "Precios especiales temporada", "research"),
    L("Renta vs venta Casita", "http://lacasitadedisfraces.com.mx/", "", "5555986267", "CDMX", "CDMX", "Renta artesanal", "Hechos artesanales no industriales", "research"),
    L("Disfraces TuDi catálogo", "https://disfraces-tudi.com/", "", "5510569978", "CDMX", "CDMX", "Mayoreo catálogo", "Infantil por catálogo", "research"),
    L("Party Zone envíos nacionales", "https://www.partyzonedisfraces.com/", "", "7228642693", "Toluca", "EdoMex", "Ecom nacional", "Halloween, Día de Muertos, cosplay, escolares", "research"),
    L("Muñoz leotardos y mallas", "", "distmunoz@gmail.com", "8183745074", "Monterrey", "NL", "Línea danza", "Complemento disfraz/danza", "research"),
    L("Remate del Disfraz renta MTY", "", "elrematedeldisfraz@gmail.com", "8120953757", "Monterrey", "NL", "Renta económica", "Temporada alto volumen", "research"),
    L("Kids mayoreo GDL cluster", "", "", "3329311002", "Guadalajara", "Jalisco", "Cluster infantil", "Varios proveedores moda+disfraz", "research"),
    L("Disfraces Centro GDL Pedro Loza", "", "", "3315286145", "Guadalajara", "Jalisco", "Cluster centro", "3 sucursales centro", "research"),
    L("Tijuana renta Marthas", "", "", "6649046302", "Tijuana", "BC", "Renta local", "Sin envíos, tienda física", "research"),
    L("Tijuana Mercado de Todos", "", "", "6646217442", "Tijuana", "BC", "Tienda integral", "Disfraces + makeup + bromas", "research"),
    L("Puebla Casa Emmanuel contacto", "", "", "2224398360", "Puebla", "Puebla", "Tienda", "WhatsApp disfraces Puebla", "research"),
    L("Halloween props Ghoulish", "https://ghoulishproductions.com.mx/", "", "7771645169", "Morelos", "Morelos", "Props + máscaras", "Innovación MX", "research"),
    L("Disfraces ecom nacional Funidelia", "https://www.funidelia.mx/", "", "", "México", "México", "Ecom", "Pedidos web", "research"),
    L("My Kids línea infantil", "https://mykidsmx.com/", "", "", "México", "México", "Ecom infantil", "Ejemplo + catálogo kids", "research"),
    L("Disfraces mayoreo Iztapalapa", "", "", "", "Iztapalapa", "CDMX", "Mayoreo oriente", "Talleres y bodegas", "research"),
    L("Disfraces mayoreo Tepito", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Temporada centro", "research"),
    L("Disfraces mayoreo La Merced", "", "", "", "CDMX", "CDMX", "Mayoreo popular", "Cluster comercial", "research"),
    L("Confección disfraces Ecatepec", "", "", "", "Ecatepec", "EdoMex", "Taller", "Maquila temporada", "research"),
    L("Confección disfraces Nezahualcóyotl", "", "", "", "Neza", "EdoMex", "Taller", "Maquila temporada", "research"),
    L("Confección disfraces Toluca", "https://www.partyzonedisfraces.com/", "", "7228642693", "Toluca", "EdoMex", "Taller + tienda", "Estado de México", "research"),
    L("Disfraces universitarios / porras", "", "", "", "México", "México", "Canal educativo", "Porristas y teatro escolar", "research"),
    L("Disfraces deportivos / mascotas equipo", "", "", "", "México", "México", "Canal deportivo", "Botargas de equipos", "research"),
]

CES = [
    L("Regalos y Canastas", "https://www.regalosycanastas.mx/", "", "", "CDMX", "CDMX", "Ejemplo original", "Ejemplo del cliente", "ejemplo_cliente"),
    L("Arcones.mx / Canastas y Arcones", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Fabricante corporativo", "Miles de arcones/día, Polanco y Bajío", "research"),
    L("Canastas y Arcones MX", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "Naucalpan", "EdoMex", "B2B/B2C", "Arcones empresariales, logística nacional", "research"),
    L("Arcones Gourmet", "https://arconesgourmet.com/", "", "", "CDMX", "CDMX", "D2C gourmet", "Canastas gourmet CDMX artesanales", "research"),
    L("María Orsini", "https://mariaorsini.com.mx/", "", "", "CDMX", "CDMX", "Premium", "+40 años canastas premium CDMX", "research"),
    L("Rivenso Canastas", "https://rivenso.com/", "ventas@rivenso.com", "5584682011", "CDMX", "CDMX", "Gourmet ecom", "Calz. Legaria 24, envíos nacionales", "research"),
    L("Canastas.com", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Fabricante nacional", "1000+ opciones, WhatsApp 5524284169", "research"),
    L("Canastas Navideñas de México", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Corporativo", "CANASTAS NAVIDEÑAS MEXICO SA DE CV", "research"),
    L("Dendi / Canastas Navideñas", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "Ecom + B2B", "+5 años, logística y facturación", "research"),
    L("Canastas México", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5538588260", "Naucalpan", "EdoMex", "Ecom corporativo", "Precio de fábrica, Toreo", "research"),
    L("Regalos México arcones", "https://regalosmexico.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Portal grupo", "Misma operación Canastas y Arcones", "research"),
    L("Arcones corporativo Toreo", "https://arcones.mx/contact/", "ventas@arcones.mx", "5598165166", "Naucalpan", "EdoMex", "CD / corporativo", "Blvd Ávila Camacho 80 Int 204", "research"),
    L("Arcones Polanco CD", "https://arcones.mx/contact/", "ventas@canastasyarcones.mx", "5616545039", "Naucalpan", "EdoMex", "Centro distribución", "Calz San Esteban 18", "research"),
    L("Arcones Querétaro Bajío", "https://arcones.mx/contact/", "ventas@canastasyarcones.mx", "5598165166", "San Juan del Río", "Querétaro", "Sucursal Bajío", "Morelos Norte 29", "research"),
    L("Canastas.com Puebla", "https://canastas.com/canastas/arcones-empresariales/arcones-navidenos-puebla/", "contacto@canastas.com", "5599901630", "Puebla", "Puebla", "Cobertura regional", "Arcones gourmet Puebla", "research"),
    L("Canastas.com Monterrey", "https://canastas.com/canastas/regalo-corporativo/regalos-a-domicilio-monterrey/", "contacto@canastas.com", "5599901630", "Monterrey", "NL", "Cobertura regional", "Regalos a domicilio MTY", "research"),
    L("Canastas.com Querétaro", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Querétaro", "Querétaro", "Cobertura regional", "Arcones corporativos Qro", "research"),
    L("Canastas.com León", "https://canastas.com/", "contacto@canastas.com", "5599901630", "León", "Guanajuato", "Cobertura regional", "Canastas gourmet León", "research"),
    L("Canastas.com Guadalajara", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Guadalajara", "Jalisco", "Cobertura regional", "Arcones occidente", "research"),
    L("Canastas.com Cancún", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Cancún", "Q. Roo", "Cobertura regional", "Riviera Maya corporativo", "research"),
    L("Canastas.com Veracruz", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Veracruz", "Veracruz", "Cobertura regional", "Boca del Río / Xalapa", "research"),
    L("Canastas.com SLP", "https://canastas.com/", "contacto@canastas.com", "5599901630", "San Luis Potosí", "SLP", "Cobertura regional", "Arcones potosinos", "research"),
    L("Canastas.com Culiacán", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Culiacán", "Sinaloa", "Cobertura regional", "Sinaloa corporativo", "research"),
    L("Canastas.com Chihuahua", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Chihuahua", "Chihuahua", "Cobertura regional", "Chihuahua / Juárez", "research"),
    L("Canastas.com Morelia", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Morelia", "Michoacán", "Cobertura regional", "Michoacán gourmet", "research"),
    L("Canastas.com Hidalgo", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Pachuca", "Hidalgo", "Cobertura regional", "Arcones Pachuca", "research"),
    L("Liverpool arcones / canastas", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail departamental", "Canal corporativo/consumo", "brand"),
    L("Palacio de Hierro canastas", "https://www.elpalaciodehierro.com/", "", "", "CDMX", "CDMX", "Retail premium", "Canastas gourmet", "brand"),
    L("Sears arcones", "", "", "", "México", "México", "Retail", "Arcones temporada", "brand"),
    L("Sam's Club arcones", "https://www.sams.com.mx/", "", "", "México", "México", "Club de precio", "Canal mayoreo consumidor", "brand"),
    L("Costco canastas / gourmet", "https://www.costco.com.mx/", "", "", "México", "México", "Club de precio", "Canal gourmet", "brand"),
    L("Walmart arcones navidad", "https://www.walmart.com.mx/", "", "", "México", "México", "Retail", "Canal masivo", "brand"),
    L("La Comer / City Market gourmet baskets", "https://www.lacomer.com.mx/", "", "", "CDMX", "CDMX", "Supermercado premium", "Canastas gourmet", "brand"),
    L("Chedraui Selecto canastas", "https://www.chedraui.com.mx/", "", "", "México", "México", "Supermercado", "Temporada", "brand"),
    L("HEB canastas norte", "https://www.heb.com.mx/", "", "", "Monterrey", "NL", "Supermercado", "Canastas y gourmet norte", "brand"),
    L("Soriana canastas", "https://www.soriana.com/", "", "", "México", "México", "Retail", "Temporada", "brand"),
    L("Despensas El Fresno / canastas", "https://elfresnoexpress.com/", "", "", "EdoMex", "EdoMex", "Despensas + canastas", "Mayoreo CDMX/Edomex", "research"),
    L("Canastas empresariales GDL boutique", "", "", "", "Guadalajara", "Jalisco", "Boutique regional", "Regalos corporativos occidente", "research"),
    L("Canastas empresariales MTY boutique", "", "", "", "Monterrey", "NL", "Boutique regional", "Regalos corporativos norte", "research"),
    L("Canastas empresariales Puebla boutique", "", "", "", "Puebla", "Puebla", "Boutique regional", "Regalos corporativos", "research"),
    L("Canastas empresariales Qro boutique", "", "", "", "Querétaro", "Querétaro", "Boutique regional", "Regalos corporativos Bajío", "research"),
    L("Canastas empresariales León boutique", "", "", "", "León", "Guanajuato", "Boutique regional", "Regalos corporativos", "research"),
    L("Canastas empresariales Mérida boutique", "", "", "", "Mérida", "Yucatán", "Boutique regional", "Regalos sureste", "research"),
    L("Canastas empresariales Tijuana boutique", "", "", "", "Tijuana", "BC", "Boutique fronteriza", "Regalos corporativos", "research"),
    L("Canastas empresariales Cancún boutique", "", "", "", "Cancún", "Q. Roo", "Boutique hotelera", "Regalos turismo/corp", "research"),
    L("Vinos y canastas CDMX", "", "", "", "CDMX", "CDMX", "Línea vinos", "Canastas con vino y licor", "research"),
    L("Canastas con tequila", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "Línea tequila", "Canastas con destilados MX", "research"),
    L("Canastas de mimbre La Merced", "", "", "", "CDMX", "CDMX", "Insumos / armado", "Mimbre y carrizo mayoreo", "research"),
    L("Canastas de carrizo mayoreo", "", "", "", "CDMX", "CDMX", "Insumos", "Contenedores para arcones", "research"),
    L("Arcones de madera fabricantes", "", "", "", "México", "México", "Insumos empaque", "Cajas y arcones de madera", "research"),
    L("Moños y emplayado arcones", "", "", "", "CDMX", "CDMX", "Insumos packing", "Armado de canastas", "research"),
    L("Importadores vino para arcones", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Importador", "Vino, conservas, ibéricos", "research"),
    L("Regalos corporativos branding", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Personalización", "Logo, grabado, termos, agendas", "research"),
    L("Canastas deducibles de impuestos", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "B2B fiscal", "Regalos empresariales deducibles", "research"),
    L("Despensas navideñas corporativas", "", "", "", "CDMX", "CDMX", "Despensas", "Alternativa a arcones gourmet", "research"),
    L("Canastas económicas corporativas", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Línea económica", "Desde ~$199", "research"),
    L("Canastas premium / whisky", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Línea premium", "Arcón whisky & delicias", "research"),
    L("Canastas gourmet deluxe", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Línea deluxe", "Cestos gourmet", "research"),
    L("Envío de regalos a domicilio CDMX", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5538588260", "CDMX", "CDMX", "Logística", "Last mile regalos", "research"),
    L("Envío nacional arcones", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "México", "México", "Logística nacional", "Cobertura República", "research"),
    L("Canastas San Pedro Garza", "https://canastas.com/", "contacto@canastas.com", "5599901630", "San Pedro", "NL", "Cobertura premium norte", "Corporativos SPGG", "research"),
    L("Canastas Irapuato", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Irapuato", "Guanajuato", "Cobertura Bajío", "Regalos empresariales", "research"),
    L("Canastas Celaya", "", "", "", "Celaya", "Guanajuato", "Boutique regional", "Bajío industrial", "research"),
    L("Canastas Aguascalientes", "", "", "", "Aguascalientes", "Aguascalientes", "Boutique regional", "Corporativos Ags", "research"),
    L("Canastas Toluca", "", "", "", "Toluca", "EdoMex", "Boutique regional", "Corporativos EdoMex", "research"),
    L("Canastas Cuernavaca", "", "", "", "Cuernavaca", "Morelos", "Boutique regional", "Regalos Morelos", "research"),
    L("Canastas Pachuca", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5598165166", "Pachuca", "Hidalgo", "Cobertura", "Venta de arcones Pachuca", "research"),
    L("Canastas Xalapa", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Xalapa", "Veracruz", "Cobertura", "Gourmet Veracruz", "research"),
    L("Canastas Boca del Río", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Boca del Río", "Veracruz", "Cobertura", "Corporativos puerto", "research"),
    L("Canastas Playa del Carmen", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Playa del Carmen", "Q. Roo", "Cobertura", "Premium Riviera", "research"),
    L("Canastas Mazatlán", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Mazatlán", "Sinaloa", "Cobertura", "Turismo + corp", "research"),
    L("Canastas Juárez", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Cd. Juárez", "Chihuahua", "Cobertura fronteriza", "Arcones con vinos", "research"),
    L("Canastas Hermosillo", "", "", "", "Hermosillo", "Sonora", "Boutique regional", "Noroeste", "research"),
    L("Canastas Culiacán boutique", "", "", "", "Culiacán", "Sinaloa", "Boutique regional", "Noroeste", "research"),
    L("Canastas Oaxaca gourmet", "", "", "", "Oaxaca", "Oaxaca", "Boutique regional", "Productos artesanales locales", "research"),
    L("Canastas Chiapas café/chocolate", "", "", "", "Tuxtla Gutiérrez", "Chiapas", "Boutique regional", "Origen local", "research"),
    L("Canastas Yucatán gourmet", "", "", "", "Mérida", "Yucatán", "Boutique regional", "Productos península", "research"),
    L("Canastas artesanales CDMX", "https://arconesgourmet.com/", "", "", "CDMX", "CDMX", "Artesanal", "Productos MX", "research"),
    L("Canastas corporativas Forbes-cited", "https://regalosmexico.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Marca líder", "Mencionados por Forbes / Fórmula", "research"),
    L("Capacidad miles de arcones/día", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Capacidad fábrica", "Alto volumen B2B", "research"),
    L("Personalización branding arcones", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "Naucalpan", "EdoMex", "Servicio B2B", "Colores, logos, mensajes", "research"),
    L("5,000 productos para armar", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "Naucalpan", "EdoMex", "Catálogo insumos", "Armado a la medida", "research"),
    L("Precios de fábrica arcones", "https://arcones.mx/", "ventas@arcones.mx", "5598165166", "Naucalpan", "EdoMex", "Mayoreo fábrica", "Descuentos por volumen", "research"),
    L("Canastas Rivenso 10% cupón canal", "https://rivenso.com/", "ventas@rivenso.com", "5515541137", "CDMX", "CDMX", "Ecom", "Oficina + móvil", "research"),
    L("Rivenso Ixtapaluca CD", "https://rivenso.com/", "ventas@rivenso.com", "5584682011", "Ixtapaluca", "EdoMex", "Centro distribución", "Calz Acozac", "research"),
    L("Canastas gourmet Polanco 5 min", "https://rivenso.com/", "ventas@rivenso.com", "5584682011", "Miguel Hidalgo", "CDMX", "Showroom", "Cerca de Polanco", "research"),
    L("Arcones empresariales 2026 catálogo", "https://canastas.com/", "contacto@canastas.com", "5524284169", "CDMX", "CDMX", "Catálogo temporada", "WhatsApp ventas", "research"),
    L("Regalos sorpresa a domicilio", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5538588260", "CDMX", "CDMX", "Ecom regalos", "No solo navidad", "research"),
    L("Estuches gourmet madera", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5538588260", "Naucalpan", "EdoMex", "Línea estuche", "Vault de madera", "research"),
    L("Sets para hombre gourmet", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5538588260", "Naucalpan", "EdoMex", "Línea género", "Regalos ejecutivos", "research"),
    L("Canastas de vinos para regalo", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Línea vinos", "Corporativo", "research"),
    L("Arcones productos de tocador", "https://canastasmexico.mx/", "ventas@canastasmexico.mx", "5598165166", "Naucalpan", "EdoMex", "Línea wellness", "No solo alimentos", "research"),
    L("Canastas para secretarios / gobierno", "https://canastasmexico.mx/", "", "5598165166", "CDMX", "CDMX", "Canal gobierno", "Protocolo", "research"),
    L("Canastas familiares navidad", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "B2C", "Menudeo temporada", "research"),
    L("Canastas para socios / clientes", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "B2B", "Relación comercial", "research"),
    L("Canastas para colaboradores", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "B2B RH", "Prestaciones fin de año", "research"),
    L("Logística puntual arcones", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "México", "México", "Operador logístico propio", "Entregas masivas diciembre", "research"),
    L("Facturación canastas Dendi", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "PyME ecom", "Atención punta a punta", "research"),
    L("Canasta Caballeros Dendi", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "SKU premium", "Línea alta", "research"),
    L("Canasta Cristal Dendi", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "SKU premium", "Con tequila", "research"),
    L("Canasta Fiel / Celeste Dendi", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "SKU mid", "Línea media", "research"),
    L("Arcón Degustación Canastas.com", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "SKU", "Variedad y estilos", "research"),
    L("Caja Sabores Exóticos", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "SKU", "Importados + locales", "research"),
    L("Arcón Lujo set vinícola español", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "SKU premium", "Vinos España", "research"),
    L("Canastas con productos locales Puebla", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Puebla", "Puebla", "Línea local", "Productores Puebla", "research"),
    L("Canastas Cholula", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Cholula", "Puebla", "Cobertura", "Personalizadas", "research"),
    L("Regalos fin de año Qro", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Querétaro", "Querétaro", "Temporada Bajío", "Empresas Qro", "research"),
    L("Canastas gourmet entrega Qro", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Querétaro", "Querétaro", "Last mile", "Bajío", "research"),
    L("Arcones corporativos NL", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Monterrey", "NL", "B2B norte", "Empresas Nuevo León", "research"),
    L("Canastas premium SPGG", "https://canastas.com/", "contacto@canastas.com", "5599901630", "San Pedro", "NL", "Premium norte", "San Pedro Garza García", "research"),
    L("Gourmet Nuevo León", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Monterrey", "NL", "Gourmet norte", "Productos premium", "research"),
    L("Canastas Acapulco", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Acapulco", "Guerrero", "Cobertura", "Turismo + corp", "research"),
    L("Venta arcones Toluca", "https://canastas.com/", "contacto@canastas.com", "5599901630", "Toluca", "EdoMex", "Cobertura", "EdoMex industrial", "research"),
    L("Canasta básica / despensa", "https://canastas.com/", "contacto@canastas.com", "5599901630", "México", "México", "Línea despensa", "Alternativa económica", "research"),
    L("Arcones centro CDMX", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Cobertura centro", "Entrega centro histórico", "research"),
    L("Tiendas regalos CDMX mayoreo", "https://canastas.com/", "contacto@canastas.com", "5524284169", "CDMX", "CDMX", "Mayoreo tiendas", "Reventa", "research"),
    L("Detalles para clientes oficina", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "CDMX", "CDMX", "B2B detalles", "No solo navidad", "research"),
    L("Regalos de cumpleaños empresas", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "CDMX", "CDMX", "B2B all-year", "Programa anual de regalos", "research"),
    L("Canastas San Miguel Chapultepec zona", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "CDMX", "CDMX", "Zona entrega", "Poniente CDMX", "research"),
    L("Canastas Satélite", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Zona entrega", "Satélite / Toreo", "research"),
    L("Puebla regalos a domicilio", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Puebla", "Puebla", "Last mile", "Portal grupo", "research"),
    L("Alianza / catálogo arcones", "", "", "", "México", "México", "Canal", "Catálogos compartidos temporada", "research"),
    L("Arcones La Gourmet", "", "", "", "México", "México", "Marca / línea", "Línea gourmet retail", "research"),
    L("Canastas Lomas", "", "", "", "CDMX", "CDMX", "Zona premium", "Lomas de Chapultepec", "research"),
    L("Regalos empresariales originales", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Posicionamiento", "Diferenciación vs retail", "research"),
    L("Importación directa vinos arcones", "https://regalosmexico.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Importador", "Ahorro de costos B2B", "research"),
    L("Entrega inmediata arcones", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Operación", "Stock temporada", "research"),
    L("Envíos gratis promociones", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "México", "México", "Promo logística", "Temporada", "research"),
    L("Canastas 100% deducibles", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5598165166", "Naucalpan", "EdoMex", "Fiscal", "Argumento B2B", "research"),
    L("RFC CAR1709188V6 Canastas y Arcones", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "Naucalpan", "EdoMex", "Razón social", "51-200 empleados", "research"),
    L("WhatsApp ventas arcones 56 1654 5039", "https://arcones.mx/", "ventas@canastasyarcones.mx", "5616545039", "Naucalpan", "EdoMex", "Canal WhatsApp", "Atención comercial", "research"),
    L("WhatsApp Canastas.com 55 2428 4169", "https://canastas.com/", "contacto@canastas.com", "5524284169", "CDMX", "CDMX", "Canal WhatsApp", "Cotizaciones", "research"),
    L("Canastas.com TikTok / redes", "https://canastas.com/", "contacto@canastas.com", "5599901630", "CDMX", "CDMX", "Marca digital", "Presencia multi-red", "research"),
    L("Canastas y Arcones Instagram", "https://canastasyarcones.mx/", "ventas@canastasyarcones.mx", "5571596103", "Naucalpan", "EdoMex", "Marca digital", "@arconesmx", "research"),
    L("Rivenso Instagram / ecom", "https://rivenso.com/", "ventas@rivenso.com", "5584682011", "CDMX", "CDMX", "Marca digital", "Cupones y catálogo", "research"),
    L("Dendi Facebook / ecom", "https://canastanavidenas.com/", "ventas@dendi.mx", "5531152282", "CDMX", "CDMX", "Marca digital", "PyME ágil", "research"),
    L("María Orsini premium legado", "https://mariaorsini.com.mx/", "", "", "CDMX", "CDMX", "Premium legado", "Marca de tradición CDMX", "research"),
    L("Arcones Gourmet artesanal MX", "https://arconesgourmet.com/", "", "", "CDMX", "CDMX", "Artesanal D2C", "Productos artesanales mexicanos", "research"),
    L("Regalos y Canastas ejemplo cliente", "https://www.regalosycanastas.mx/", "", "", "CDMX", "CDMX", "Referencia", "Seed original", "ejemplo_cliente"),
]


def main():
    print("Generating lotes 06-08…")
    dump_seeds("06", "maquillaje_artistico", "Maquillaje artístico, body paint, FX y caracterización MX", MAQ)
    dump_seeds("07", "disfraces", "Disfraces mayoreo/renta/ecom México", DIS)
    dump_seeds("08", "cestas_de_regalo", "Canastas, arcones y regalos corporativos MX", CES)
    print(f"counts: 06={len(MAQ)} 07={len(DIS)} 08={len(CES)}")


if __name__ == "__main__":
    main()
