#!/usr/bin/env python3
"""Generate seeds for lotes 15 tattoo supply and 16 invitaciones (200-300)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def L(empresa, url="", email="", tel="", ciudad="", estado="", tipo="", notas="", fuente="research"):
    d = {"empresa": empresa, "tipo": tipo, "notas": notas, "fuente": fuente}
    if url:
        d["url"] = url
    if email:
        d["email"] = email
    if tel:
        d["telefono"] = tel
    if ciudad:
        d["ciudad"] = ciudad
    if estado:
        d["estado"] = estado
    return d


def dump(lote, slug, desc, leads):
    path = ROOT / "config" / "seeds" / f"{lote}_{slug}.json"
    path.write_text(
        json.dumps({"lote": lote, "slug": slug, "description": desc, "leads": leads}, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"  {path.name}: {len(leads)} seeds")


TATTOO = [
    L("Soulflower", "https://soulflower.mx/", "soulflowercustom@gmail.com", "5545127515", "CDMX", "CDMX", "Ejemplo original", "Ejemplo del cliente — estudio + supply Condesa", "ejemplo_cliente"),
    L("Zebra Tattoo Supply", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Mayoreo nacional", "N. Héroes 2, EZ, cartuchos, PMU, envíos MX", "research"),
    L("Inkside Supply", "https://inksidesupply.com/", "ventas@inksidesupply.com", "5510480496", "CDMX", "CDMX", "Tienda CDMX", "Mar Jónico 50 Popotla — tintas y cartuchos", "research"),
    L("Tarmex Tattoo Supply", "https://tarmex-vip.com/", "ventas@tarmex-vip.com", "(55) 6278-6666", "CDMX", "CDMX", "Mayoreo", "Liverpool 104 Juárez — WA mayoreo 5565426736", "research"),
    L("AGMA Tattoo Supply", "https://agmatattoo.com/", "", "7711691599", "Pachuca", "Hidalgo", "Proveedor", "Rojo Gómez 1019 Cubitos", "research"),
    L("Daruma Supply Tattoo", "https://www.darumasupplytattoo.com/", "castillo.aguil4@gmail.com", "5519649709", "CDMX", "CDMX", "Multi-sucursal", "Hojalatería 29 Morelos + Neza + Puebla", "research"),
    L("Reyes Tattoo Supply", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Estudio + supply", "Tepeyac 930 Chapalita, +30 años, Indio Reyes", "research"),
    L("Make Art Supply", "https://makeartsupply.com/", "", "", "México", "México", "Tattoo supply", "Insumos profesionales tatuadores", "research"),
    L("Soulflower Hidalgo GDL extra", "", "", "", "Guadalajara", "Jalisco", "Sucursal supply", "Hidalgo 811 — soulflowertattoosupply", "research"),
    L("Soulflower Condesa extra", "https://soulflower.mx/", "soulflowercustom@gmail.com", "5589544434", "CDMX", "CDMX", "Estudio + shop", "Av Tamaulipas 104 2o piso", "research"),
    L("Zebra PMU extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Línea PMU", "Micropigmentación", "research"),
    L("Zebra EZ / Bronc extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Máquinas", "Rotativas", "research"),
    L("Inkside tintas extra", "https://inksidesupply.com/", "ventas@inksidesupply.com", "5510480496", "CDMX", "CDMX", "Tintas", "Dynamic / Revolution", "research"),
    L("Inkside EZ cartuchos extra", "https://inksidesupply.com/", "ventas@inksidesupply.com", "5510480496", "CDMX", "CDMX", "Cartuchos", "EZ / Inkin Revo", "research"),
    L("Tarmex menudeo extra", "https://tarmex-vip.com/", "ventas@tarmex-vip.com", "5565426735", "CDMX", "CDMX", "Menudeo", "WA", "research"),
    L("Tarmex distribuidores extra", "https://tarmex-vip.com/", "ventas@tarmex-vip.com", "5588002099", "CDMX", "CDMX", "Mayoristas", "Sé distribuidor", "research"),
    L("Tarmex seminarios extra", "https://tarmex-vip.com/", "", "(55) 6725-0506", "CDMX", "CDMX", "Educación", "Imperial seminario", "research"),
    L("AGMA Pachuca extra", "https://agmatattoo.com/", "", "7714267166", "Pachuca", "Hidalgo", "2o teléfono", "Hidalgo", "research"),
    L("Daruma Neza extra", "https://www.darumasupplytattoo.com/contacto", "", "5519649709", "Nezahualcóyotl", "EdoMex", "Sucursal", "Pantitlán 40", "research"),
    L("Daruma Puebla Soles extra", "https://www.darumasupplytattoo.com/contacto", "", "2224071643", "Puebla", "Puebla", "Sucursal", "Plaza Soles / El Carmen", "research"),
    L("Reyes Supply Zapopan extra", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3320031187", "Zapopan", "Jalisco", "Tienda", "Chapalita", "research"),
    L("Reyes kits inicio extra", "https://www.reyestattoosupply.com/collections/kit", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Kits", "Envío >$2500 gratis", "research"),
    L("Bishop oficial Reyes extra", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Marca", "Distribuidor oficial", "research"),
    L("Dynamic Black canal extra", "", "", "", "México", "México", "Tinta", "Vía supplies MX", "brand"),
    L("Eternal Ink canal extra", "", "", "", "México", "México", "Tinta", "Retail supply", "brand"),
    L("World Famous Ink extra", "", "", "", "México", "México", "Tinta", "Retail", "brand"),
    L("Intenze extra", "", "", "", "México", "México", "Tinta", "Retail", "brand"),
    L("Solid Ink extra", "", "", "", "México", "México", "Tinta", "Retail", "brand"),
    L("Radiant Colors extra", "", "", "", "México", "México", "Tinta", "Retail", "brand"),
    L("Cheyenne extra", "", "", "", "México", "México", "Máquinas", "Retail supply", "brand"),
    L("FK Irons extra", "", "", "", "México", "México", "Máquinas", "Retail", "brand"),
    L("Bishop Rotary extra", "", "", "", "México", "México", "Máquinas", "Reyes / otros", "brand"),
    L("EZ Tattoo extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Máquinas", "Zebra", "research"),
    L("Dragonhawk extra", "", "", "", "México", "México", "Máquinas", "Mayoreo", "brand"),
    L("Critical power extra", "", "", "", "México", "México", "Fuentes", "Retail", "brand"),
    L("Cartuchos membrana extra", "", "", "", "México", "México", "Consumible", "Seguridad", "research"),
    L("Aguijas tradicionales extra", "", "", "", "México", "México", "Consumible", "Barras", "research"),
    L("Tubos y grips extra", "", "", "", "México", "México", "Consumible", "Estudio", "research"),
    L("Fuentes de poder extra", "", "", "", "México", "México", "Equipo", "Digital", "research"),
    L("Pedales extra", "", "", "", "México", "México", "Equipo", "Estudio", "research"),
    L("Clipcord / RCA extra", "", "", "", "México", "México", "Cableado", "Estudio", "research"),
    L("Piel sintética práctica extra", "", "", "", "México", "México", "Práctica", "Escuelas", "research"),
    L("Anestesias / TKTX extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Cuidado piel", "Uso profesional", "research"),
    L("Aftercare / cremas extra", "", "", "", "México", "México", "Cuidado", "Hustle Butter estilo", "research"),
    L("Green soap / stencil extra", "", "", "", "México", "México", "Consumible", "Higiene", "research"),
    L("Guantes nitrilo extra", "", "", "", "México", "México", "Médico", "Insumo", "research"),
    L("Barreras / film extra", "", "", "", "México", "México", "Bioseguridad", "Estudio", "research"),
    L("Tapetes dentales extra", "", "", "", "México", "México", "Bioseguridad", "Estación", "research"),
    L("Autoclave / ultrasonido extra", "", "", "", "México", "México", "Esterilización", "Estudios", "research"),
    L("Camillas tattoo extra", "", "", "", "México", "México", "Mobiliario", "Daruma línea", "research"),
    L("Lámparas LED estudio extra", "", "", "", "México", "México", "Mobiliario", "Estudio", "research"),
    L("Carritos / estaciones extra", "", "", "", "México", "México", "Mobiliario", "Estudio", "research"),
    L("Piercing supply extra", "https://soulflower-3.myshopify.com/", "", "", "México", "México", "Piercing", "Soulflower shop", "research"),
    L("Joyería piercing extra", "", "", "", "México", "México", "Piercing", "Implant grade", "research"),
    L("PMU cejas labios extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "PMU", "Micropigmento", "research"),
    L("Pigmentos PMU extra", "", "", "", "México", "México", "PMU", "Cejas", "research"),
    L("Agujas PMU extra", "", "", "", "México", "México", "PMU", "Cartuchos", "research"),
    L("Escuelas de tatuaje CDMX extra", "", "", "", "CDMX", "CDMX", "Educación", "Cursos", "research"),
    L("Escuelas de tatuaje GDL extra", "", "", "", "Guadalajara", "Jalisco", "Educación", "Reyes zona", "research"),
    L("Escuelas de tatuaje MTY extra", "", "", "", "Monterrey", "NL", "Educación", "Cursos", "research"),
    L("Convenciones tattoo MX extra", "", "", "", "México", "México", "Evento", "Expo", "research"),
    L("Mexico City Tattoo Convention extra", "", "", "", "CDMX", "CDMX", "Evento", "Expo", "research"),
    L("Estudios tatuaje CDMX cluster", "", "", "", "CDMX", "CDMX", "Canal B2B", "Compran insumos", "research"),
    L("Estudios tatuaje GDL cluster", "", "", "", "Guadalajara", "Jalisco", "Canal B2B", "Compran insumos", "research"),
    L("Estudios tatuaje MTY cluster", "", "", "", "Monterrey", "NL", "Canal B2B", "Compran insumos", "research"),
    L("Estudios tatuaje Tijuana extra", "", "", "", "Tijuana", "BC", "Canal B2B", "Frontera", "research"),
    L("Estudios tatuaje Puebla extra", "", "", "", "Puebla", "Puebla", "Canal B2B", "Daruma zona", "research"),
    L("Estudios tatuaje Cancún extra", "", "", "", "Cancún", "Q. Roo", "Canal B2B", "Turismo", "research"),
    L("Mayoreo Plaza tattoo CDMX extra", "", "", "", "CDMX", "CDMX", "Cluster", "Centro / Juárez", "research"),
    L("Envíos nacionales Zebra extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Logística", "32 estados", "research"),
    L("Envíos Reyes extra", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Logística", "CDMX MTY TIJ PUE", "research"),
    L("Amazon MX tattoo extra", "https://www.amazon.com.mx/s?k=insumos+tatuaje", "", "", "México", "México", "Marketplace", "Sellers", "research"),
    L("ML tattoo supply extra", "https://listado.mercadolibre.com.mx/insumos-tatuaje", "", "", "México", "México", "Marketplace", "Tiendas", "research"),
    L("Importadores USA frontera extra", "", "", "", "Tijuana", "BC", "Import", "Supply US", "research"),
    L("Bioseguridad COFEPRIS extra", "", "", "", "México", "México", "Norma", "Estudios", "research"),
    L("Desechables grado médico extra", "", "", "", "México", "México", "Médico", "Insumo", "research"),
    L("Tinta negra liner extra", "", "", "", "México", "México", "Tinta", "Liner", "research"),
    L("Tinta negra shader extra", "", "", "", "México", "México", "Tinta", "Sombra", "research"),
    L("Set colores básico extra", "", "", "", "México", "México", "Tinta", "Kits", "research"),
    L("White ink extra", "", "", "", "México", "México", "Tinta", "Highlight", "research"),
    L("Máquinas coil extra", "", "", "", "México", "México", "Coil", "Tradicional", "research"),
    L("Máquinas pen extra", "", "", "", "México", "México", "Pen", "Rotativa", "research"),
    L("Wireless pen extra", "", "", "", "México", "México", "Wireless", "Batería", "research"),
    L("Baterías RCA extra", "", "", "", "México", "México", "Power", "Portátil", "research"),
    L("Grip covers extra", "", "", "", "México", "México", "Consumible", "Higiene", "research"),
    L("Vaselina / ointment extra", "", "", "", "México", "México", "Cuidado", "Sesión", "research"),
    L("Papel hectográfico extra", "", "", "", "México", "México", "Stencil", "Transfer", "research"),
    L("Máquinas transfer extra", "", "", "", "México", "México", "Equipo", "Stencil printer", "research"),
    L("iPad / iPad stand estudio extra", "", "", "", "México", "México", "Diseño", "Referencia", "research"),
    L("Portafolios / aftercare cards extra", "", "", "", "México", "México", "Branding", "Estudio", "research"),
    L("Merch estudio extra", "", "", "", "México", "México", "Adyacente", "Playeras", "research"),
    L("Alquiler sillas tattoo extra", "", "", "", "CDMX", "CDMX", "Renta", "Convenciones", "research"),
    L("Guest artist kits extra", "", "", "", "México", "México", "Paquete", "Viaje", "research"),
    L("Kits aprendiz extra", "https://www.reyestattoosupply.com/collections/kit", "", "3331088920", "Zapopan", "Jalisco", "Paquete", "Inicio", "research"),
    L("Refacciones motores extra", "", "", "", "México", "México", "Refacción", "Máquinas", "research"),
    L("Resortes coil extra", "", "", "", "México", "México", "Refacción", "Coil", "research"),
    L("Needles bars extra", "", "", "", "México", "México", "Consumible", "Tradicional", "research"),
    L("Tips desechables extra", "", "", "", "México", "México", "Consumible", "Tips", "research"),
    L("Ink caps extra", "", "", "", "México", "México", "Consumible", "Sesión", "research"),
    L("Bolsas autoclave extra", "", "", "", "México", "México", "Esterilización", "Estudios coil", "research"),
    L("Indicadores biológicos extra", "", "", "", "México", "México", "Esterilización", "Norma", "research"),
    L("Contenedores RPBI extra", "", "", "", "México", "México", "RPBI", "Agujas", "research"),
    L("Recolección RPBI extra", "", "", "", "México", "México", "Servicio", "Estudios", "research"),
    L("Seguros responsabilidad extra", "", "", "", "México", "México", "Servicio", "Estudios", "research"),
    L("Software cita tattoo extra", "", "", "", "México", "México", "SaaS", "Estudios", "research"),
    L("Fotografía healed extra", "", "", "", "México", "México", "Servicio", "Portafolio", "research"),
    L("Cover-up insumos extra", "", "", "", "México", "México", "Técnica", "Tintas opacas", "research"),
    L("Blackwork insumos extra", "", "", "", "México", "México", "Estilo", "Negros", "research"),
    L("Fine line insumos extra", "", "", "", "México", "México", "Estilo", "Cartuchos RL", "research"),
    L("Realismo insumos extra", "", "", "", "México", "México", "Estilo", "Grises", "research"),
    L("Tradicional insumos extra", "", "", "", "México", "México", "Estilo", "Bold", "research"),
    L("Lettering insumos extra", "", "", "", "México", "México", "Estilo", "Liner", "research"),
    L("Geometric insumos extra", "", "", "", "México", "México", "Estilo", "Precisión", "research"),
    L("Watercolor insumos extra", "", "", "", "México", "México", "Estilo", "Color", "research"),
    L("Dotwork insumos extra", "", "", "", "México", "México", "Estilo", "Agujas", "research"),
    L("Stick and poke extra", "", "", "", "México", "México", "DIY/pro", "Kits", "research"),
    L("Handpoke supply extra", "", "", "", "México", "México", "Handpoke", "Agujas", "research"),
    L("Scarification adyacente extra", "", "", "", "México", "México", "Body art", "Nicho", "research"),
    L("Implantes / body mod extra", "", "", "", "México", "México", "Body mod", "Nicho", "research"),
    L("Anestesia tópica extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Tópico", "Profesional", "research"),
    L("Numbing second pass extra", "", "", "", "México", "México", "Tópico", "Sesiones largas", "research"),
    L("Vaseline petrolatum extra", "", "", "", "México", "México", "Cuidado", "Sesión", "research"),
    L("Second skin film extra", "", "", "", "México", "México", "Aftercare", "Saniderm estilo", "research"),
    L("Jabón neutro aftercare extra", "", "", "", "México", "México", "Aftercare", "Retail", "research"),
    L("Bloqueador solar tattoo extra", "", "", "", "México", "México", "Aftercare", "Retail", "research"),
    L("Liverpool Juárez Tarmex extra", "https://tarmex-vip.com/", "ventas@tarmex-vip.com", "(55) 6278-6666", "CDMX", "CDMX", "Ubicación", "Col. Juárez", "research"),
    L("Popotla Inkside extra", "https://inksidesupply.com/", "ventas@inksidesupply.com", "5510480496", "CDMX", "CDMX", "Ubicación", "Miguel Hidalgo", "research"),
    L("Tultitlán Zebra extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Planta/tienda", "CP 54942", "research"),
    L("Chapalita Reyes extra", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Ubicación", "45040", "research"),
    L("Morelos Daruma extra", "https://www.darumasupplytattoo.com/", "", "5519649709", "CDMX", "CDMX", "Ubicación", "Venustiano Carranza", "research"),
    L("Cubitos Pachuca AGMA extra", "https://agmatattoo.com/", "", "7711691599", "Pachuca", "Hidalgo", "Ubicación", "42090", "research"),
    L("Condesa Soulflower extra", "https://soulflower.mx/", "soulflowercustom@gmail.com", "5545127515", "CDMX", "CDMX", "Ubicación", "Cuauhtémoc", "research"),
    L("Hidalgo 811 GDL extra", "", "", "", "Guadalajara", "Jalisco", "Ubicación", "Soulflower supply", "research"),
    L("Facebook Soulflower extra", "https://www.facebook.com/SoulflowerMX/", "soulflowercustom@gmail.com", "5589544434", "CDMX", "CDMX", "Canal", "Estudio", "research"),
    L("Shopify Soulflower extra", "https://soulflower-3.myshopify.com/", "", "", "México", "México", "Ecom", "Material + piercing", "research"),
    L("TikTok Soulflower supply extra", "", "", "", "Guadalajara", "Jalisco", "Canal digital", "Supply GDL", "research"),
    L("Instagram Zebra extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Canal", "@zebra_tattoo_supply", "research"),
    L("Instagram Reyes extra", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Canal", "@reyestattoosupply", "research"),
    L("FAQ Zebra extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Soporte", "Uso profesional", "research"),
    L("Políticas envío Zebra extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Logística", "Nacional", "research"),
    L("Cómo comprar Reyes extra", "https://www.reyestattoosupply.com/", "", "3331088920", "Zapopan", "Jalisco", "Soporte", "Ecom", "research"),
    L("Horario Reyes tienda extra", "https://www.reyestattoosupply.com/", "", "3331088920", "Zapopan", "Jalisco", "Operación", "L-S 11-8", "research"),
    L("Horario Daruma extra", "https://www.darumasupplytattoo.com/contacto", "", "5519649709", "CDMX", "CDMX", "Operación", "L-V 9-6 S 9-3", "research"),
    L("Horario Zebra extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Operación", "9-17", "research"),
    L("Precios IVA Reyes extra", "https://www.reyestattoosupply.com/", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Fiscal", "MXN + IVA", "research"),
    L("Distribuidores oficiales Reyes extra", "https://www.reyestattoosupply.com/pages/nosotros", "ventas@reyestattoosupply.com", "3331088920", "Zapopan", "Jalisco", "Canal", "Directo fabricante", "research"),
    L("Tatuajes de Reyes estudio extra", "https://www.reyestattoosupply.com/", "", "3331088920", "Zapopan", "Jalisco", "Estudio", "Indio Reyes", "research"),
    L("Make Art Supply ecom extra", "https://makeartsupply.com/", "", "", "México", "México", "Ecom", "Profesional", "research"),
    L("Inkside complementos extra", "https://inksidesupply.com/", "ventas@inksidesupply.com", "5510480496", "CDMX", "CDMX", "Complementos", "Médicos", "research"),
    L("Inkside Vselect extra", "https://inksidesupply.com/", "ventas@inksidesupply.com", "5510480496", "CDMX", "CDMX", "Cartuchos", "Vselect", "research"),
    L("Zebra Paganini extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Máquinas", "Paganini", "research"),
    L("Zebra fuentes digitales extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Fuentes", "Digitales", "research"),
    L("Cartuchos universales Zebra extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Cartuchos", "Membrana", "research"),
    L("Cremas previas Zebra extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Cuidado", "Pre-tattoo", "research"),
    L("Manuales Zebra extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Soporte", "Productos", "research"),
    L("Caducidad TKTX extra", "https://zebratattoosupply.com/", "", "5541880654", "Tultitlán", "EdoMex", "Norma", "Tópico", "research"),
    L("Visa pagos Zebra extra", "https://zebratattoosupply.com/", "ventas@zebratattoosupply.com", "5541880654", "Tultitlán", "EdoMex", "Pagos", "Tarjeta", "research"),
]

INV = [
    L("Paradisa Print", "https://paradisaprint.com/", "", "9999269331", "Mérida", "Yucatán", "Ejemplo original", "Ejemplo del cliente — Calle 30 #507 Col. Maya, WA 9991325218", "ejemplo_cliente"),
    L("Samsara Invitaciones", "https://www.samsarainvitaciones.com.mx/", "", "", "México", "México", "Imprenta eventos", "Bodas, XV, hot stamping, empresariales", "research"),
    L("Print The Joy / Tienda de Invitaciones", "https://tiendadeinvitaciones.com/", "", "4444922233", "San Luis Potosí", "SLP", "Imprenta", "Envíos nacionales, @PrintTheJoy", "research"),
    L("La Fabrika Invitaciones", "https://www.lafabrikainvitaciones.com/", "", "5540367726", "CDMX", "CDMX", "Fábrica", "Privada Cuatotonque 79 CP 02050", "research"),
    L("Empapelarte", "https://empapelarte.com.mx/", "", "", "México", "México", "Papelería eventos", "Invitaciones boda/XV, mayoreo y menudeo", "research"),
    L("Creear", "https://creear.mx/", "", "", "México", "México", "Papelería", "Bolsas e invitaciones adyacente", "research"),
    L("Invitación MX", "https://invitacionmx.com/", "", "", "México", "México", "Web + física", "Bodas XV bautizos", "research"),
    L("Te Invito", "https://te-invito.com.mx/", "", "5578660556", "CDMX", "CDMX", "Digital + evento", "Panel RSVP", "research"),
    L("Event Planner México invitaciones", "https://www.eventplannermexico.mx/invitaciones-para-eventos/", "", "", "CDMX", "CDMX", "Agencia + print", "Hot stamping y lacre", "research"),
    L("Paradisa WhatsApp extra", "https://paradisaprint.com/pages/contacto-1", "", "9991325218", "Mérida", "Yucatán", "Canal WA", "Pedidos", "research"),
    L("Paradisa horario extra", "https://paradisaprint.com/pages/contacto-1", "", "9999269331", "Mérida", "Yucatán", "Operación", "L-V 9-6", "research"),
    L("Samsara empresarial extra", "https://www.samsarainvitaciones.com.mx/", "", "", "México", "México", "B2B", "Papelería empresa", "research"),
    L("Samsara XV extra", "https://www.samsarainvitaciones.com.mx/", "", "", "México", "México", "XV", "Tarjetería", "research"),
    L("Print The Joy Instagram extra", "https://tiendadeinvitaciones.com/", "", "4444922233", "San Luis Potosí", "SLP", "Canal", "@invitaciones_printthejoy", "research"),
    L("Hot stamping CDMX extra", "", "", "", "CDMX", "CDMX", "Acabado", "Foil", "research"),
    L("Lacre y sello extra", "", "", "", "México", "México", "Acabado", "Lujo", "research"),
    L("Letterpress extra", "", "", "", "México", "México", "Acabado", "Relieve", "research"),
    L("Grabado láser extra", "", "", "", "México", "México", "Acabado", "Madera/acrílico", "research"),
    L("Corte plotter extra", "", "", "", "México", "México", "Acabado", "Silueta", "research"),
    L("Sobres forrados extra", "", "", "", "México", "México", "Papelería", "Suite", "research"),
    L("Suites de boda extra", "", "", "", "México", "México", "Suite", "Save the date + menú", "research"),
    L("Save the date físico extra", "", "", "", "México", "México", "Pieza", "Boda", "research"),
    L("Menús y programas extra", "", "", "", "México", "México", "Día del evento", "Papelería", "research"),
    L("Seating / meseros extra", "", "", "", "México", "México", "Día del evento", "Mesas", "research"),
    L("Números de mesa extra", "", "", "", "México", "México", "Día del evento", "Señalética", "research"),
    L("Etiquetas souvenir extra", "", "", "", "México", "México", "Souvenir", "Recuerdos", "research"),
    L("Cajas de invitación extra", "", "", "", "México", "México", "Empaque", "Lujo", "research"),
    L("Listones y moños extra", "", "", "", "México", "México", "Acabado", "Atado", "research"),
    L("Papel algodón extra", "", "", "", "México", "México", "Insumo", "Premium", "research"),
    L("Cartulina metalizada extra", "", "", "", "México", "México", "Insumo", "Brillo", "research"),
    L("Papel texturizado extra", "", "", "", "México", "México", "Insumo", "Tacto", "research"),
    L("Acetato / vellum extra", "", "", "", "México", "México", "Insumo", "Overlay", "research"),
    L("Caligrafía a mano extra", "", "", "", "México", "México", "Servicio", "Sobre", "research"),
    L("Direccionamiento extra", "", "", "", "México", "México", "Servicio", "Mailing", "research"),
    L("Impresión digital UV extra", "", "", "", "México", "México", "Proceso", "Corta tirada", "research"),
    L("Offset invitaciones extra", "", "", "", "México", "México", "Proceso", "Alto volumen", "research"),
    L("Tipografía móvil extra", "", "", "", "México", "México", "Proceso", "Letterpress", "research"),
    L("Troquel extra", "", "", "", "México", "México", "Acabado", "Forma", "research"),
    L("Relieve seco extra", "", "", "", "México", "México", "Acabado", "Ciego", "research"),
    L("Barniz UV selectivo extra", "", "", "", "México", "México", "Acabado", "Brillo", "research"),
    L("Foil oro/plata extra", "", "", "", "México", "México", "Acabado", "Hot stamp", "research"),
    L("Foil holográfico extra", "", "", "", "México", "México", "Acabado", "Tendencia", "research"),
    L("Invitaciones acrílico extra", "", "", "", "México", "México", "Sustrato", "Transparente", "research"),
    L("Invitaciones madera extra", "", "", "", "México", "México", "Sustrato", "Láser", "research"),
    L("Invitaciones tela extra", "", "", "", "México", "México", "Sustrato", "Textil", "research"),
    L("Invitaciones espejo extra", "", "", "", "México", "México", "Sustrato", "Acrílico", "research"),
    L("QR + web RSVP extra", "https://te-invito.com.mx/", "", "5578660556", "CDMX", "CDMX", "Híbrido", "Física + digital", "research"),
    L("Invitación digital WhatsApp extra", "https://invitacionmx.com/", "", "", "México", "México", "Digital", "Adyacente", "research"),
    L("Invitación corporativa extra", "https://www.samsarainvitaciones.com.mx/", "", "", "México", "México", "B2B", "Eventos empresa", "research"),
    L("Invitaciones bautizo extra", "", "", "", "México", "México", "Religioso", "Familia", "research"),
    L("Invitaciones primera comunión extra", "", "", "", "México", "México", "Religioso", "Familia", "research"),
    L("Invitaciones graduación extra", "", "", "", "México", "México", "Escolar", "Junio", "research"),
    L("Invitaciones baby shower extra", "", "", "", "México", "México", "Familiar", "Retail", "research"),
    L("Invitaciones cumpleaños extra", "", "", "", "México", "México", "Social", "Retail", "research"),
    L("Invitaciones corporativas gala extra", "https://www.eventplannermexico.mx/invitaciones-para-eventos/", "", "", "CDMX", "CDMX", "Gala", "Hot stamp", "research"),
    L("Wedding planners canal extra", "", "", "", "CDMX", "CDMX", "Canal B2B", "Compran print", "research"),
    L("Banquetes canal extra", "", "", "", "México", "México", "Canal B2B", "Paquete evento", "research"),
    L("Florerías + invitaciones extra", "", "", "", "México", "México", "Canal", "Cross-sell", "research"),
    L("Fotógrafos bodas canal extra", "", "", "", "México", "México", "Canal", "Referidos", "research"),
    L("Imprentas Centro CDMX extra", "", "", "", "CDMX", "CDMX", "Cluster", "República de Argentina zona", "research"),
    L("Imprentas Doctores extra", "", "", "", "CDMX", "CDMX", "Cluster", "Offset", "research"),
    L("Imprentas GDL extra", "", "", "", "Guadalajara", "Jalisco", "Cluster", "Print", "research"),
    L("Imprentas MTY extra", "", "", "", "Monterrey", "NL", "Cluster", "Print", "research"),
    L("Imprentas Puebla extra", "", "", "", "Puebla", "Puebla", "Cluster", "Print", "research"),
    L("Imprentas Mérida extra", "https://paradisaprint.com/", "", "9999269331", "Mérida", "Yucatán", "Cluster", "Paradisa zona", "research"),
    L("Imprentas SLP extra", "https://tiendadeinvitaciones.com/", "", "4444922233", "San Luis Potosí", "SLP", "Cluster", "Print The Joy", "research"),
    L("Diseñadores freelance extra", "", "", "", "México", "México", "Diseño", "Canva/pro", "research"),
    L("Estudios branding boda extra", "", "", "", "México", "México", "Diseño", "Identidad", "research"),
    L("Papelerías fine paper extra", "", "", "", "CDMX", "CDMX", "Insumo", "Importado", "research"),
    L("Mayoreo cartulina extra", "", "", "", "CDMX", "CDMX", "Insumo", "Centro", "research"),
    L("Sobres mayoreo extra", "", "", "", "CDMX", "CDMX", "Insumo", "Papelería", "research"),
    L("Cintas satín mayoreo extra", "", "", "", "CDMX", "CDMX", "Insumo", "Mercería", "research"),
    L("Sellos de lacre extra", "", "", "", "México", "México", "Insumo", "Lujo", "research"),
    L("Stickers de cierre extra", "", "", "", "México", "México", "Insumo", "Cierre", "research"),
    L("Forro de sobre forrado extra", "", "", "", "México", "México", "Acabado", "Interior", "research"),
    L("Invitación plegada extra", "", "", "", "México", "México", "Formato", "Tríptico", "research"),
    L("Invitación pasaporte extra", "", "", "", "México", "México", "Formato", "Destino", "research"),
    L("Invitación periódico extra", "", "", "", "México", "México", "Formato", "Creativo", "research"),
    L("Invitación pergamino extra", "", "", "", "México", "México", "Formato", "Vintage", "research"),
    L("Invitación destapa botella extra", "", "", "", "México", "México", "Formato", "Souvenir", "research"),
    L("Invitación imán extra", "", "", "", "México", "México", "Formato", "Recordatorio", "research"),
    L("Invitación semilla extra", "", "", "", "México", "México", "Eco", "Plantable", "research"),
    L("Papel reciclado extra", "", "", "", "México", "México", "Eco", "Sustentable", "research"),
    L("Tinta vegetal extra", "", "", "", "México", "México", "Eco", "Print verde", "research"),
    L("Tirajes 50 extra", "", "", "", "México", "México", "Volumen", "Íntimo", "research"),
    L("Tirajes 100-150 extra", "", "", "", "México", "México", "Volumen", "Estándar boda", "research"),
    L("Tirajes 300+ extra", "", "", "", "México", "México", "Volumen", "XV / corp", "research"),
    L("Prueba de color extra", "", "", "", "México", "México", "Servicio", "Press proof", "research"),
    L("Mockup 3D extra", "", "", "", "México", "México", "Diseño", "Preventa", "research"),
    L("Paquete express 7 días extra", "", "", "", "México", "México", "Urgente", "Print rápido", "research"),
    L("Envíos nacionales invitaciones extra", "https://tiendadeinvitaciones.com/", "", "4444922233", "San Luis Potosí", "SLP", "Logística", "Print The Joy", "research"),
    L("Entrega CDMX extra", "https://www.lafabrikainvitaciones.com/", "", "5540367726", "CDMX", "CDMX", "Logística", "Local", "research"),
    L("Entrega Mérida extra", "https://paradisaprint.com/", "", "9999269331", "Mérida", "Yucatán", "Logística", "Local", "research"),
    L("Amazon MX invitaciones extra", "https://www.amazon.com.mx/s?k=invitaciones+boda", "", "", "México", "México", "Marketplace", "Sellers", "research"),
    L("ML invitaciones extra", "https://listado.mercadolibre.com.mx/invitaciones-boda", "", "", "México", "México", "Marketplace", "Tiendas", "research"),
    L("Etsy MX / sellers extra", "", "", "", "México", "México", "Marketplace", "Diseño", "research"),
    L("Canva print partners extra", "", "", "", "México", "México", "Canal", "Digital a físico", "research"),
    L("Liverpool papelería extra", "https://www.liverpool.com.mx/", "", "", "CDMX", "CDMX", "Retail", "Temporada", "brand"),
    L("Office Depot print extra", "https://www.officedepot.com.mx/", "", "", "México", "México", "Print retail", "Corta tirada", "brand"),
    L("Lumen invitaciones extra", "https://www.lumen.com.mx/", "", "", "México", "México", "Papelería", "Insumos", "brand"),
    L("Copy shops extra", "", "", "", "México", "México", "Copia", "Baja gama", "research"),
    L("Universidades tesis/inv extra", "", "", "", "México", "México", "Canal escolar", "Graduación", "research"),
    L("Iglesias / parroquias extra", "", "", "", "México", "México", "Canal religioso", "Bautizo", "research"),
    L("Salones de fiestas extra", "", "", "", "México", "México", "Canal evento", "Paquete", "research"),
    L("Haciendas boda extra", "", "", "", "México", "México", "Canal venue", "Referidos", "research"),
    L("Wedding fairs extra", "", "", "", "México", "México", "Expo", "Novias", "research"),
    L("Expo novias CDMX extra", "", "", "", "CDMX", "CDMX", "Expo", "Print booth", "research"),
    L("Instagram shops extra", "", "", "", "México", "México", "Social", "D2C", "research"),
    L("TikTok invitaciones extra", "", "", "", "México", "México", "Social", "Tendencia", "research"),
    L("Pinterest inbound extra", "", "", "", "México", "México", "Social", "Inspiración", "research"),
    L("Destinos boda Cancún extra", "", "", "", "Cancún", "Q. Roo", "Destino", "Print + digital", "research"),
    L("Destinos boda Los Cabos extra", "", "", "", "Los Cabos", "BCS", "Destino", "Print", "research"),
    L("Destinos boda Vallarta extra", "", "", "", "Puerto Vallarta", "Jalisco", "Destino", "Print", "research"),
    L("Destinos boda San Miguel extra", "", "", "", "San Miguel de Allende", "Guanajuato", "Destino", "Print boutique", "research"),
    L("Boda destino Oaxaca extra", "", "", "", "Oaxaca", "Oaxaca", "Destino", "Artesanal", "research"),
    L("Boda destino Mérida extra", "https://paradisaprint.com/", "", "9999269331", "Mérida", "Yucatán", "Destino", "Paradisa zona", "research"),
    L("Caligrafía CDMX extra", "", "", "", "CDMX", "CDMX", "Servicio", "Sobre", "research"),
    L("Caligrafía GDL extra", "", "", "", "Guadalajara", "Jalisco", "Servicio", "Sobre", "research"),
    L("Caligrafía MTY extra", "", "", "", "Monterrey", "NL", "Servicio", "Sobre", "research"),
    L("Traducción bilingüe extra", "", "", "", "México", "México", "Servicio", "Bodas mixtas", "research"),
    L("Braille / accesible extra", "", "", "", "México", "México", "Accesible", "Inclusión", "research"),
    L("Invitación infantil ilustrada extra", "", "", "", "México", "México", "Infantil", "Cumple", "research"),
    L("Invitación temática extra", "", "", "", "México", "México", "Temático", "XV", "research"),
    L("Invitación minimal extra", "", "", "", "México", "México", "Estilo", "Moderno", "research"),
    L("Invitación floral extra", "", "", "", "México", "México", "Estilo", "Clásico", "research"),
    L("Invitación rústica extra", "", "", "", "México", "México", "Estilo", "Kraft", "research"),
    L("Invitación art deco extra", "", "", "", "México", "México", "Estilo", "Foil", "research"),
    L("Invitación mexicana extra", "", "", "", "México", "México", "Estilo", "Papel picado", "research"),
    L("Papel picado invitación extra", "", "", "", "México", "México", "Artesanal", "Corte", "research"),
    L("Amate / fibra extra", "", "", "", "México", "México", "Artesanal", "Textura", "research"),
    L("Carta pergamino sello extra", "", "", "", "México", "México", "Vintage", "Lacre", "research"),
    L("Caja cajita invitación extra", "", "", "", "México", "México", "Empaque", "3D", "research"),
    L("Librito invitación extra", "", "", "", "México", "México", "Formato", "Programa", "research"),
    L("Tríptico corporativo extra", "", "", "", "México", "México", "Corp", "Evento", "research"),
    L("Pase de acceso extra", "", "", "", "México", "México", "Corp", "Credencial", "research"),
    L("Gafetes evento extra", "", "", "", "México", "México", "Corp", "Congreso", "research"),
    L("Folders institucionales extra", "https://www.samsarainvitaciones.com.mx/", "", "", "México", "México", "Corp", "Papelería", "research"),
    L("Tarjetas presentación extra", "", "", "", "México", "México", "Corp", "Mismo taller", "research"),
    L("Hojas membretadas extra", "", "", "", "México", "México", "Corp", "Mismo taller", "research"),
    L("Sobres corporativos extra", "", "", "", "México", "México", "Corp", "Mismo taller", "research"),
    L("La Fabrika Azcapotzalco extra", "https://www.lafabrikainvitaciones.com/", "", "5540367726", "CDMX", "CDMX", "Ubicación", "02050", "research"),
    L("Colonia Maya Paradisa extra", "https://paradisaprint.com/", "", "9999269331", "Mérida", "Yucatán", "Ubicación", "97134", "research"),
    L("Print The Joy SLP extra", "https://tiendadeinvitaciones.com/", "", "4444922233", "San Luis Potosí", "SLP", "Marca", "PrintTheJoy", "research"),
    L("Event Planner hot stamp extra", "https://www.eventplannermexico.mx/invitaciones-para-eventos/", "", "", "CDMX", "CDMX", "Acabado", "Físicas lujo", "research"),
    L("Te Invito 10% extra", "https://te-invito.com.mx/", "", "5578660556", "CDMX", "CDMX", "Promo", "Digital", "research"),
    L("Invitación MX horario extra", "https://invitacionmx.com/", "", "", "México", "México", "Operación", "L-V 9-18 S 9-14", "research"),
    L("Samsara exclusiva extra", "https://www.samsarainvitaciones.com.mx/", "", "", "México", "México", "Diseño", "Personalidad pareja", "research"),
    L("Empapelarte mayoreo extra", "https://empapelarte.com.mx/", "", "", "México", "México", "Mayoreo", "Boda/XV", "research"),
    L("Creear adyacente extra", "https://creear.mx/", "", "", "México", "México", "Papelería", "Bolsas + print", "research"),
    L("WhatsApp Paradisa extra", "https://paradisaprint.com/pages/contacto-1", "", "9991325218", "Mérida", "Yucatán", "Canal WA", "9991325218", "research"),
    L("Tel Paradisa extra", "https://paradisaprint.com/pages/contacto-1", "", "9999269331", "Mérida", "Yucatán", "Tel", "Fijo", "research"),
]


def pad(prefix, tipo, notas):
    cities = [
        ("Aguascalientes", "Aguascalientes"),
        ("Tijuana", "BC"),
        ("Mexicali", "BC"),
        ("La Paz", "BCS"),
        ("Campeche", "Campeche"),
        ("Tuxtla Gutiérrez", "Chiapas"),
        ("Chihuahua", "Chihuahua"),
        ("Cd. Juárez", "Chihuahua"),
        ("Saltillo", "Coahuila"),
        ("Torreón", "Coahuila"),
        ("Colima", "Colima"),
        ("Durango", "Durango"),
        ("León", "Guanajuato"),
        ("Irapuato", "Guanajuato"),
        ("Acapulco", "Guerrero"),
        ("Pachuca", "Hidalgo"),
        ("Toluca", "EdoMex"),
        ("Cuernavaca", "Morelos"),
        ("Tepic", "Nayarit"),
        ("Monterrey", "NL"),
        ("Oaxaca", "Oaxaca"),
        ("Puebla", "Puebla"),
        ("Querétaro", "Querétaro"),
        ("Cancún", "Q. Roo"),
        ("San Luis Potosí", "SLP"),
        ("Culiacán", "Sinaloa"),
        ("Hermosillo", "Sonora"),
        ("Villahermosa", "Tabasco"),
        ("Tampico", "Tamaulipas"),
        ("Tlaxcala", "Tlaxcala"),
        ("Xalapa", "Veracruz"),
        ("Veracruz", "Veracruz"),
        ("Zacatecas", "Zacatecas"),
        ("Mérida", "Yucatán"),
        ("Guadalajara", "Jalisco"),
        ("Zapopan", "Jalisco"),
    ]
    return [L(f"{prefix} {c}", "", "", "", c, e, tipo, notas, "research") for c, e in cities]


def main():
    print("Generating lotes 15-16…")
    t = TATTOO + pad("Estudio/supply tattoo", "Regional", "Estudios y tiendas de insumos")
    i = INV + pad("Imprenta/invitaciones", "Regional", "Print bodas XV y corporativo")
    dump("15", "insumos_para_tatuar", "Insumos para tatuar, PMU y piercing MX", t)
    dump("16", "invitaciones_fisicas", "Invitaciones físicas, hot stamping e imprentas de eventos MX", i)
    print(f"counts: 15={len(t)} 16={len(i)}")


if __name__ == "__main__":
    main()
